Ary: <
  DropItemId: 4001101
  DropId: 40011
  ItemId: 20011
  Count: 2
  DropWay: 3
  Probability: 7000
  IsRare: 1
>
Ary: <
  DropItemId: 4001102
  DropId: 40011
  ItemId: 20011
  Count: 5
  DropWay: 3
  Probability: 3000
  IsRare: 1
>
Ary: <
  DropItemId: 4001201
  DropId: 40012
  ItemId: 20011
  Count: 10
  DropWay: 1
  Probability: 10000
>
Ary: <
  DropItemId: 4001301
  DropId: 40013
  ItemId: 20001
  Count: 5
  DropWay: 1
  Probability: 10000
>
Ary: <
  DropItemId: 4001302
  DropId: 40013
  ItemId: 20002
  Count: 2
  DropWay: 1
  Probability: 10000
>
Ary: <
  DropItemId: 4001401
  DropId: 40014
  ItemId: 20003
  Count: 2
  DropWay: 1
  Probability: 10000
  IsRare: 1
>
Ary: <
  DropItemId: 4001402
  DropId: 40014
  ItemId: 20004
  Count: 1
  DropWay: 1
  Probability: 10000
  IsRare: 1
>
Ary: <
  DropItemId: 4001501
  DropId: 40015
  ItemId: 20011
  Count: 3
  DropWay: 1
  Probability: 10000
>
Ary: <
  DropItemId: 4001502
  DropId: 40015
  ItemId: 1
  Count: 1000
  DropWay: 1
  Probability: 10000
>
Ary: <
  DropItemId: 4001601
  DropId: 40016
  ItemId: 1
  Count: 5000
  DropWay: 1
  Probability: 10000
>
Ary: <
  DropItemId: 4001701
  DropId: 40017
  ItemId: 2
  Count: 100
  DropWay: 1
  Probability: 10000
  IsRare: 1
>
Ary: <
  DropItemId: 4002101
  DropId: 40021
  ItemId: 1
  Count: 10000
  DropWay: 1
  Probability: 10000
>
Ary: <
  DropItemId: 4002201
  DropId: 40022
  ItemId: 2
  Count: 50
  DropWay: 1
  Probability: 10000
  IsRare: 1
>
Ary: <
  DropItemId: 4002301
  DropId: 40023
  ItemId: 20011
  Count: 1
  DropWay: 4
  Probability: 2000
  IsRare: 1
>
Ary: <
  DropItemId: 4002302
  DropId: 40023
  ItemId: 1
  Count: 100
  DropWay: 4
  Probability: 10000
>