Ary: <
  Id: 90101001
  UseType: 3
  UseId: 90410101
  UseValue: 1
  IsEnable: 1
>
Ary: <
  Id: 90101002
  UseType: 3
  UseId: 90410102
  UseValue: 1
  IsEnable: 1
>
Ary: <
  Id: 20101001
  UseType: 2
  UseId: 10101002
  UseValue: 100
  IsEnable: 1
>