Ary: <
  Id: 1
  ItemId: 20001
  OutputItemId: 1
  OutputCount: 100
  IsEnable: 1
>
Ary: <
  Id: 2
  ItemId: 20002
  OutputItemId: 1
  OutputCount: 500
  IsEnable: 1
>
Ary: <
  Id: 3
  ItemId: 20003
  OutputItemId: 1
  OutputCount: 2000
  IsEnable: 1
>
Ary: <
  Id: 4
  ItemId: 20004
  OutputItemId: 1
  OutputCount: 10000
  IsEnable: 1
>
Ary: <
  Id: 5
  ItemId: 20011
  OutputItemId: 2
  OutputCount: 5
  IsEnable: 1
>