Ary: <
  Id: 30001
  UseType: 3
  UseId: 50001
  UseValue: 1
  IsEnable: 1
>
Ary: <
  Id: 30002
  UseType: 3
  UseId: 50002
  UseValue: 1
  IsEnable: 1
>
Ary: <
  Id: 30003
  UseType: 3
  UseId: 50003
  UseValue: 1
  IsEnable: 1
>
Ary: <
  Id: 30004
  UseType: 3
  UseId: 50004
  UseValue: 1
  IsEnable: 1
>
Ary: <
  Id: 30005
  UseType: 3
  UseId: 50005
  UseValue: 1
  IsEnable: 1
>
Ary: <
  Id: 30006
  UseType: 3
  UseId: 50006
  UseValue: 1
  IsEnable: 1
>
Ary: <
  Id: 30011
  UseType: 3
  UseId: 50007
  UseValue: 1
  IsEnable: 1
>
Ary: <
  Id: 10005
  UseType: 3
  UseId: 50008
  UseValue: 1
  IsEnable: 1
>
Ary: <
  Id: 10002
  UseType: 2
  UseId: 4
  UseValue: 100
  IsEnable: 1
>
Ary: <
  Id: 10003
  UseType: 2
  UseId: 5
  UseValue: 50
  IsEnable: 1
>
Ary: <
  Id: 10004
  UseType: 2
  UseId: 5
  UseValue: 200
  IsEnable: 1
>