Ary: <
  ItemId: 30001
  RuleId: 3
>
Ary: <
  ItemId: 30002
  RuleId: 3
>
Ary: <
  ItemId: 30003
  RuleId: 3
>
Ary: <
  ItemId: 30004
  RuleId: 3
>
Ary: <
  ItemId: 30005
  RuleId: 3
>
Ary: <
  ItemId: 30006
  RuleId: 3
>
Ary: <
  ItemId: 30011
  RuleId: 3
>
Ary: <
  ItemId: 10005
  RuleId: 3
>
Ary: <
  ItemId: 10001
  RuleId: 2
>
Ary: <
  ItemId: 10002
  RuleId: 2
>
Ary: <
  ItemId: 10003
  RuleId: 2
>
Ary: <
  ItemId: 10004
  RuleId: 2
>
Ary: <
  ItemId: 20001
  RuleId: 4
>
Ary: <
  ItemId: 20002
  RuleId: 4
>
Ary: <
  ItemId: 20003
  RuleId: 4
>
Ary: <
  ItemId: 20004
  RuleId: 4
>
Ary: <
  ItemId: 20011
  RuleId: 4
>
Ary: <
  ItemId: 70001
  RuleId: 2
>
Ary: <
  ItemId: 70002
  RuleId: 2
>
Ary: <
  ItemId: 70003
  RuleId: 2
>
Ary: <
  ItemId: 70004
  RuleId: 2
>
Ary: <
  ItemId: 70005
  RuleId: 2
>
Ary: <
  ItemId: 70006
  RuleId: 2
>
Ary: <
  ItemId: 70007
  RuleId: 2
>
Ary: <
  ItemId: 70008
  RuleId: 2
>
Ary: <
  ItemId: 70011
  RuleId: 2
>