Ary: <
  Round: 1
  Publics: <
    Values: "A1"
    Values: "J3"
    Values: "K1"
  >
  Publics: <
    Values: "21"
    Values: "31"
  >
  Chair1: <
    Values: <
      Values: 31.12
      Values: 44.111
    >
    Values: <
      Values: 978.012
      Values: 7876.73
    >
  >
  Chair1: <
    Values: <
      Values: 31.12
      Values: 44.111
    >
    Values: <
      Values: 978.012
      Values: 7876.73
    >
  >
  Chair2: "A3,Q1"
  Chair3: "A2,J2"
  Chair4: "A2,J2"
  Chair5: "A3,Q2"
  Chair6: "A2,J3"
  Chair7: "A2,J3"
  Chair8: "A3,Q3"
  Chair9: "A2,J4"
  Chair10: "A2,J4"
>
Ary: <
  Round: 2
  Publics: <
    Values: "A1"
    Values: "J3"
    Values: "K1"
  >
  Publics: <
    Values: "21"
    Values: "31"
  >
  Chair1: <
    Values: <
      Values: 31.12
      Values: 44.111
    >
    Values: <
      Values: 978.012
      Values: 7876.73
    >
  >
  Chair1: <
    Values: <
      Values: 31.12
      Values: 44.111
    >
    Values: <
      Values: 978.012
      Values: 7876.73
    >
  >
  Chair2: "A3,Q1"
  Chair3: "A2,J2"
  Chair4: "A2,J2"
  Chair5: "A3,Q2"
  Chair6: "A2,J3"
  Chair7: "A2,J3"
  Chair8: "A3,Q3"
  Chair9: "A2,J4"
  Chair10: "A2,J4"
>
Ary: <
  Round: 3
  Publics: <
    Values: "A1"
    Values: "J3"
    Values: "K1"
  >
  Publics: <
    Values: "21"
    Values: "31"
  >
  Chair1: <
    Values: <
      Values: 31.12
      Values: 44.111
    >
    Values: <
      Values: 978.012
      Values: 7876.73
    >
  >
  Chair1: <
    Values: <
      Values: 31.12
      Values: 44.111
    >
    Values: <
      Values: 978.012
      Values: 7876.73
    >
  >
  Chair2: "A3,Q1"
  Chair3: "A2,J2"
  Chair4: "A2,J2"
  Chair5: "A3,Q2"
  Chair6: "A2,J3"
  Chair7: "A2,J3"
  Chair8: "A3,Q3"
  Chair9: "A2,J4"
  Chair10: "A2,J4"
>
Ary: <
  Round: 4
  Publics: <
    Values: "A1"
    Values: "J3"
    Values: "K1"
  >
  Publics: <
    Values: "21"
    Values: "31"
  >
  Chair1: <
    Values: <
      Values: 31.12
      Values: 44.111
    >
    Values: <
      Values: 978.012
      Values: 7876.73
    >
  >
  Chair1: <
    Values: <
      Values: 31.12
      Values: 44.111
    >
    Values: <
      Values: 978.012
      Values: 7876.73
    >
  >
  Chair2: "A3,Q1"
  Chair3: "A2,J2"
  Chair4: "A2,J2"
  Chair5: "A3,Q2"
  Chair6: "A2,J3"
  Chair7: "A2,J3"
  Chair8: "A3,Q3"
  Chair9: "A2,J4"
  Chair10: "A2,J4"
>