// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: core/cmd.proto

package g1_protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CMD int32

const (
	CMD__CMD_ZERO CMD = 0
	// 强制下线
	CMD_SC_KICK_OUT CMD = 12289
	// 同步玩家数据
	CMD_SC_SYNC_USER_DATA CMD = 12290
	// 聊天信息推送
	CMD_SC_CHAT CMD = 12291
	// 通知客户端数据有变动
	CMD_SC_DATA_CHANGE_NOTIFY CMD = 12292
	// 同步玩家数据（全量 section + 增量 patch，与 SC_SYNC_USER_DATA 并存）
	CMD_SC_SYNC_USER_DATA_V2 CMD = 12294
	// 恭喜获得：奖励展示聚合推送
	CMD_SC_OBTAIN_NOTICE   CMD = 12295
	CMD_CONN_KICK_OUT_REQ  CMD = 69632
	CMD_CONN_KICK_OUT_RSP  CMD = 69633
	CMD_CONN_BROADCAST_REQ CMD = 69634
	CMD_CONN_BROADCAST_RSP CMD = 69635
	// 登陆
	CMD_MAIN_LOGIN_REQ CMD = 131072
	CMD_MAIN_LOGIN_RSP CMD = 131073
	// 登出
	CMD_MAIN_LOGOUT_REQ CMD = 131074
	CMD_MAIN_LOGOUT_RSP CMD = 131075
	// 心跳
	CMD_MAIN_HEARTBEAT_REQ CMD = 131076
	CMD_MAIN_HEARTBEAT_RSP CMD = 131077
	// 道具使用
	CMD_MAIN_ITEM_USE_REQ CMD = 131078
	CMD_MAIN_ITEM_USE_RSP CMD = 131079
	// 改名
	CMD_MAIN_CHANGE_NAME_REQ CMD = 131080
	CMD_MAIN_CHANGE_NAME_RSP CMD = 131081
	// 改头像
	CMD_MAIN_CHANGE_ICON_REQ CMD = 131082
	CMD_MAIN_CHANGE_ICON_RSP CMD = 131083
	// 出售道具
	CMD_MAIN_ITEM_SELL_REQ CMD = 131084
	CMD_MAIN_ITEM_SELL_RSP CMD = 131085
	// 分解道具
	CMD_MAIN_ITEM_DECOMPOSE_REQ CMD = 131086
	CMD_MAIN_ITEM_DECOMPOSE_RSP CMD = 131087
	// 背包查询(分类分页)
	CMD_MAIN_BACKPACK_QUERY_REQ CMD = 131088
	CMD_MAIN_BACKPACK_QUERY_RSP CMD = 131089
	// 批量添加道具(GM/测试)
	CMD_MAIN_ITEM_BATCH_ADD_REQ CMD = 131090
	CMD_MAIN_ITEM_BATCH_ADD_RSP CMD = 131091
	// ~~~~~~~~~~~~引导功能~~~~~~~~~~~~~~~~~~
	// 发送已经完成的ID
	CMD_GUIDE_COMPLETED_REQ CMD = 131508
	CMD_GUIDE_COMPLETED_RSP CMD = 131509
	// 发送正在进行的ID
	CMD_GUIDE_IN_PROGRESS_REQ CMD = 131510
	CMD_GUIDE_IN_PROGRESS_RSP CMD = 131511
	// 购买礼包
	CMD_MAIN_MALL_BUY_PACKAGE_REQ CMD = 131504
	CMD_MAIN_MALL_BUY_PACKAGE_RSP CMD = 131505
	// 充值
	CMD_MAIN_MALL_RECHARGE_REQ CMD = 131506
	CMD_MAIN_MALL_RECHARGE_RSP CMD = 131507
	// ~~~~~~~~~~主线任务相关~~~~~~~~~~
	// 完成主线任务
	CMD_MAIN_TASK_FINISH_REQ CMD = 131536
	CMD_MAIN_TASK_FINISH_RSP CMD = 131537
	// ~~~~~~~~~~通知类~~~~~~~~~
	// 单个任务更新通知
	CMD_MAIN_NOTIFY_ACTIVITY_TASK_SINGLE_UPDATE CMD = 143361
	// 设置角色信息
	CMD_MAIN_GM_GET_ROLE_REQ          CMD = 172032
	CMD_MAIN_GM_GET_ROLE_RSP          CMD = 172033
	CMD_MAIN_GM_SET_ROLE_REQ          CMD = 172034
	CMD_MAIN_GM_SET_ROLE_RSP          CMD = 172035
	CMD_MAIN_GM_ADD_ITEM_REQ          CMD = 172036
	CMD_MAIN_GM_ADD_ITEM_RSP          CMD = 172037
	CMD_INFO_GET_BRIEF_INFO_REQ       CMD = 196608
	CMD_INFO_GET_BRIEF_INFO_RSP       CMD = 196609
	CMD_INFO_GET_ICON_DESC_REQ        CMD = 196610
	CMD_INFO_GET_ICON_DESC_RSP        CMD = 196611
	CMD_INFO_INNER_SET_BRIEF_INFO_REQ CMD = 200704
	CMD_INFO_INNER_SET_BRIEF_INFO_RSP CMD = 200705
	// -------- MailSvr (server_type = 6) --------
	CMD_MAIL_GET_MAIL_LIST_REQ   CMD = 393216 // 获取邮件
	CMD_MAIL_GET_MAIL_LIST_RSP   CMD = 393217
	CMD_MAIL_READ_MAIL_REQ       CMD = 393218 // 阅读邮件
	CMD_MAIL_READ_MAIL_RSP       CMD = 393219
	CMD_MAIL_DEL_MAIL_REQ        CMD = 393220 // 删除邮件
	CMD_MAIL_DEL_MAIL_RSP        CMD = 393221
	CMD_MAIL_GET_MAIL_ATTACH_REQ CMD = 393222 // 领取附件
	CMD_MAIL_GET_MAIL_ATTACH_RSP CMD = 393223
	CMD_MAIL_INNER_ADD_MAIL_REQ  CMD = 397312 // 添加邮件
	CMD_MAIL_INNER_ADD_MAIL_RSP  CMD = 397313
	// 发送聊天
	CMD_CHAT_CHAT_REQ CMD = 458752
	CMD_CHAT_CHAT_RSP CMD = 458753
	// 获取聊天信息
	CMD_CHAT_GET_CHAT_INFO_REQ CMD = 458754
	CMD_CHAT_GET_CHAT_INFO_RSP CMD = 458755
	// 删除好友聊天数据
	CMD_CHAT_DEL_CHAT_REQ CMD = 458756
	CMD_CHAT_DEL_CHAT_RSP CMD = 458757
	// 获取社交信息
	CMD_FRIEND_GET_FRIEND_INFO_REQ CMD = 524288
	CMD_FRIEND_GET_FRIEND_INFO_RSP CMD = 524289
	// 添加好友
	CMD_FRIEND_ADD_FRIEND_REQ CMD = 524290
	CMD_FRIEND_ADD_FRIEND_RSP CMD = 524291
	// 确认添加好友
	CMD_FRIEND_CONFIRM_FRIEND_REQ CMD = 524292
	CMD_FRIEND_CONFIRM_FRIEND_RSP CMD = 524293
	// 屏蔽玩家
	CMD_FRIEND_SHIELD_USER_REQ CMD = 524294
	CMD_FRIEND_SHIELD_USER_RSP CMD = 524295
	// 搜索玩家
	CMD_FRIEND_SEARCH_ROLE_REQ          CMD = 524296
	CMD_FRIEND_SEARCH_ROLE_RSP          CMD = 524297
	CMD_FRIEND_INNER_ADD_FRIEND_REQ     CMD = 528384
	CMD_FRIEND_INNER_ADD_FRIEND_RSP     CMD = 528385
	CMD_FRIEND_INNER_CONFIRM_FRIEND_REQ CMD = 528386
	CMD_FRIEND_INNER_CONFIRM_FRIEND_RSP CMD = 528387
	// -------- mysqlsvr(server_type = 4) --------
	CMD_MYSQL_INNER_UPDATE_ROLE_INFO_REQ CMD = 266240
	CMD_MYSQL_INNER_UPDATE_ROLE_INFO_RSP CMD = 266241
	CMD_MYSQL_INNER_SEARCH_ROLE_REQ      CMD = 266242
	CMD_MYSQL_INNER_SEARCH_ROLE_RSP      CMD = 266243
	// 向数据库查询礼包码
	CMD_MYSQL_INNER_SEARCH_GIFT_CODE_REQ CMD = 266244
	CMD_MYSQL_INNER_SEARCH_GIFT_CODE_RSP CMD = 266245
	// 角色全量快照（L3 持久层）：写回（双写异步路径）与回源读（冷登录）
	CMD_MYSQL_INNER_SAVE_ROLE_DATA_REQ CMD = 266254
	CMD_MYSQL_INNER_SAVE_ROLE_DATA_RSP CMD = 266255
	CMD_MYSQL_INNER_LOAD_ROLE_DATA_REQ CMD = 266256
	CMD_MYSQL_INNER_LOAD_ROLE_DATA_RSP CMD = 266257
)

// Enum value maps for CMD.
var (
	CMD_name = map[int32]string{
		0:      "_CMD_ZERO",
		12289:  "SC_KICK_OUT",
		12290:  "SC_SYNC_USER_DATA",
		12291:  "SC_CHAT",
		12292:  "SC_DATA_CHANGE_NOTIFY",
		12294:  "SC_SYNC_USER_DATA_V2",
		12295:  "SC_OBTAIN_NOTICE",
		69632:  "CONN_KICK_OUT_REQ",
		69633:  "CONN_KICK_OUT_RSP",
		69634:  "CONN_BROADCAST_REQ",
		69635:  "CONN_BROADCAST_RSP",
		131072: "MAIN_LOGIN_REQ",
		131073: "MAIN_LOGIN_RSP",
		131074: "MAIN_LOGOUT_REQ",
		131075: "MAIN_LOGOUT_RSP",
		131076: "MAIN_HEARTBEAT_REQ",
		131077: "MAIN_HEARTBEAT_RSP",
		131078: "MAIN_ITEM_USE_REQ",
		131079: "MAIN_ITEM_USE_RSP",
		131080: "MAIN_CHANGE_NAME_REQ",
		131081: "MAIN_CHANGE_NAME_RSP",
		131082: "MAIN_CHANGE_ICON_REQ",
		131083: "MAIN_CHANGE_ICON_RSP",
		131084: "MAIN_ITEM_SELL_REQ",
		131085: "MAIN_ITEM_SELL_RSP",
		131086: "MAIN_ITEM_DECOMPOSE_REQ",
		131087: "MAIN_ITEM_DECOMPOSE_RSP",
		131088: "MAIN_BACKPACK_QUERY_REQ",
		131089: "MAIN_BACKPACK_QUERY_RSP",
		131090: "MAIN_ITEM_BATCH_ADD_REQ",
		131091: "MAIN_ITEM_BATCH_ADD_RSP",
		131508: "GUIDE_COMPLETED_REQ",
		131509: "GUIDE_COMPLETED_RSP",
		131510: "GUIDE_IN_PROGRESS_REQ",
		131511: "GUIDE_IN_PROGRESS_RSP",
		131504: "MAIN_MALL_BUY_PACKAGE_REQ",
		131505: "MAIN_MALL_BUY_PACKAGE_RSP",
		131506: "MAIN_MALL_RECHARGE_REQ",
		131507: "MAIN_MALL_RECHARGE_RSP",
		131536: "MAIN_TASK_FINISH_REQ",
		131537: "MAIN_TASK_FINISH_RSP",
		143361: "MAIN_NOTIFY_ACTIVITY_TASK_SINGLE_UPDATE",
		172032: "MAIN_GM_GET_ROLE_REQ",
		172033: "MAIN_GM_GET_ROLE_RSP",
		172034: "MAIN_GM_SET_ROLE_REQ",
		172035: "MAIN_GM_SET_ROLE_RSP",
		172036: "MAIN_GM_ADD_ITEM_REQ",
		172037: "MAIN_GM_ADD_ITEM_RSP",
		196608: "INFO_GET_BRIEF_INFO_REQ",
		196609: "INFO_GET_BRIEF_INFO_RSP",
		196610: "INFO_GET_ICON_DESC_REQ",
		196611: "INFO_GET_ICON_DESC_RSP",
		200704: "INFO_INNER_SET_BRIEF_INFO_REQ",
		200705: "INFO_INNER_SET_BRIEF_INFO_RSP",
		393216: "MAIL_GET_MAIL_LIST_REQ",
		393217: "MAIL_GET_MAIL_LIST_RSP",
		393218: "MAIL_READ_MAIL_REQ",
		393219: "MAIL_READ_MAIL_RSP",
		393220: "MAIL_DEL_MAIL_REQ",
		393221: "MAIL_DEL_MAIL_RSP",
		393222: "MAIL_GET_MAIL_ATTACH_REQ",
		393223: "MAIL_GET_MAIL_ATTACH_RSP",
		397312: "MAIL_INNER_ADD_MAIL_REQ",
		397313: "MAIL_INNER_ADD_MAIL_RSP",
		458752: "CHAT_CHAT_REQ",
		458753: "CHAT_CHAT_RSP",
		458754: "CHAT_GET_CHAT_INFO_REQ",
		458755: "CHAT_GET_CHAT_INFO_RSP",
		458756: "CHAT_DEL_CHAT_REQ",
		458757: "CHAT_DEL_CHAT_RSP",
		524288: "FRIEND_GET_FRIEND_INFO_REQ",
		524289: "FRIEND_GET_FRIEND_INFO_RSP",
		524290: "FRIEND_ADD_FRIEND_REQ",
		524291: "FRIEND_ADD_FRIEND_RSP",
		524292: "FRIEND_CONFIRM_FRIEND_REQ",
		524293: "FRIEND_CONFIRM_FRIEND_RSP",
		524294: "FRIEND_SHIELD_USER_REQ",
		524295: "FRIEND_SHIELD_USER_RSP",
		524296: "FRIEND_SEARCH_ROLE_REQ",
		524297: "FRIEND_SEARCH_ROLE_RSP",
		528384: "FRIEND_INNER_ADD_FRIEND_REQ",
		528385: "FRIEND_INNER_ADD_FRIEND_RSP",
		528386: "FRIEND_INNER_CONFIRM_FRIEND_REQ",
		528387: "FRIEND_INNER_CONFIRM_FRIEND_RSP",
		266240: "MYSQL_INNER_UPDATE_ROLE_INFO_REQ",
		266241: "MYSQL_INNER_UPDATE_ROLE_INFO_RSP",
		266242: "MYSQL_INNER_SEARCH_ROLE_REQ",
		266243: "MYSQL_INNER_SEARCH_ROLE_RSP",
		266244: "MYSQL_INNER_SEARCH_GIFT_CODE_REQ",
		266245: "MYSQL_INNER_SEARCH_GIFT_CODE_RSP",
		266254: "MYSQL_INNER_SAVE_ROLE_DATA_REQ",
		266255: "MYSQL_INNER_SAVE_ROLE_DATA_RSP",
		266256: "MYSQL_INNER_LOAD_ROLE_DATA_REQ",
		266257: "MYSQL_INNER_LOAD_ROLE_DATA_RSP",
	}
	CMD_value = map[string]int32{
		"_CMD_ZERO":                               0,
		"SC_KICK_OUT":                             12289,
		"SC_SYNC_USER_DATA":                       12290,
		"SC_CHAT":                                 12291,
		"SC_DATA_CHANGE_NOTIFY":                   12292,
		"SC_SYNC_USER_DATA_V2":                    12294,
		"SC_OBTAIN_NOTICE":                        12295,
		"CONN_KICK_OUT_REQ":                       69632,
		"CONN_KICK_OUT_RSP":                       69633,
		"CONN_BROADCAST_REQ":                      69634,
		"CONN_BROADCAST_RSP":                      69635,
		"MAIN_LOGIN_REQ":                          131072,
		"MAIN_LOGIN_RSP":                          131073,
		"MAIN_LOGOUT_REQ":                         131074,
		"MAIN_LOGOUT_RSP":                         131075,
		"MAIN_HEARTBEAT_REQ":                      131076,
		"MAIN_HEARTBEAT_RSP":                      131077,
		"MAIN_ITEM_USE_REQ":                       131078,
		"MAIN_ITEM_USE_RSP":                       131079,
		"MAIN_CHANGE_NAME_REQ":                    131080,
		"MAIN_CHANGE_NAME_RSP":                    131081,
		"MAIN_CHANGE_ICON_REQ":                    131082,
		"MAIN_CHANGE_ICON_RSP":                    131083,
		"MAIN_ITEM_SELL_REQ":                      131084,
		"MAIN_ITEM_SELL_RSP":                      131085,
		"MAIN_ITEM_DECOMPOSE_REQ":                 131086,
		"MAIN_ITEM_DECOMPOSE_RSP":                 131087,
		"MAIN_BACKPACK_QUERY_REQ":                 131088,
		"MAIN_BACKPACK_QUERY_RSP":                 131089,
		"MAIN_ITEM_BATCH_ADD_REQ":                 131090,
		"MAIN_ITEM_BATCH_ADD_RSP":                 131091,
		"GUIDE_COMPLETED_REQ":                     131508,
		"GUIDE_COMPLETED_RSP":                     131509,
		"GUIDE_IN_PROGRESS_REQ":                   131510,
		"GUIDE_IN_PROGRESS_RSP":                   131511,
		"MAIN_MALL_BUY_PACKAGE_REQ":               131504,
		"MAIN_MALL_BUY_PACKAGE_RSP":               131505,
		"MAIN_MALL_RECHARGE_REQ":                  131506,
		"MAIN_MALL_RECHARGE_RSP":                  131507,
		"MAIN_TASK_FINISH_REQ":                    131536,
		"MAIN_TASK_FINISH_RSP":                    131537,
		"MAIN_NOTIFY_ACTIVITY_TASK_SINGLE_UPDATE": 143361,
		"MAIN_GM_GET_ROLE_REQ":                    172032,
		"MAIN_GM_GET_ROLE_RSP":                    172033,
		"MAIN_GM_SET_ROLE_REQ":                    172034,
		"MAIN_GM_SET_ROLE_RSP":                    172035,
		"MAIN_GM_ADD_ITEM_REQ":                    172036,
		"MAIN_GM_ADD_ITEM_RSP":                    172037,
		"INFO_GET_BRIEF_INFO_REQ":                 196608,
		"INFO_GET_BRIEF_INFO_RSP":                 196609,
		"INFO_GET_ICON_DESC_REQ":                  196610,
		"INFO_GET_ICON_DESC_RSP":                  196611,
		"INFO_INNER_SET_BRIEF_INFO_REQ":           200704,
		"INFO_INNER_SET_BRIEF_INFO_RSP":           200705,
		"MAIL_GET_MAIL_LIST_REQ":                  393216,
		"MAIL_GET_MAIL_LIST_RSP":                  393217,
		"MAIL_READ_MAIL_REQ":                      393218,
		"MAIL_READ_MAIL_RSP":                      393219,
		"MAIL_DEL_MAIL_REQ":                       393220,
		"MAIL_DEL_MAIL_RSP":                       393221,
		"MAIL_GET_MAIL_ATTACH_REQ":                393222,
		"MAIL_GET_MAIL_ATTACH_RSP":                393223,
		"MAIL_INNER_ADD_MAIL_REQ":                 397312,
		"MAIL_INNER_ADD_MAIL_RSP":                 397313,
		"CHAT_CHAT_REQ":                           458752,
		"CHAT_CHAT_RSP":                           458753,
		"CHAT_GET_CHAT_INFO_REQ":                  458754,
		"CHAT_GET_CHAT_INFO_RSP":                  458755,
		"CHAT_DEL_CHAT_REQ":                       458756,
		"CHAT_DEL_CHAT_RSP":                       458757,
		"FRIEND_GET_FRIEND_INFO_REQ":              524288,
		"FRIEND_GET_FRIEND_INFO_RSP":              524289,
		"FRIEND_ADD_FRIEND_REQ":                   524290,
		"FRIEND_ADD_FRIEND_RSP":                   524291,
		"FRIEND_CONFIRM_FRIEND_REQ":               524292,
		"FRIEND_CONFIRM_FRIEND_RSP":               524293,
		"FRIEND_SHIELD_USER_REQ":                  524294,
		"FRIEND_SHIELD_USER_RSP":                  524295,
		"FRIEND_SEARCH_ROLE_REQ":                  524296,
		"FRIEND_SEARCH_ROLE_RSP":                  524297,
		"FRIEND_INNER_ADD_FRIEND_REQ":             528384,
		"FRIEND_INNER_ADD_FRIEND_RSP":             528385,
		"FRIEND_INNER_CONFIRM_FRIEND_REQ":         528386,
		"FRIEND_INNER_CONFIRM_FRIEND_RSP":         528387,
		"MYSQL_INNER_UPDATE_ROLE_INFO_REQ":        266240,
		"MYSQL_INNER_UPDATE_ROLE_INFO_RSP":        266241,
		"MYSQL_INNER_SEARCH_ROLE_REQ":             266242,
		"MYSQL_INNER_SEARCH_ROLE_RSP":             266243,
		"MYSQL_INNER_SEARCH_GIFT_CODE_REQ":        266244,
		"MYSQL_INNER_SEARCH_GIFT_CODE_RSP":        266245,
		"MYSQL_INNER_SAVE_ROLE_DATA_REQ":          266254,
		"MYSQL_INNER_SAVE_ROLE_DATA_RSP":          266255,
		"MYSQL_INNER_LOAD_ROLE_DATA_REQ":          266256,
		"MYSQL_INNER_LOAD_ROLE_DATA_RSP":          266257,
	}
)

func (x CMD) Enum() *CMD {
	p := new(CMD)
	*p = x
	return p
}

func (x CMD) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CMD) Descriptor() protoreflect.EnumDescriptor {
	return file_core_cmd_proto_enumTypes[0].Descriptor()
}

func (CMD) Type() protoreflect.EnumType {
	return &file_core_cmd_proto_enumTypes[0]
}

func (x CMD) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CMD.Descriptor instead.
func (CMD) EnumDescriptor() ([]byte, []int) {
	return file_core_cmd_proto_rawDescGZIP(), []int{0}
}

// [ 结构名 = cmd Val] client映射结构名使用，需要跟上面的定义同步增加
type CmdTo int32

const (
	CmdTo__ZERO CmdTo = 0
	// 强制下线
	CmdTo_ScKickOut CmdTo = 12289
	// 同步玩家数据
	CmdTo_ScSyncUserData   CmdTo = 12290
	CmdTo_ScSyncUserDataV2 CmdTo = 12294
	// 聊天信息推送
	CmdTo_ScChat CmdTo = 12291
	// 通知客户端数据有变动
	CmdTo_ScDataChangeNotify CmdTo = 12292
	CmdTo_ConnKickOutReq     CmdTo = 69632
	CmdTo_ConnKickOutRsp     CmdTo = 69633
	CmdTo_ConnBroadcastReq   CmdTo = 69634
	CmdTo_ConnBroadcastRsp   CmdTo = 69635
	// 登陆
	CmdTo_LoginReq CmdTo = 131072
	CmdTo_LoginRsp CmdTo = 131073
	// 登出
	CmdTo_LogoutReq CmdTo = 131074
	CmdTo_LogoutRsp CmdTo = 131075
	// 心跳
	CmdTo_HeartBeatReq CmdTo = 131076
	CmdTo_HeartBeatRsp CmdTo = 131077
	// 道具使用
	CmdTo_ItemUseReq CmdTo = 131078
	CmdTo_ItemUseRsp CmdTo = 131079
	// 改名
	CmdTo_ChangeNameReq CmdTo = 131080
	CmdTo_ChangeNameRsp CmdTo = 131081
	// 改头像
	CmdTo_ChangeIconReq CmdTo = 131082
	CmdTo_ChangeIconRsp CmdTo = 131083
	// ~~~~~~~~~~~~引导功能~~~~~~~~~~~~~~~~~~
	// 发送已经完成的ID
	CmdTo_GuideCompletedReq CmdTo = 131508
	CmdTo_GuideCompletedRsp CmdTo = 131509
	// 发送正在进行的ID
	CmdTo_GuideInProgressReq CmdTo = 131510
	CmdTo_GuideInProgressRsp CmdTo = 131511
	// 购买礼包
	CmdTo_MallBuyPackageReq CmdTo = 131504
	CmdTo_MallBuyPackageRsp CmdTo = 131505
	// 充值
	CmdTo_MallRechargeReq CmdTo = 131506
	CmdTo_MallRechargeRsp CmdTo = 131507
	// ~~~~~~~~~~主线任务相关~~~~~~~~~~
	// 完成主线任务
	CmdTo_MainTaskFinishReq CmdTo = 131536
	CmdTo_MainTaskFinishRsp CmdTo = 131537
	// 获取邮件
	CmdTo_GetMailListReq CmdTo = 393216
	CmdTo_GetMailListRsp CmdTo = 393217
	// 阅读邮件
	CmdTo_ReadMailReq CmdTo = 393218
	CmdTo_ReadMailRsp CmdTo = 393219
	// 删除邮件
	CmdTo_DelMailReq CmdTo = 393220
	CmdTo_DelMailRsp CmdTo = 393221
	// 领取附件
	CmdTo_GetMailAttachReq CmdTo = 393222
	CmdTo_GetMailAttachRsp CmdTo = 393223
	// 发送聊天
	CmdTo_ChatChatReq CmdTo = 458752
	CmdTo_ChatChatRsp CmdTo = 458753
	// 获取聊天信息
	CmdTo_ChatGetChatInfoReq CmdTo = 458754
	CmdTo_ChatGetChatInfoRsp CmdTo = 458755
	// 删除好友聊天数据
	CmdTo_ChatDelChatReq CmdTo = 458756
	CmdTo_ChatDelChatRsp CmdTo = 458757
	// 获取社交信息
	CmdTo_FriendGetFriendInfoReq CmdTo = 524288
	CmdTo_FriendGetFriendInfoRsp CmdTo = 524289
	// 添加好友
	CmdTo_FriendAddFriendReq CmdTo = 524290
	CmdTo_FriendAddFriendRsp CmdTo = 524291
	// 确认添加好友
	CmdTo_FriendConfirmFriendReq CmdTo = 524292
	CmdTo_FriendConfirmFriendRsp CmdTo = 524293
	// 屏蔽玩家
	CmdTo_FriendShieldUserReq CmdTo = 524294
	CmdTo_FriendShieldUserRsp CmdTo = 524295
	// 搜索玩家
	CmdTo_FriendSearchRoleReq CmdTo = 524296
	CmdTo_FriendSearchRoleRsp CmdTo = 524297
)

// Enum value maps for CmdTo.
var (
	CmdTo_name = map[int32]string{
		0:      "_ZERO",
		12289:  "ScKickOut",
		12290:  "ScSyncUserData",
		12294:  "ScSyncUserDataV2",
		12291:  "ScChat",
		12292:  "ScDataChangeNotify",
		69632:  "ConnKickOutReq",
		69633:  "ConnKickOutRsp",
		69634:  "ConnBroadcastReq",
		69635:  "ConnBroadcastRsp",
		131072: "LoginReq",
		131073: "LoginRsp",
		131074: "LogoutReq",
		131075: "LogoutRsp",
		131076: "HeartBeatReq",
		131077: "HeartBeatRsp",
		131078: "ItemUseReq",
		131079: "ItemUseRsp",
		131080: "ChangeNameReq",
		131081: "ChangeNameRsp",
		131082: "ChangeIconReq",
		131083: "ChangeIconRsp",
		131508: "GuideCompletedReq",
		131509: "GuideCompletedRsp",
		131510: "GuideInProgressReq",
		131511: "GuideInProgressRsp",
		131504: "MallBuyPackageReq",
		131505: "MallBuyPackageRsp",
		131506: "MallRechargeReq",
		131507: "MallRechargeRsp",
		131536: "MainTaskFinishReq",
		131537: "MainTaskFinishRsp",
		393216: "GetMailListReq",
		393217: "GetMailListRsp",
		393218: "ReadMailReq",
		393219: "ReadMailRsp",
		393220: "DelMailReq",
		393221: "DelMailRsp",
		393222: "GetMailAttachReq",
		393223: "GetMailAttachRsp",
		458752: "ChatChatReq",
		458753: "ChatChatRsp",
		458754: "ChatGetChatInfoReq",
		458755: "ChatGetChatInfoRsp",
		458756: "ChatDelChatReq",
		458757: "ChatDelChatRsp",
		524288: "FriendGetFriendInfoReq",
		524289: "FriendGetFriendInfoRsp",
		524290: "FriendAddFriendReq",
		524291: "FriendAddFriendRsp",
		524292: "FriendConfirmFriendReq",
		524293: "FriendConfirmFriendRsp",
		524294: "FriendShieldUserReq",
		524295: "FriendShieldUserRsp",
		524296: "FriendSearchRoleReq",
		524297: "FriendSearchRoleRsp",
	}
	CmdTo_value = map[string]int32{
		"_ZERO":                  0,
		"ScKickOut":              12289,
		"ScSyncUserData":         12290,
		"ScSyncUserDataV2":       12294,
		"ScChat":                 12291,
		"ScDataChangeNotify":     12292,
		"ConnKickOutReq":         69632,
		"ConnKickOutRsp":         69633,
		"ConnBroadcastReq":       69634,
		"ConnBroadcastRsp":       69635,
		"LoginReq":               131072,
		"LoginRsp":               131073,
		"LogoutReq":              131074,
		"LogoutRsp":              131075,
		"HeartBeatReq":           131076,
		"HeartBeatRsp":           131077,
		"ItemUseReq":             131078,
		"ItemUseRsp":             131079,
		"ChangeNameReq":          131080,
		"ChangeNameRsp":          131081,
		"ChangeIconReq":          131082,
		"ChangeIconRsp":          131083,
		"GuideCompletedReq":      131508,
		"GuideCompletedRsp":      131509,
		"GuideInProgressReq":     131510,
		"GuideInProgressRsp":     131511,
		"MallBuyPackageReq":      131504,
		"MallBuyPackageRsp":      131505,
		"MallRechargeReq":        131506,
		"MallRechargeRsp":        131507,
		"MainTaskFinishReq":      131536,
		"MainTaskFinishRsp":      131537,
		"GetMailListReq":         393216,
		"GetMailListRsp":         393217,
		"ReadMailReq":            393218,
		"ReadMailRsp":            393219,
		"DelMailReq":             393220,
		"DelMailRsp":             393221,
		"GetMailAttachReq":       393222,
		"GetMailAttachRsp":       393223,
		"ChatChatReq":            458752,
		"ChatChatRsp":            458753,
		"ChatGetChatInfoReq":     458754,
		"ChatGetChatInfoRsp":     458755,
		"ChatDelChatReq":         458756,
		"ChatDelChatRsp":         458757,
		"FriendGetFriendInfoReq": 524288,
		"FriendGetFriendInfoRsp": 524289,
		"FriendAddFriendReq":     524290,
		"FriendAddFriendRsp":     524291,
		"FriendConfirmFriendReq": 524292,
		"FriendConfirmFriendRsp": 524293,
		"FriendShieldUserReq":    524294,
		"FriendShieldUserRsp":    524295,
		"FriendSearchRoleReq":    524296,
		"FriendSearchRoleRsp":    524297,
	}
)

func (x CmdTo) Enum() *CmdTo {
	p := new(CmdTo)
	*p = x
	return p
}

func (x CmdTo) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CmdTo) Descriptor() protoreflect.EnumDescriptor {
	return file_core_cmd_proto_enumTypes[1].Descriptor()
}

func (CmdTo) Type() protoreflect.EnumType {
	return &file_core_cmd_proto_enumTypes[1]
}

func (x CmdTo) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CmdTo.Descriptor instead.
func (CmdTo) EnumDescriptor() ([]byte, []int) {
	return file_core_cmd_proto_rawDescGZIP(), []int{1}
}

var File_core_cmd_proto protoreflect.FileDescriptor

const file_core_cmd_proto_rawDesc = "" +
	"\n" +
	"\x0ecore/cmd.proto\x12\x06g1.cmd*\xe1\x15\n" +
	"\x03CMD\x12\r\n" +
	"\t_CMD_ZERO\x10\x00\x12\x10\n" +
	"\vSC_KICK_OUT\x10\x81`\x12\x16\n" +
	"\x11SC_SYNC_USER_DATA\x10\x82`\x12\f\n" +
	"\aSC_CHAT\x10\x83`\x12\x1a\n" +
	"\x15SC_DATA_CHANGE_NOTIFY\x10\x84`\x12\x19\n" +
	"\x14SC_SYNC_USER_DATA_V2\x10\x86`\x12\x15\n" +
	"\x10SC_OBTAIN_NOTICE\x10\x87`\x12\x17\n" +
	"\x11CONN_KICK_OUT_REQ\x10\x80\xa0\x04\x12\x17\n" +
	"\x11CONN_KICK_OUT_RSP\x10\x81\xa0\x04\x12\x18\n" +
	"\x12CONN_BROADCAST_REQ\x10\x82\xa0\x04\x12\x18\n" +
	"\x12CONN_BROADCAST_RSP\x10\x83\xa0\x04\x12\x14\n" +
	"\x0eMAIN_LOGIN_REQ\x10\x80\x80\b\x12\x14\n" +
	"\x0eMAIN_LOGIN_RSP\x10\x81\x80\b\x12\x15\n" +
	"\x0fMAIN_LOGOUT_REQ\x10\x82\x80\b\x12\x15\n" +
	"\x0fMAIN_LOGOUT_RSP\x10\x83\x80\b\x12\x18\n" +
	"\x12MAIN_HEARTBEAT_REQ\x10\x84\x80\b\x12\x18\n" +
	"\x12MAIN_HEARTBEAT_RSP\x10\x85\x80\b\x12\x17\n" +
	"\x11MAIN_ITEM_USE_REQ\x10\x86\x80\b\x12\x17\n" +
	"\x11MAIN_ITEM_USE_RSP\x10\x87\x80\b\x12\x1a\n" +
	"\x14MAIN_CHANGE_NAME_REQ\x10\x88\x80\b\x12\x1a\n" +
	"\x14MAIN_CHANGE_NAME_RSP\x10\x89\x80\b\x12\x1a\n" +
	"\x14MAIN_CHANGE_ICON_REQ\x10\x8a\x80\b\x12\x1a\n" +
	"\x14MAIN_CHANGE_ICON_RSP\x10\x8b\x80\b\x12\x18\n" +
	"\x12MAIN_ITEM_SELL_REQ\x10\x8c\x80\b\x12\x18\n" +
	"\x12MAIN_ITEM_SELL_RSP\x10\x8d\x80\b\x12\x1d\n" +
	"\x17MAIN_ITEM_DECOMPOSE_REQ\x10\x8e\x80\b\x12\x1d\n" +
	"\x17MAIN_ITEM_DECOMPOSE_RSP\x10\x8f\x80\b\x12\x1d\n" +
	"\x17MAIN_BACKPACK_QUERY_REQ\x10\x90\x80\b\x12\x1d\n" +
	"\x17MAIN_BACKPACK_QUERY_RSP\x10\x91\x80\b\x12\x1d\n" +
	"\x17MAIN_ITEM_BATCH_ADD_REQ\x10\x92\x80\b\x12\x1d\n" +
	"\x17MAIN_ITEM_BATCH_ADD_RSP\x10\x93\x80\b\x12\x19\n" +
	"\x13GUIDE_COMPLETED_REQ\x10\xb4\x83\b\x12\x19\n" +
	"\x13GUIDE_COMPLETED_RSP\x10\xb5\x83\b\x12\x1b\n" +
	"\x15GUIDE_IN_PROGRESS_REQ\x10\xb6\x83\b\x12\x1b\n" +
	"\x15GUIDE_IN_PROGRESS_RSP\x10\xb7\x83\b\x12\x1f\n" +
	"\x19MAIN_MALL_BUY_PACKAGE_REQ\x10\xb0\x83\b\x12\x1f\n" +
	"\x19MAIN_MALL_BUY_PACKAGE_RSP\x10\xb1\x83\b\x12\x1c\n" +
	"\x16MAIN_MALL_RECHARGE_REQ\x10\xb2\x83\b\x12\x1c\n" +
	"\x16MAIN_MALL_RECHARGE_RSP\x10\xb3\x83\b\x12\x1a\n" +
	"\x14MAIN_TASK_FINISH_REQ\x10Ѓ\b\x12\x1a\n" +
	"\x14MAIN_TASK_FINISH_RSP\x10у\b\x12-\n" +
	"'MAIN_NOTIFY_ACTIVITY_TASK_SINGLE_UPDATE\x10\x81\xe0\b\x12\x1a\n" +
	"\x14MAIN_GM_GET_ROLE_REQ\x10\x80\xc0\n" +
	"\x12\x1a\n" +
	"\x14MAIN_GM_GET_ROLE_RSP\x10\x81\xc0\n" +
	"\x12\x1a\n" +
	"\x14MAIN_GM_SET_ROLE_REQ\x10\x82\xc0\n" +
	"\x12\x1a\n" +
	"\x14MAIN_GM_SET_ROLE_RSP\x10\x83\xc0\n" +
	"\x12\x1a\n" +
	"\x14MAIN_GM_ADD_ITEM_REQ\x10\x84\xc0\n" +
	"\x12\x1a\n" +
	"\x14MAIN_GM_ADD_ITEM_RSP\x10\x85\xc0\n" +
	"\x12\x1d\n" +
	"\x17INFO_GET_BRIEF_INFO_REQ\x10\x80\x80\f\x12\x1d\n" +
	"\x17INFO_GET_BRIEF_INFO_RSP\x10\x81\x80\f\x12\x1c\n" +
	"\x16INFO_GET_ICON_DESC_REQ\x10\x82\x80\f\x12\x1c\n" +
	"\x16INFO_GET_ICON_DESC_RSP\x10\x83\x80\f\x12#\n" +
	"\x1dINFO_INNER_SET_BRIEF_INFO_REQ\x10\x80\xa0\f\x12#\n" +
	"\x1dINFO_INNER_SET_BRIEF_INFO_RSP\x10\x81\xa0\f\x12\x1c\n" +
	"\x16MAIL_GET_MAIL_LIST_REQ\x10\x80\x80\x18\x12\x1c\n" +
	"\x16MAIL_GET_MAIL_LIST_RSP\x10\x81\x80\x18\x12\x18\n" +
	"\x12MAIL_READ_MAIL_REQ\x10\x82\x80\x18\x12\x18\n" +
	"\x12MAIL_READ_MAIL_RSP\x10\x83\x80\x18\x12\x17\n" +
	"\x11MAIL_DEL_MAIL_REQ\x10\x84\x80\x18\x12\x17\n" +
	"\x11MAIL_DEL_MAIL_RSP\x10\x85\x80\x18\x12\x1e\n" +
	"\x18MAIL_GET_MAIL_ATTACH_REQ\x10\x86\x80\x18\x12\x1e\n" +
	"\x18MAIL_GET_MAIL_ATTACH_RSP\x10\x87\x80\x18\x12\x1d\n" +
	"\x17MAIL_INNER_ADD_MAIL_REQ\x10\x80\xa0\x18\x12\x1d\n" +
	"\x17MAIL_INNER_ADD_MAIL_RSP\x10\x81\xa0\x18\x12\x13\n" +
	"\rCHAT_CHAT_REQ\x10\x80\x80\x1c\x12\x13\n" +
	"\rCHAT_CHAT_RSP\x10\x81\x80\x1c\x12\x1c\n" +
	"\x16CHAT_GET_CHAT_INFO_REQ\x10\x82\x80\x1c\x12\x1c\n" +
	"\x16CHAT_GET_CHAT_INFO_RSP\x10\x83\x80\x1c\x12\x17\n" +
	"\x11CHAT_DEL_CHAT_REQ\x10\x84\x80\x1c\x12\x17\n" +
	"\x11CHAT_DEL_CHAT_RSP\x10\x85\x80\x1c\x12 \n" +
	"\x1aFRIEND_GET_FRIEND_INFO_REQ\x10\x80\x80 \x12 \n" +
	"\x1aFRIEND_GET_FRIEND_INFO_RSP\x10\x81\x80 \x12\x1b\n" +
	"\x15FRIEND_ADD_FRIEND_REQ\x10\x82\x80 \x12\x1b\n" +
	"\x15FRIEND_ADD_FRIEND_RSP\x10\x83\x80 \x12\x1f\n" +
	"\x19FRIEND_CONFIRM_FRIEND_REQ\x10\x84\x80 \x12\x1f\n" +
	"\x19FRIEND_CONFIRM_FRIEND_RSP\x10\x85\x80 \x12\x1c\n" +
	"\x16FRIEND_SHIELD_USER_REQ\x10\x86\x80 \x12\x1c\n" +
	"\x16FRIEND_SHIELD_USER_RSP\x10\x87\x80 \x12\x1c\n" +
	"\x16FRIEND_SEARCH_ROLE_REQ\x10\x88\x80 \x12\x1c\n" +
	"\x16FRIEND_SEARCH_ROLE_RSP\x10\x89\x80 \x12!\n" +
	"\x1bFRIEND_INNER_ADD_FRIEND_REQ\x10\x80\xa0 \x12!\n" +
	"\x1bFRIEND_INNER_ADD_FRIEND_RSP\x10\x81\xa0 \x12%\n" +
	"\x1fFRIEND_INNER_CONFIRM_FRIEND_REQ\x10\x82\xa0 \x12%\n" +
	"\x1fFRIEND_INNER_CONFIRM_FRIEND_RSP\x10\x83\xa0 \x12&\n" +
	" MYSQL_INNER_UPDATE_ROLE_INFO_REQ\x10\x80\xa0\x10\x12&\n" +
	" MYSQL_INNER_UPDATE_ROLE_INFO_RSP\x10\x81\xa0\x10\x12!\n" +
	"\x1bMYSQL_INNER_SEARCH_ROLE_REQ\x10\x82\xa0\x10\x12!\n" +
	"\x1bMYSQL_INNER_SEARCH_ROLE_RSP\x10\x83\xa0\x10\x12&\n" +
	" MYSQL_INNER_SEARCH_GIFT_CODE_REQ\x10\x84\xa0\x10\x12&\n" +
	" MYSQL_INNER_SEARCH_GIFT_CODE_RSP\x10\x85\xa0\x10\x12$\n" +
	"\x1eMYSQL_INNER_SAVE_ROLE_DATA_REQ\x10\x8e\xa0\x10\x12$\n" +
	"\x1eMYSQL_INNER_SAVE_ROLE_DATA_RSP\x10\x8f\xa0\x10\x12$\n" +
	"\x1eMYSQL_INNER_LOAD_ROLE_DATA_REQ\x10\x90\xa0\x10\x12$\n" +
	"\x1eMYSQL_INNER_LOAD_ROLE_DATA_RSP\x10\x91\xa0\x10*\xee\t\n" +
	"\x05CmdTo\x12\t\n" +
	"\x05_ZERO\x10\x00\x12\x0e\n" +
	"\tScKickOut\x10\x81`\x12\x13\n" +
	"\x0eScSyncUserData\x10\x82`\x12\x15\n" +
	"\x10ScSyncUserDataV2\x10\x86`\x12\v\n" +
	"\x06ScChat\x10\x83`\x12\x17\n" +
	"\x12ScDataChangeNotify\x10\x84`\x12\x14\n" +
	"\x0eConnKickOutReq\x10\x80\xa0\x04\x12\x14\n" +
	"\x0eConnKickOutRsp\x10\x81\xa0\x04\x12\x16\n" +
	"\x10ConnBroadcastReq\x10\x82\xa0\x04\x12\x16\n" +
	"\x10ConnBroadcastRsp\x10\x83\xa0\x04\x12\x0e\n" +
	"\bLoginReq\x10\x80\x80\b\x12\x0e\n" +
	"\bLoginRsp\x10\x81\x80\b\x12\x0f\n" +
	"\tLogoutReq\x10\x82\x80\b\x12\x0f\n" +
	"\tLogoutRsp\x10\x83\x80\b\x12\x12\n" +
	"\fHeartBeatReq\x10\x84\x80\b\x12\x12\n" +
	"\fHeartBeatRsp\x10\x85\x80\b\x12\x10\n" +
	"\n" +
	"ItemUseReq\x10\x86\x80\b\x12\x10\n" +
	"\n" +
	"ItemUseRsp\x10\x87\x80\b\x12\x13\n" +
	"\rChangeNameReq\x10\x88\x80\b\x12\x13\n" +
	"\rChangeNameRsp\x10\x89\x80\b\x12\x13\n" +
	"\rChangeIconReq\x10\x8a\x80\b\x12\x13\n" +
	"\rChangeIconRsp\x10\x8b\x80\b\x12\x17\n" +
	"\x11GuideCompletedReq\x10\xb4\x83\b\x12\x17\n" +
	"\x11GuideCompletedRsp\x10\xb5\x83\b\x12\x18\n" +
	"\x12GuideInProgressReq\x10\xb6\x83\b\x12\x18\n" +
	"\x12GuideInProgressRsp\x10\xb7\x83\b\x12\x17\n" +
	"\x11MallBuyPackageReq\x10\xb0\x83\b\x12\x17\n" +
	"\x11MallBuyPackageRsp\x10\xb1\x83\b\x12\x15\n" +
	"\x0fMallRechargeReq\x10\xb2\x83\b\x12\x15\n" +
	"\x0fMallRechargeRsp\x10\xb3\x83\b\x12\x17\n" +
	"\x11MainTaskFinishReq\x10Ѓ\b\x12\x17\n" +
	"\x11MainTaskFinishRsp\x10у\b\x12\x14\n" +
	"\x0eGetMailListReq\x10\x80\x80\x18\x12\x14\n" +
	"\x0eGetMailListRsp\x10\x81\x80\x18\x12\x11\n" +
	"\vReadMailReq\x10\x82\x80\x18\x12\x11\n" +
	"\vReadMailRsp\x10\x83\x80\x18\x12\x10\n" +
	"\n" +
	"DelMailReq\x10\x84\x80\x18\x12\x10\n" +
	"\n" +
	"DelMailRsp\x10\x85\x80\x18\x12\x16\n" +
	"\x10GetMailAttachReq\x10\x86\x80\x18\x12\x16\n" +
	"\x10GetMailAttachRsp\x10\x87\x80\x18\x12\x11\n" +
	"\vChatChatReq\x10\x80\x80\x1c\x12\x11\n" +
	"\vChatChatRsp\x10\x81\x80\x1c\x12\x18\n" +
	"\x12ChatGetChatInfoReq\x10\x82\x80\x1c\x12\x18\n" +
	"\x12ChatGetChatInfoRsp\x10\x83\x80\x1c\x12\x14\n" +
	"\x0eChatDelChatReq\x10\x84\x80\x1c\x12\x14\n" +
	"\x0eChatDelChatRsp\x10\x85\x80\x1c\x12\x1c\n" +
	"\x16FriendGetFriendInfoReq\x10\x80\x80 \x12\x1c\n" +
	"\x16FriendGetFriendInfoRsp\x10\x81\x80 \x12\x18\n" +
	"\x12FriendAddFriendReq\x10\x82\x80 \x12\x18\n" +
	"\x12FriendAddFriendRsp\x10\x83\x80 \x12\x1c\n" +
	"\x16FriendConfirmFriendReq\x10\x84\x80 \x12\x1c\n" +
	"\x16FriendConfirmFriendRsp\x10\x85\x80 \x12\x19\n" +
	"\x13FriendShieldUserReq\x10\x86\x80 \x12\x19\n" +
	"\x13FriendShieldUserRsp\x10\x87\x80 \x12\x19\n" +
	"\x13FriendSearchRoleReq\x10\x88\x80 \x12\x19\n" +
	"\x13FriendSearchRoleRsp\x10\x89\x80 B9Z7github.com/Iori372552686/g1_common/protocol;g1_protocolb\x06proto3"

var (
	file_core_cmd_proto_rawDescOnce sync.Once
	file_core_cmd_proto_rawDescData []byte
)

func file_core_cmd_proto_rawDescGZIP() []byte {
	file_core_cmd_proto_rawDescOnce.Do(func() {
		file_core_cmd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_cmd_proto_rawDesc), len(file_core_cmd_proto_rawDesc)))
	})
	return file_core_cmd_proto_rawDescData
}

var file_core_cmd_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_core_cmd_proto_goTypes = []any{
	(CMD)(0),   // 0: g1.cmd.CMD
	(CmdTo)(0), // 1: g1.cmd.CmdTo
}
var file_core_cmd_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_cmd_proto_init() }
func file_core_cmd_proto_init() {
	if File_core_cmd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_cmd_proto_rawDesc), len(file_core_cmd_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_cmd_proto_goTypes,
		DependencyIndexes: file_core_cmd_proto_depIdxs,
		EnumInfos:         file_core_cmd_proto_enumTypes,
	}.Build()
	File_core_cmd_proto = out.File
	file_core_cmd_proto_goTypes = nil
	file_core_cmd_proto_depIdxs = nil
}
