//
// 本代码由xlsx工具生成，请勿手动修改

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: config/consts.proto

package g1_protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConstsGlobalConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int32                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`       // 字段ID
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`    // 字段名称
	Value         int32                  `protobuf:"varint,3,opt,name=Value,proto3" json:"Value,omitempty"` // 值
	Desc          string                 `protobuf:"bytes,4,opt,name=desc,proto3" json:"desc,omitempty"`    // 描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConstsGlobalConfig) Reset() {
	*x = ConstsGlobalConfig{}
	mi := &file_config_consts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConstsGlobalConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConstsGlobalConfig) ProtoMessage() {}

func (x *ConstsGlobalConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_consts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConstsGlobalConfig.ProtoReflect.Descriptor instead.
func (*ConstsGlobalConfig) Descriptor() ([]byte, []int) {
	return file_config_consts_proto_rawDescGZIP(), []int{0}
}

func (x *ConstsGlobalConfig) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *ConstsGlobalConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConstsGlobalConfig) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ConstsGlobalConfig) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type ConstsGlobalConfigAry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ary           []*ConstsGlobalConfig  `protobuf:"bytes,1,rep,name=Ary,proto3" json:"Ary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConstsGlobalConfigAry) Reset() {
	*x = ConstsGlobalConfigAry{}
	mi := &file_config_consts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConstsGlobalConfigAry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConstsGlobalConfigAry) ProtoMessage() {}

func (x *ConstsGlobalConfigAry) ProtoReflect() protoreflect.Message {
	mi := &file_config_consts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConstsGlobalConfigAry.ProtoReflect.Descriptor instead.
func (*ConstsGlobalConfigAry) Descriptor() ([]byte, []int) {
	return file_config_consts_proto_rawDescGZIP(), []int{1}
}

func (x *ConstsGlobalConfigAry) GetAry() []*ConstsGlobalConfig {
	if x != nil {
		return x.Ary
	}
	return nil
}

var File_config_consts_proto protoreflect.FileDescriptor

const file_config_consts_proto_rawDesc = "" +
	"\n" +
	"\x13config/consts.proto\x12\vg1.protocol\"b\n" +
	"\x12ConstsGlobalConfig\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x05R\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x14\n" +
	"\x05Value\x18\x03 \x01(\x05R\x05Value\x12\x12\n" +
	"\x04desc\x18\x04 \x01(\tR\x04desc\"J\n" +
	"\x15ConstsGlobalConfigAry\x121\n" +
	"\x03Ary\x18\x01 \x03(\v2\x1f.g1.protocol.ConstsGlobalConfigR\x03AryB9Z7github.com/Iori372552686/g1_common/protocol;g1_protocolb\x06proto3"

var (
	file_config_consts_proto_rawDescOnce sync.Once
	file_config_consts_proto_rawDescData []byte
)

func file_config_consts_proto_rawDescGZIP() []byte {
	file_config_consts_proto_rawDescOnce.Do(func() {
		file_config_consts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_consts_proto_rawDesc), len(file_config_consts_proto_rawDesc)))
	})
	return file_config_consts_proto_rawDescData
}

var file_config_consts_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_config_consts_proto_goTypes = []any{
	(*ConstsGlobalConfig)(nil),    // 0: g1.protocol.ConstsGlobalConfig
	(*ConstsGlobalConfigAry)(nil), // 1: g1.protocol.ConstsGlobalConfigAry
}
var file_config_consts_proto_depIdxs = []int32{
	0, // 0: g1.protocol.ConstsGlobalConfigAry.Ary:type_name -> g1.protocol.ConstsGlobalConfig
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_config_consts_proto_init() }
func file_config_consts_proto_init() {
	if File_config_consts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_consts_proto_rawDesc), len(file_config_consts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_consts_proto_goTypes,
		DependencyIndexes: file_config_consts_proto_depIdxs,
		MessageInfos:      file_config_consts_proto_msgTypes,
	}.Build()
	File_config_consts_proto = out.File
	file_config_consts_proto_goTypes = nil
	file_config_consts_proto_depIdxs = nil
}
