// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: core/database.proto

package g1_protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 角色信息
type MysqlRoleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty" gorm:"column:uid;type:bigint;primaryKey;comment:玩家uid"`                     // @inject_tag: gorm:"column:uid;type:bigint;primaryKey;comment:玩家uid"
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty" gorm:"column:name;type:varchar(25);index:IDX_role_info_name;comment:玩家名称"` // @inject_tag: gorm:"column:name;type:varchar(25);index:IDX_role_info_name;comment:玩家名称"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MysqlRoleInfo) Reset() {
	*x = MysqlRoleInfo{}
	mi := &file_core_database_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MysqlRoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MysqlRoleInfo) ProtoMessage() {}

func (x *MysqlRoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_database_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MysqlRoleInfo.ProtoReflect.Descriptor instead.
func (*MysqlRoleInfo) Descriptor() ([]byte, []int) {
	return file_core_database_proto_rawDescGZIP(), []int{0}
}

func (x *MysqlRoleInfo) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *MysqlRoleInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 角色全量数据快照（L3 持久层）：data 为 RoleInfo 整包 proto 序列化。
// update_time 用服务器时钟（datetime.NowMs），禁用带时区偏移的 Role.Now()，
// 与 SaveRoom/SaveGame 同构，作陈旧写守卫（repository.ErrStaleUpdate）。
type MysqlRoleData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty" gorm:"column:uid;type:bigint;primaryKey;comment:玩家uid"`                                      // @inject_tag: gorm:"column:uid;type:bigint;primaryKey;comment:玩家uid"
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty" gorm:"column:data;type:longblob;comment:RoleInfo整包序列化"`                                     // @inject_tag: gorm:"column:data;type:longblob;comment:RoleInfo整包序列化"
	UpdateTime    int64                  `protobuf:"varint,3,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty" gorm:"column:update_time;type:bigint;comment:更新时间(服务器时钟ms)"` // @inject_tag: gorm:"column:update_time;type:bigint;comment:更新时间(服务器时钟ms)"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MysqlRoleData) Reset() {
	*x = MysqlRoleData{}
	mi := &file_core_database_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MysqlRoleData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MysqlRoleData) ProtoMessage() {}

func (x *MysqlRoleData) ProtoReflect() protoreflect.Message {
	mi := &file_core_database_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MysqlRoleData.ProtoReflect.Descriptor instead.
func (*MysqlRoleData) Descriptor() ([]byte, []int) {
	return file_core_database_proto_rawDescGZIP(), []int{1}
}

func (x *MysqlRoleData) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *MysqlRoleData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MysqlRoleData) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

var File_core_database_proto protoreflect.FileDescriptor

const file_core_database_proto_rawDesc = "" +
	"\n" +
	"\x13core/database.proto\x12\vg1.protocol\"5\n" +
	"\rMysqlRoleInfo\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"V\n" +
	"\rMysqlRoleData\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1f\n" +
	"\vupdate_time\x18\x03 \x01(\x03R\n" +
	"updateTimeB9Z7github.com/Iori372552686/g1_common/protocol;g1_protocolb\x06proto3"

var (
	file_core_database_proto_rawDescOnce sync.Once
	file_core_database_proto_rawDescData []byte
)

func file_core_database_proto_rawDescGZIP() []byte {
	file_core_database_proto_rawDescOnce.Do(func() {
		file_core_database_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_database_proto_rawDesc), len(file_core_database_proto_rawDesc)))
	})
	return file_core_database_proto_rawDescData
}

var file_core_database_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_core_database_proto_goTypes = []any{
	(*MysqlRoleInfo)(nil), // 0: g1.protocol.MysqlRoleInfo
	(*MysqlRoleData)(nil), // 1: g1.protocol.MysqlRoleData
}
var file_core_database_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_database_proto_init() }
func file_core_database_proto_init() {
	if File_core_database_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_database_proto_rawDesc), len(file_core_database_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_database_proto_goTypes,
		DependencyIndexes: file_core_database_proto_depIdxs,
		MessageInfos:      file_core_database_proto_msgTypes,
	}.Build()
	File_core_database_proto = out.File
	file_core_database_proto_goTypes = nil
	file_core_database_proto_depIdxs = nil
}
