// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: storage/db.proto

package g1_protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 游戏房间数据db
// @db:string|Global|DBTexasRoomData:%s,RoomId|#multi
type DBTexasRoomData struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RoomId            uint64                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Base              *RoomBaseInfo          `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	LookerMap         map[uint64]uint32      `protobuf:"bytes,3,rep,name=looker_map,json=lookerMap,proto3" json:"looker_map,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Table             *TableTexasGameData    `protobuf:"bytes,4,opt,name=table,proto3" json:"table,omitempty"`
	CurState          GameState              `protobuf:"varint,5,opt,name=cur_state,json=curState,proto3,enum=g1.protocol.GameState" json:"cur_state,omitempty"`
	TotalBuyinChips   int64                  `protobuf:"varint,6,opt,name=total_buyin_chips,json=totalBuyinChips,proto3" json:"total_buyin_chips,omitempty"`       // 总买入筹码
	TotalServiceChips int64                  `protobuf:"varint,7,opt,name=total_service_chips,json=totalServiceChips,proto3" json:"total_service_chips,omitempty"` // 总服务费
	TotalRuningWater  int64                  `protobuf:"varint,8,opt,name=total_runing_water,json=totalRuningWater,proto3" json:"total_runing_water,omitempty"`    // 总流水
	TotalJoinCount    int64                  `protobuf:"varint,9,opt,name=total_join_count,json=totalJoinCount,proto3" json:"total_join_count,omitempty"`          // 参与游戏玩家列表
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DBTexasRoomData) Reset() {
	*x = DBTexasRoomData{}
	mi := &file_storage_db_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBTexasRoomData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBTexasRoomData) ProtoMessage() {}

func (x *DBTexasRoomData) ProtoReflect() protoreflect.Message {
	mi := &file_storage_db_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBTexasRoomData.ProtoReflect.Descriptor instead.
func (*DBTexasRoomData) Descriptor() ([]byte, []int) {
	return file_storage_db_proto_rawDescGZIP(), []int{0}
}

func (x *DBTexasRoomData) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *DBTexasRoomData) GetBase() *RoomBaseInfo {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *DBTexasRoomData) GetLookerMap() map[uint64]uint32 {
	if x != nil {
		return x.LookerMap
	}
	return nil
}

func (x *DBTexasRoomData) GetTable() *TableTexasGameData {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *DBTexasRoomData) GetCurState() GameState {
	if x != nil {
		return x.CurState
	}
	return GameState_STATE_INIT
}

func (x *DBTexasRoomData) GetTotalBuyinChips() int64 {
	if x != nil {
		return x.TotalBuyinChips
	}
	return 0
}

func (x *DBTexasRoomData) GetTotalServiceChips() int64 {
	if x != nil {
		return x.TotalServiceChips
	}
	return 0
}

func (x *DBTexasRoomData) GetTotalRuningWater() int64 {
	if x != nil {
		return x.TotalRuningWater
	}
	return 0
}

func (x *DBTexasRoomData) GetTotalJoinCount() int64 {
	if x != nil {
		return x.TotalJoinCount
	}
	return 0
}

// 游戏大厅房间信息数据db
// @db:string|Global|DBTexasRoomCenterInfo:%s,RoomId|#multi
type DBTexasRoomCenterInfo struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Index         uint64                   `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`                                                                                                 // rid index
	Stage         RoomStage                `protobuf:"varint,2,opt,name=stage,proto3,enum=g1.protocol.RoomStage" json:"stage,omitempty"`                                                                      // RoomStage
	RoomsMap      map[uint64]*RoomShowInfo `protobuf:"bytes,3,rep,name=rooms_map,json=roomsMap,proto3" json:"rooms_map,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // key:房间id, value: 房间展示信息
	RoomCount     uint32                   `protobuf:"varint,4,opt,name=room_count,json=roomCount,proto3" json:"room_count,omitempty"`                                                                        // 房间数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DBTexasRoomCenterInfo) Reset() {
	*x = DBTexasRoomCenterInfo{}
	mi := &file_storage_db_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DBTexasRoomCenterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBTexasRoomCenterInfo) ProtoMessage() {}

func (x *DBTexasRoomCenterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_storage_db_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBTexasRoomCenterInfo.ProtoReflect.Descriptor instead.
func (*DBTexasRoomCenterInfo) Descriptor() ([]byte, []int) {
	return file_storage_db_proto_rawDescGZIP(), []int{1}
}

func (x *DBTexasRoomCenterInfo) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *DBTexasRoomCenterInfo) GetStage() RoomStage {
	if x != nil {
		return x.Stage
	}
	return RoomStage_Free
}

func (x *DBTexasRoomCenterInfo) GetRoomsMap() map[uint64]*RoomShowInfo {
	if x != nil {
		return x.RoomsMap
	}
	return nil
}

func (x *DBTexasRoomCenterInfo) GetRoomCount() uint32 {
	if x != nil {
		return x.RoomCount
	}
	return 0
}

var File_storage_db_proto protoreflect.FileDescriptor

const file_storage_db_proto_rawDesc = "" +
	"\n" +
	"\x10storage/db.proto\x12\vg1.protocol\x1a\x0fcore/room.proto\x1a\x11core/struct.proto\x1a\x14core/game_enum.proto\"\x83\x04\n" +
	"\x0fDBTexasRoomData\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x04R\x06roomId\x12-\n" +
	"\x04base\x18\x02 \x01(\v2\x19.g1.protocol.RoomBaseInfoR\x04base\x12J\n" +
	"\n" +
	"looker_map\x18\x03 \x03(\v2+.g1.protocol.DBTexasRoomData.LookerMapEntryR\tlookerMap\x125\n" +
	"\x05table\x18\x04 \x01(\v2\x1f.g1.protocol.TableTexasGameDataR\x05table\x123\n" +
	"\tcur_state\x18\x05 \x01(\x0e2\x16.g1.protocol.GameStateR\bcurState\x12*\n" +
	"\x11total_buyin_chips\x18\x06 \x01(\x03R\x0ftotalBuyinChips\x12.\n" +
	"\x13total_service_chips\x18\a \x01(\x03R\x11totalServiceChips\x12,\n" +
	"\x12total_runing_water\x18\b \x01(\x03R\x10totalRuningWater\x12(\n" +
	"\x10total_join_count\x18\t \x01(\x03R\x0etotalJoinCount\x1a<\n" +
	"\x0eLookerMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"\xa1\x02\n" +
	"\x15DBTexasRoomCenterInfo\x12\x14\n" +
	"\x05Index\x18\x01 \x01(\x04R\x05Index\x12,\n" +
	"\x05stage\x18\x02 \x01(\x0e2\x16.g1.protocol.RoomStageR\x05stage\x12M\n" +
	"\trooms_map\x18\x03 \x03(\v20.g1.protocol.DBTexasRoomCenterInfo.RoomsMapEntryR\broomsMap\x12\x1d\n" +
	"\n" +
	"room_count\x18\x04 \x01(\rR\troomCount\x1aV\n" +
	"\rRoomsMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.g1.protocol.RoomShowInfoR\x05value:\x028\x01B9Z7github.com/Iori372552686/g1_common/protocol;g1_protocolb\x06proto3"

var (
	file_storage_db_proto_rawDescOnce sync.Once
	file_storage_db_proto_rawDescData []byte
)

func file_storage_db_proto_rawDescGZIP() []byte {
	file_storage_db_proto_rawDescOnce.Do(func() {
		file_storage_db_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_db_proto_rawDesc), len(file_storage_db_proto_rawDesc)))
	})
	return file_storage_db_proto_rawDescData
}

var file_storage_db_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_storage_db_proto_goTypes = []any{
	(*DBTexasRoomData)(nil),       // 0: g1.protocol.DBTexasRoomData
	(*DBTexasRoomCenterInfo)(nil), // 1: g1.protocol.DBTexasRoomCenterInfo
	nil,                           // 2: g1.protocol.DBTexasRoomData.LookerMapEntry
	nil,                           // 3: g1.protocol.DBTexasRoomCenterInfo.RoomsMapEntry
	(*RoomBaseInfo)(nil),          // 4: g1.protocol.RoomBaseInfo
	(*TableTexasGameData)(nil),    // 5: g1.protocol.TableTexasGameData
	(GameState)(0),                // 6: g1.protocol.GameState
	(RoomStage)(0),                // 7: g1.protocol.RoomStage
	(*RoomShowInfo)(nil),          // 8: g1.protocol.RoomShowInfo
}
var file_storage_db_proto_depIdxs = []int32{
	4, // 0: g1.protocol.DBTexasRoomData.base:type_name -> g1.protocol.RoomBaseInfo
	2, // 1: g1.protocol.DBTexasRoomData.looker_map:type_name -> g1.protocol.DBTexasRoomData.LookerMapEntry
	5, // 2: g1.protocol.DBTexasRoomData.table:type_name -> g1.protocol.TableTexasGameData
	6, // 3: g1.protocol.DBTexasRoomData.cur_state:type_name -> g1.protocol.GameState
	7, // 4: g1.protocol.DBTexasRoomCenterInfo.stage:type_name -> g1.protocol.RoomStage
	3, // 5: g1.protocol.DBTexasRoomCenterInfo.rooms_map:type_name -> g1.protocol.DBTexasRoomCenterInfo.RoomsMapEntry
	8, // 6: g1.protocol.DBTexasRoomCenterInfo.RoomsMapEntry.value:type_name -> g1.protocol.RoomShowInfo
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_storage_db_proto_init() }
func file_storage_db_proto_init() {
	if File_storage_db_proto != nil {
		return
	}
	file_core_room_proto_init()
	file_core_struct_proto_init()
	file_core_game_enum_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_db_proto_rawDesc), len(file_storage_db_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_storage_db_proto_goTypes,
		DependencyIndexes: file_storage_db_proto_depIdxs,
		MessageInfos:      file_storage_db_proto_msgTypes,
	}.Build()
	File_storage_db_proto = out.File
	file_storage_db_proto_goTypes = nil
	file_storage_db_proto_depIdxs = nil
}
