//
// 本代码由xlsx工具生成，请勿手动修改

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: config/drop.proto

package g1_protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DropGroupConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groupid       int32                  `protobuf:"varint,1,opt,name=Groupid,proto3" json:"Groupid,omitempty"`                                                                                    // 掉落组Id
	Subid         int32                  `protobuf:"varint,2,opt,name=Subid,proto3" json:"Subid,omitempty"`                                                                                        // 子序号
	DropGroupName string                 `protobuf:"bytes,3,opt,name=DropGroupName,proto3" json:"DropGroupName,omitempty"`                                                                         // 掉落组名
	DropWay       int32                  `protobuf:"varint,4,opt,name=DropWay,proto3" json:"DropWay,omitempty"`                                                                                    // 选择方式
	DropRateMap   map[int32]int32        `protobuf:"bytes,5,rep,name=DropRateMap,proto3" json:"DropRateMap,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 掉落概率表
	DropType      int32                  `protobuf:"varint,6,opt,name=DropType,proto3" json:"DropType,omitempty"`                                                                                  // 产出控制
	DropCount     int32                  `protobuf:"varint,7,opt,name=DropCount,proto3" json:"DropCount,omitempty"`                                                                                // 执行次数
	Type          int32                  `protobuf:"varint,8,opt,name=Type,proto3" json:"Type,omitempty"`                                                                                          // 组类型
	IsBan         int32                  `protobuf:"varint,9,opt,name=IsBan,proto3" json:"IsBan,omitempty"`                                                                                        // 是否禁用
	Desc          string                 `protobuf:"bytes,10,opt,name=Desc,proto3" json:"Desc,omitempty"`                                                                                          // 描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropGroupConfig) Reset() {
	*x = DropGroupConfig{}
	mi := &file_config_drop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropGroupConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropGroupConfig) ProtoMessage() {}

func (x *DropGroupConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_drop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropGroupConfig.ProtoReflect.Descriptor instead.
func (*DropGroupConfig) Descriptor() ([]byte, []int) {
	return file_config_drop_proto_rawDescGZIP(), []int{0}
}

func (x *DropGroupConfig) GetGroupid() int32 {
	if x != nil {
		return x.Groupid
	}
	return 0
}

func (x *DropGroupConfig) GetSubid() int32 {
	if x != nil {
		return x.Subid
	}
	return 0
}

func (x *DropGroupConfig) GetDropGroupName() string {
	if x != nil {
		return x.DropGroupName
	}
	return ""
}

func (x *DropGroupConfig) GetDropWay() int32 {
	if x != nil {
		return x.DropWay
	}
	return 0
}

func (x *DropGroupConfig) GetDropRateMap() map[int32]int32 {
	if x != nil {
		return x.DropRateMap
	}
	return nil
}

func (x *DropGroupConfig) GetDropType() int32 {
	if x != nil {
		return x.DropType
	}
	return 0
}

func (x *DropGroupConfig) GetDropCount() int32 {
	if x != nil {
		return x.DropCount
	}
	return 0
}

func (x *DropGroupConfig) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *DropGroupConfig) GetIsBan() int32 {
	if x != nil {
		return x.IsBan
	}
	return 0
}

func (x *DropGroupConfig) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type DropGroupConfigAry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ary           []*DropGroupConfig     `protobuf:"bytes,1,rep,name=Ary,proto3" json:"Ary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropGroupConfigAry) Reset() {
	*x = DropGroupConfigAry{}
	mi := &file_config_drop_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropGroupConfigAry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropGroupConfigAry) ProtoMessage() {}

func (x *DropGroupConfigAry) ProtoReflect() protoreflect.Message {
	mi := &file_config_drop_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropGroupConfigAry.ProtoReflect.Descriptor instead.
func (*DropGroupConfigAry) Descriptor() ([]byte, []int) {
	return file_config_drop_proto_rawDescGZIP(), []int{1}
}

func (x *DropGroupConfigAry) GetAry() []*DropGroupConfig {
	if x != nil {
		return x.Ary
	}
	return nil
}

type DropItemConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DropItemId    int32                  `protobuf:"varint,1,opt,name=DropItemId,proto3" json:"DropItemId,omitempty"`   // 掉落物品Id
	DropId        int32                  `protobuf:"varint,2,opt,name=DropId,proto3" json:"DropId,omitempty"`           // 掉落Id
	ItemId        int32                  `protobuf:"varint,3,opt,name=ItemId,proto3" json:"ItemId,omitempty"`           // 物品Id
	ItemName      string                 `protobuf:"bytes,4,opt,name=ItemName,proto3" json:"ItemName,omitempty"`        // 物品名
	Count         int64                  `protobuf:"varint,5,opt,name=Count,proto3" json:"Count,omitempty"`             // 数量
	DropWay       int32                  `protobuf:"varint,6,opt,name=DropWay,proto3" json:"DropWay,omitempty"`         // 掉落方式
	Probability   int32                  `protobuf:"varint,7,opt,name=Probability,proto3" json:"Probability,omitempty"` // 掉落概率
	IsRare        int32                  `protobuf:"varint,8,opt,name=IsRare,proto3" json:"IsRare,omitempty"`           // 是否罕见
	IsShow        int32                  `protobuf:"varint,9,opt,name=IsShow,proto3" json:"IsShow,omitempty"`           // 是否展示
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropItemConfig) Reset() {
	*x = DropItemConfig{}
	mi := &file_config_drop_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropItemConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropItemConfig) ProtoMessage() {}

func (x *DropItemConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_drop_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropItemConfig.ProtoReflect.Descriptor instead.
func (*DropItemConfig) Descriptor() ([]byte, []int) {
	return file_config_drop_proto_rawDescGZIP(), []int{2}
}

func (x *DropItemConfig) GetDropItemId() int32 {
	if x != nil {
		return x.DropItemId
	}
	return 0
}

func (x *DropItemConfig) GetDropId() int32 {
	if x != nil {
		return x.DropId
	}
	return 0
}

func (x *DropItemConfig) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *DropItemConfig) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *DropItemConfig) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *DropItemConfig) GetDropWay() int32 {
	if x != nil {
		return x.DropWay
	}
	return 0
}

func (x *DropItemConfig) GetProbability() int32 {
	if x != nil {
		return x.Probability
	}
	return 0
}

func (x *DropItemConfig) GetIsRare() int32 {
	if x != nil {
		return x.IsRare
	}
	return 0
}

func (x *DropItemConfig) GetIsShow() int32 {
	if x != nil {
		return x.IsShow
	}
	return 0
}

type DropItemConfigAry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ary           []*DropItemConfig      `protobuf:"bytes,1,rep,name=Ary,proto3" json:"Ary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropItemConfigAry) Reset() {
	*x = DropItemConfigAry{}
	mi := &file_config_drop_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropItemConfigAry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropItemConfigAry) ProtoMessage() {}

func (x *DropItemConfigAry) ProtoReflect() protoreflect.Message {
	mi := &file_config_drop_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropItemConfigAry.ProtoReflect.Descriptor instead.
func (*DropItemConfigAry) Descriptor() ([]byte, []int) {
	return file_config_drop_proto_rawDescGZIP(), []int{3}
}

func (x *DropItemConfigAry) GetAry() []*DropItemConfig {
	if x != nil {
		return x.Ary
	}
	return nil
}

var File_config_drop_proto protoreflect.FileDescriptor

const file_config_drop_proto_rawDesc = "" +
	"\n" +
	"\x11config/drop.proto\x12\vg1.protocol\"\x8a\x03\n" +
	"\x0fDropGroupConfig\x12\x18\n" +
	"\aGroupid\x18\x01 \x01(\x05R\aGroupid\x12\x14\n" +
	"\x05Subid\x18\x02 \x01(\x05R\x05Subid\x12$\n" +
	"\rDropGroupName\x18\x03 \x01(\tR\rDropGroupName\x12\x18\n" +
	"\aDropWay\x18\x04 \x01(\x05R\aDropWay\x12O\n" +
	"\vDropRateMap\x18\x05 \x03(\v2-.g1.protocol.DropGroupConfig.DropRateMapEntryR\vDropRateMap\x12\x1a\n" +
	"\bDropType\x18\x06 \x01(\x05R\bDropType\x12\x1c\n" +
	"\tDropCount\x18\a \x01(\x05R\tDropCount\x12\x12\n" +
	"\x04Type\x18\b \x01(\x05R\x04Type\x12\x14\n" +
	"\x05IsBan\x18\t \x01(\x05R\x05IsBan\x12\x12\n" +
	"\x04Desc\x18\n" +
	" \x01(\tR\x04Desc\x1a>\n" +
	"\x10DropRateMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"D\n" +
	"\x12DropGroupConfigAry\x12.\n" +
	"\x03Ary\x18\x01 \x03(\v2\x1c.g1.protocol.DropGroupConfigR\x03Ary\"\xfe\x01\n" +
	"\x0eDropItemConfig\x12\x1e\n" +
	"\n" +
	"DropItemId\x18\x01 \x01(\x05R\n" +
	"DropItemId\x12\x16\n" +
	"\x06DropId\x18\x02 \x01(\x05R\x06DropId\x12\x16\n" +
	"\x06ItemId\x18\x03 \x01(\x05R\x06ItemId\x12\x1a\n" +
	"\bItemName\x18\x04 \x01(\tR\bItemName\x12\x14\n" +
	"\x05Count\x18\x05 \x01(\x03R\x05Count\x12\x18\n" +
	"\aDropWay\x18\x06 \x01(\x05R\aDropWay\x12 \n" +
	"\vProbability\x18\a \x01(\x05R\vProbability\x12\x16\n" +
	"\x06IsRare\x18\b \x01(\x05R\x06IsRare\x12\x16\n" +
	"\x06IsShow\x18\t \x01(\x05R\x06IsShow\"B\n" +
	"\x11DropItemConfigAry\x12-\n" +
	"\x03Ary\x18\x01 \x03(\v2\x1b.g1.protocol.DropItemConfigR\x03AryB9Z7github.com/Iori372552686/g1_common/protocol;g1_protocolb\x06proto3"

var (
	file_config_drop_proto_rawDescOnce sync.Once
	file_config_drop_proto_rawDescData []byte
)

func file_config_drop_proto_rawDescGZIP() []byte {
	file_config_drop_proto_rawDescOnce.Do(func() {
		file_config_drop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_drop_proto_rawDesc), len(file_config_drop_proto_rawDesc)))
	})
	return file_config_drop_proto_rawDescData
}

var file_config_drop_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_config_drop_proto_goTypes = []any{
	(*DropGroupConfig)(nil),    // 0: g1.protocol.DropGroupConfig
	(*DropGroupConfigAry)(nil), // 1: g1.protocol.DropGroupConfigAry
	(*DropItemConfig)(nil),     // 2: g1.protocol.DropItemConfig
	(*DropItemConfigAry)(nil),  // 3: g1.protocol.DropItemConfigAry
	nil,                        // 4: g1.protocol.DropGroupConfig.DropRateMapEntry
}
var file_config_drop_proto_depIdxs = []int32{
	4, // 0: g1.protocol.DropGroupConfig.DropRateMap:type_name -> g1.protocol.DropGroupConfig.DropRateMapEntry
	0, // 1: g1.protocol.DropGroupConfigAry.Ary:type_name -> g1.protocol.DropGroupConfig
	2, // 2: g1.protocol.DropItemConfigAry.Ary:type_name -> g1.protocol.DropItemConfig
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_config_drop_proto_init() }
func file_config_drop_proto_init() {
	if File_config_drop_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_drop_proto_rawDesc), len(file_config_drop_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_drop_proto_goTypes,
		DependencyIndexes: file_config_drop_proto_depIdxs,
		MessageInfos:      file_config_drop_proto_msgTypes,
	}.Build()
	File_config_drop_proto = out.File
	file_config_drop_proto_goTypes = nil
	file_config_drop_proto_depIdxs = nil
}
