//
// 本代码由xlsx工具生成，请勿手动修改

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: config/enum.proto

package g1_protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PropertyType int32

const (
	PropertyType_PropertyType_Empty   PropertyType = 0 // 道具类型-空
	PropertyType_PropertyType_Coin    PropertyType = 1 // 道具类型-金币
	PropertyType_PropertyType_Diamond PropertyType = 2 // 道具类型-钻石
)

// Enum value maps for PropertyType.
var (
	PropertyType_name = map[int32]string{
		0: "PropertyType_Empty",
		1: "PropertyType_Coin",
		2: "PropertyType_Diamond",
	}
	PropertyType_value = map[string]int32{
		"PropertyType_Empty":   0,
		"PropertyType_Coin":    1,
		"PropertyType_Diamond": 2,
	}
)

func (x PropertyType) Enum() *PropertyType {
	p := new(PropertyType)
	*p = x
	return p
}

func (x PropertyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PropertyType) Descriptor() protoreflect.EnumDescriptor {
	return file_config_enum_proto_enumTypes[0].Descriptor()
}

func (PropertyType) Type() protoreflect.EnumType {
	return &file_config_enum_proto_enumTypes[0]
}

func (x PropertyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PropertyType.Descriptor instead.
func (PropertyType) EnumDescriptor() ([]byte, []int) {
	return file_config_enum_proto_rawDescGZIP(), []int{0}
}

type QualityType int32

const (
	QualityType_QualityType_None  QualityType = 0 // 品质类型-空
	QualityType_QualityType_White QualityType = 1 // 品质类型-白
	QualityType_QualityType_Blue  QualityType = 2 // 品质类型-蓝
)

// Enum value maps for QualityType.
var (
	QualityType_name = map[int32]string{
		0: "QualityType_None",
		1: "QualityType_White",
		2: "QualityType_Blue",
	}
	QualityType_value = map[string]int32{
		"QualityType_None":  0,
		"QualityType_White": 1,
		"QualityType_Blue":  2,
	}
)

func (x QualityType) Enum() *QualityType {
	p := new(QualityType)
	*p = x
	return p
}

func (x QualityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QualityType) Descriptor() protoreflect.EnumDescriptor {
	return file_config_enum_proto_enumTypes[1].Descriptor()
}

func (QualityType) Type() protoreflect.EnumType {
	return &file_config_enum_proto_enumTypes[1]
}

func (x QualityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QualityType.Descriptor instead.
func (QualityType) EnumDescriptor() ([]byte, []int) {
	return file_config_enum_proto_rawDescGZIP(), []int{1}
}

type TaskType int32

const (
	TaskType_TaskType_NONE TaskType = 0 // 任务类型-空
	TaskType_TaskType_MAIN TaskType = 1 // 任务类型-主线
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "TaskType_NONE",
		1: "TaskType_MAIN",
	}
	TaskType_value = map[string]int32{
		"TaskType_NONE": 0,
		"TaskType_MAIN": 1,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_config_enum_proto_enumTypes[2].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_config_enum_proto_enumTypes[2]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_config_enum_proto_rawDescGZIP(), []int{2}
}

var File_config_enum_proto protoreflect.FileDescriptor

const file_config_enum_proto_rawDesc = "" +
	"\n" +
	"\x11config/enum.proto\x12\vg1.protocol*W\n" +
	"\fPropertyType\x12\x16\n" +
	"\x12PropertyType_Empty\x10\x00\x12\x15\n" +
	"\x11PropertyType_Coin\x10\x01\x12\x18\n" +
	"\x14PropertyType_Diamond\x10\x02*P\n" +
	"\vQualityType\x12\x14\n" +
	"\x10QualityType_None\x10\x00\x12\x15\n" +
	"\x11QualityType_White\x10\x01\x12\x14\n" +
	"\x10QualityType_Blue\x10\x02*0\n" +
	"\bTaskType\x12\x11\n" +
	"\rTaskType_NONE\x10\x00\x12\x11\n" +
	"\rTaskType_MAIN\x10\x01B9Z7github.com/Iori372552686/g1_common/protocol;g1_protocolb\x06proto3"

var (
	file_config_enum_proto_rawDescOnce sync.Once
	file_config_enum_proto_rawDescData []byte
)

func file_config_enum_proto_rawDescGZIP() []byte {
	file_config_enum_proto_rawDescOnce.Do(func() {
		file_config_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_enum_proto_rawDesc), len(file_config_enum_proto_rawDesc)))
	})
	return file_config_enum_proto_rawDescData
}

var file_config_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_config_enum_proto_goTypes = []any{
	(PropertyType)(0), // 0: g1.protocol.PropertyType
	(QualityType)(0),  // 1: g1.protocol.QualityType
	(TaskType)(0),     // 2: g1.protocol.TaskType
}
var file_config_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_config_enum_proto_init() }
func file_config_enum_proto_init() {
	if File_config_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_enum_proto_rawDesc), len(file_config_enum_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_enum_proto_goTypes,
		DependencyIndexes: file_config_enum_proto_depIdxs,
		EnumInfos:         file_config_enum_proto_enumTypes,
	}.Build()
	File_config_enum_proto = out.File
	file_config_enum_proto_goTypes = nil
	file_config_enum_proto_depIdxs = nil
}
