// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: core/error_code.proto

package g1_protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	// 公共错误码，范围：[-99,-1]
	ErrorCode_ERR_SUCESS                 ErrorCode = 0   // 成功 ,新pb版本可能导致缺省nil
	ErrorCode_ERR_OK                     ErrorCode = 200 // 成功,兼容http状态码
	ErrorCode_ERR_FAIL                   ErrorCode = -1
	ErrorCode_ERR_TIMEOUT                ErrorCode = -2
	ErrorCode_ERR_MARSHAL                ErrorCode = -3
	ErrorCode_ERR_NOT_EXIST              ErrorCode = -4
	ErrorCode_ERR_DB                     ErrorCode = -5
	ErrorCode_ERR_CONF                   ErrorCode = -6
	ErrorCode_ERR_ARGV                   ErrorCode = -7
	ErrorCode_ERR_ZONE                   ErrorCode = -8
	ErrorCode_ERR_HAS_EXIST              ErrorCode = -9
	ErrorCode_ERR_GEN_ID                 ErrorCode = -10
	ErrorCode_ERR_INTERNAL               ErrorCode = -11
	ErrorCode_ERR_NOT_EXIST_GAME_ROOM    ErrorCode = -12    // 游戏房间不存在
	ErrorCode_ERR_NOT_EXIST_PLAYER       ErrorCode = -13    // 玩家不存在
	ErrorCode_ERR_NOT_EXIST_GAME_LOG     ErrorCode = -14    // 游戏日志不存在
	ErrorCode_ERR_NOT_ENOUGH_GAME_ROOM   ErrorCode = -15    //  游戏房间不足
	ErrorCode_ERR_UNAUTHENTICATED        ErrorCode = -16    // 身份凭据缺失、无效、过期或已吊销
	ErrorCode_ERR_UNIMPLEMENTED          ErrorCode = -17    // RPC 方法尚未实现
	ErrorCode_ERR_INSTANCE_NOT_AVAILABLE ErrorCode = -10001 // 副本未开放
	ErrorCode_ERR_ITEM_NOT_ENOUGH        ErrorCode = -10002 // 道具数量不足
	ErrorCode_ERR_ITEM_ADD_ERROR         ErrorCode = -10003 // 添加道具失败
	ErrorCode_ERR_ITEM_CARD_NOT_EXIST    ErrorCode = -10004 // 卡牌不存在
	ErrorCode_ERR_INSTANCE_NOT_PASS      ErrorCode = -10005 // 章节未通关
	ErrorCode_ERR_REWARD_ALREADY_GET     ErrorCode = -10006 // 奖励重复领取
	ErrorCode_ERR_SINEW_NOT_ENOUGH       ErrorCode = -10007 // 体力不足
	ErrorCode_ERR_GOLD_NOT_ENOUGH        ErrorCode = -10008 // 金币不足
	ErrorCode_ERR_DIAMOND_NOT_ENOUGH     ErrorCode = -10009 // 钻石不足
	ErrorCode_ERR_ACE_COIN_NOT_ENOUGH    ErrorCode = -10010 // ace币不足
	// 背包/道具系统
	ErrorCode_ERR_ITEM_OVER_LIMIT                 ErrorCode = -10011 // 道具超过拥有上限
	ErrorCode_ERR_ITEM_CAN_NOT_USE                ErrorCode = -10012 // 道具不可使用
	ErrorCode_ERR_ITEM_CAN_NOT_SELL               ErrorCode = -10013 // 道具不可出售
	ErrorCode_ERR_ITEM_CAN_NOT_DECOMPOSE          ErrorCode = -10014 // 道具不可分解
	ErrorCode_ERR_ICON_NOT_HAVE                   ErrorCode = -10020 // 头像未获得
	ErrorCode_ERR_FRAME_NOT_HAVE                  ErrorCode = -10021 // 相框未获得
	ErrorCode_ERR_IMAGE_NOT_HAVE                  ErrorCode = -10022 // 立绘未获得
	ErrorCode_ERR_INVALID_NAME                    ErrorCode = -10023 // 名字不合法
	ErrorCode_ERR_SENSITIVE_WORD                  ErrorCode = -10024 // 敏感词
	ErrorCode_ERR_DUPLICATE_NAME                  ErrorCode = -10025 // 名字已经存在
	ErrorCode_ERR_FRIEND_ALREADY_FRIEND           ErrorCode = -10050 // 对方已经是好友
	ErrorCode_ERR_FRIEND_NOT_EXIST                ErrorCode = -10051 // 好友不存在
	ErrorCode_ERR_FRIEND_MAX_INVITATION_NUM       ErrorCode = -10052
	ErrorCode_ERR_FRIEND_OTHER_MAX_INVITATION_NUM ErrorCode = -10053 // 对方好友申请已满
	ErrorCode_ERR_FRIEND_INVITATION_NOT_EXIST     ErrorCode = -10054
	ErrorCode_ERR_FRIEND_MAX_FRIEND_NUM           ErrorCode = -10055 // 好友数量满
	ErrorCode_ERR_FRIEND_OTHER_MAX_FRIEND_NUM     ErrorCode = -10056 // 对方好友数量满
	ErrorCode_ERR_FRIEND_SHIELD                   ErrorCode = -10057 // 玩家被屏蔽
	ErrorCode_ERR_FRIEND_MAX_SHIELD               ErrorCode = -10058 // 黑名单达到上限
	ErrorCode_ERR_MALL_OUT_OF_TIME                ErrorCode = -10130 // 商城商品已过期
	ErrorCode_ERR_MALL_DAILY_LIMIT                ErrorCode = -10131 // 商城商品每日购买限制
	ErrorCode_ERR_MALL_BUY_LIMIT                  ErrorCode = -10132 // 商城商品购买限制
	ErrorCode_ERR_MAIN_TASK_NOT_FINISH            ErrorCode = -10150 // 主线任务未完成
	ErrorCode_ERR_GUIDE_IS_EXIST                  ErrorCode = -10187 // 该引导已经存在
	ErrorCode_ERR_FUNCTION_NOT_OPEN               ErrorCode = -10188 // 功能未开放
	// 德州扑克错误码
	ErrorCode_ERR_TEXAS_FOLD_PARAMETERS         ErrorCode = -20000 // 弃牌参数错误
	ErrorCode_ERR_TEXAS_SEAT_OCCUPIED           ErrorCode = -20001 // 座位已经被占用
	ErrorCode_ERR_TEXAS_PLAYER_NOT_IN_GAME      ErrorCode = -20002 // 玩家不在游戏中
	ErrorCode_ERR_TEXAS_PLAYER_NOT_ACTIVE       ErrorCode = -20003 // 玩家不能操作
	ErrorCode_ERR_TEXAS_PLAYER_STATUS_INCORRECT ErrorCode = -20004 // 玩家状态不正确
	ErrorCode_ERR_TEXAS_PLAYER_IN_GAME          ErrorCode = -20005 // 玩家已经在游戏中
	ErrorCode_ERR_TEXAS_TABLE_FULL              ErrorCode = -20006 // 桌子数量已满
	ErrorCode_ERR_TEXAS_NOT_IN_TABLE            ErrorCode = -20007 // 玩家不在桌子中
	ErrorCode_ERR_TEXAS_STAND_UP_PARAMETERS     ErrorCode = -20008 // 站起参数错误
	ErrorCode_ERR_TEXAS_PLAYER_HAS_STAND_UP     ErrorCode = -20009 // 玩家已经站起
	ErrorCode_ERR_TEXAS_DO_BET_PARAMETERS       ErrorCode = -20010 // 下注参数错误
	ErrorCode_ERR_TEXAS_CHIPS_NOT_ENOUGH        ErrorCode = -20011 // 筹码不足
	ErrorCode_ERR_TEXAS_CALL_CHIPS_NOT_ENOUGH   ErrorCode = -20012 // 跟注筹码不足
	ErrorCode_ERR_TEXAS_RAISE_CHIPS_NOT_ENOUGH  ErrorCode = -20013 // 加注筹码不足
	ErrorCode_ERR_TEXAS_CONFIG_NOT_FOUND        ErrorCode = -20014 // 配置未找到
	ErrorCode_ERR_TEXAS_SEAT_NOT_FOUND          ErrorCode = -20015 // 座位未找到
	// 排行榜
	ErrorCode_ERR_RANK_TYPE_ERROR ErrorCode = -90000 // 排行榜类型错误
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:      "ERR_SUCESS",
		200:    "ERR_OK",
		-1:     "ERR_FAIL",
		-2:     "ERR_TIMEOUT",
		-3:     "ERR_MARSHAL",
		-4:     "ERR_NOT_EXIST",
		-5:     "ERR_DB",
		-6:     "ERR_CONF",
		-7:     "ERR_ARGV",
		-8:     "ERR_ZONE",
		-9:     "ERR_HAS_EXIST",
		-10:    "ERR_GEN_ID",
		-11:    "ERR_INTERNAL",
		-12:    "ERR_NOT_EXIST_GAME_ROOM",
		-13:    "ERR_NOT_EXIST_PLAYER",
		-14:    "ERR_NOT_EXIST_GAME_LOG",
		-15:    "ERR_NOT_ENOUGH_GAME_ROOM",
		-16:    "ERR_UNAUTHENTICATED",
		-17:    "ERR_UNIMPLEMENTED",
		-10001: "ERR_INSTANCE_NOT_AVAILABLE",
		-10002: "ERR_ITEM_NOT_ENOUGH",
		-10003: "ERR_ITEM_ADD_ERROR",
		-10004: "ERR_ITEM_CARD_NOT_EXIST",
		-10005: "ERR_INSTANCE_NOT_PASS",
		-10006: "ERR_REWARD_ALREADY_GET",
		-10007: "ERR_SINEW_NOT_ENOUGH",
		-10008: "ERR_GOLD_NOT_ENOUGH",
		-10009: "ERR_DIAMOND_NOT_ENOUGH",
		-10010: "ERR_ACE_COIN_NOT_ENOUGH",
		-10011: "ERR_ITEM_OVER_LIMIT",
		-10012: "ERR_ITEM_CAN_NOT_USE",
		-10013: "ERR_ITEM_CAN_NOT_SELL",
		-10014: "ERR_ITEM_CAN_NOT_DECOMPOSE",
		-10020: "ERR_ICON_NOT_HAVE",
		-10021: "ERR_FRAME_NOT_HAVE",
		-10022: "ERR_IMAGE_NOT_HAVE",
		-10023: "ERR_INVALID_NAME",
		-10024: "ERR_SENSITIVE_WORD",
		-10025: "ERR_DUPLICATE_NAME",
		-10050: "ERR_FRIEND_ALREADY_FRIEND",
		-10051: "ERR_FRIEND_NOT_EXIST",
		-10052: "ERR_FRIEND_MAX_INVITATION_NUM",
		-10053: "ERR_FRIEND_OTHER_MAX_INVITATION_NUM",
		-10054: "ERR_FRIEND_INVITATION_NOT_EXIST",
		-10055: "ERR_FRIEND_MAX_FRIEND_NUM",
		-10056: "ERR_FRIEND_OTHER_MAX_FRIEND_NUM",
		-10057: "ERR_FRIEND_SHIELD",
		-10058: "ERR_FRIEND_MAX_SHIELD",
		-10130: "ERR_MALL_OUT_OF_TIME",
		-10131: "ERR_MALL_DAILY_LIMIT",
		-10132: "ERR_MALL_BUY_LIMIT",
		-10150: "ERR_MAIN_TASK_NOT_FINISH",
		-10187: "ERR_GUIDE_IS_EXIST",
		-10188: "ERR_FUNCTION_NOT_OPEN",
		-20000: "ERR_TEXAS_FOLD_PARAMETERS",
		-20001: "ERR_TEXAS_SEAT_OCCUPIED",
		-20002: "ERR_TEXAS_PLAYER_NOT_IN_GAME",
		-20003: "ERR_TEXAS_PLAYER_NOT_ACTIVE",
		-20004: "ERR_TEXAS_PLAYER_STATUS_INCORRECT",
		-20005: "ERR_TEXAS_PLAYER_IN_GAME",
		-20006: "ERR_TEXAS_TABLE_FULL",
		-20007: "ERR_TEXAS_NOT_IN_TABLE",
		-20008: "ERR_TEXAS_STAND_UP_PARAMETERS",
		-20009: "ERR_TEXAS_PLAYER_HAS_STAND_UP",
		-20010: "ERR_TEXAS_DO_BET_PARAMETERS",
		-20011: "ERR_TEXAS_CHIPS_NOT_ENOUGH",
		-20012: "ERR_TEXAS_CALL_CHIPS_NOT_ENOUGH",
		-20013: "ERR_TEXAS_RAISE_CHIPS_NOT_ENOUGH",
		-20014: "ERR_TEXAS_CONFIG_NOT_FOUND",
		-20015: "ERR_TEXAS_SEAT_NOT_FOUND",
		-90000: "ERR_RANK_TYPE_ERROR",
	}
	ErrorCode_value = map[string]int32{
		"ERR_SUCESS":                          0,
		"ERR_OK":                              200,
		"ERR_FAIL":                            -1,
		"ERR_TIMEOUT":                         -2,
		"ERR_MARSHAL":                         -3,
		"ERR_NOT_EXIST":                       -4,
		"ERR_DB":                              -5,
		"ERR_CONF":                            -6,
		"ERR_ARGV":                            -7,
		"ERR_ZONE":                            -8,
		"ERR_HAS_EXIST":                       -9,
		"ERR_GEN_ID":                          -10,
		"ERR_INTERNAL":                        -11,
		"ERR_NOT_EXIST_GAME_ROOM":             -12,
		"ERR_NOT_EXIST_PLAYER":                -13,
		"ERR_NOT_EXIST_GAME_LOG":              -14,
		"ERR_NOT_ENOUGH_GAME_ROOM":            -15,
		"ERR_UNAUTHENTICATED":                 -16,
		"ERR_UNIMPLEMENTED":                   -17,
		"ERR_INSTANCE_NOT_AVAILABLE":          -10001,
		"ERR_ITEM_NOT_ENOUGH":                 -10002,
		"ERR_ITEM_ADD_ERROR":                  -10003,
		"ERR_ITEM_CARD_NOT_EXIST":             -10004,
		"ERR_INSTANCE_NOT_PASS":               -10005,
		"ERR_REWARD_ALREADY_GET":              -10006,
		"ERR_SINEW_NOT_ENOUGH":                -10007,
		"ERR_GOLD_NOT_ENOUGH":                 -10008,
		"ERR_DIAMOND_NOT_ENOUGH":              -10009,
		"ERR_ACE_COIN_NOT_ENOUGH":             -10010,
		"ERR_ITEM_OVER_LIMIT":                 -10011,
		"ERR_ITEM_CAN_NOT_USE":                -10012,
		"ERR_ITEM_CAN_NOT_SELL":               -10013,
		"ERR_ITEM_CAN_NOT_DECOMPOSE":          -10014,
		"ERR_ICON_NOT_HAVE":                   -10020,
		"ERR_FRAME_NOT_HAVE":                  -10021,
		"ERR_IMAGE_NOT_HAVE":                  -10022,
		"ERR_INVALID_NAME":                    -10023,
		"ERR_SENSITIVE_WORD":                  -10024,
		"ERR_DUPLICATE_NAME":                  -10025,
		"ERR_FRIEND_ALREADY_FRIEND":           -10050,
		"ERR_FRIEND_NOT_EXIST":                -10051,
		"ERR_FRIEND_MAX_INVITATION_NUM":       -10052,
		"ERR_FRIEND_OTHER_MAX_INVITATION_NUM": -10053,
		"ERR_FRIEND_INVITATION_NOT_EXIST":     -10054,
		"ERR_FRIEND_MAX_FRIEND_NUM":           -10055,
		"ERR_FRIEND_OTHER_MAX_FRIEND_NUM":     -10056,
		"ERR_FRIEND_SHIELD":                   -10057,
		"ERR_FRIEND_MAX_SHIELD":               -10058,
		"ERR_MALL_OUT_OF_TIME":                -10130,
		"ERR_MALL_DAILY_LIMIT":                -10131,
		"ERR_MALL_BUY_LIMIT":                  -10132,
		"ERR_MAIN_TASK_NOT_FINISH":            -10150,
		"ERR_GUIDE_IS_EXIST":                  -10187,
		"ERR_FUNCTION_NOT_OPEN":               -10188,
		"ERR_TEXAS_FOLD_PARAMETERS":           -20000,
		"ERR_TEXAS_SEAT_OCCUPIED":             -20001,
		"ERR_TEXAS_PLAYER_NOT_IN_GAME":        -20002,
		"ERR_TEXAS_PLAYER_NOT_ACTIVE":         -20003,
		"ERR_TEXAS_PLAYER_STATUS_INCORRECT":   -20004,
		"ERR_TEXAS_PLAYER_IN_GAME":            -20005,
		"ERR_TEXAS_TABLE_FULL":                -20006,
		"ERR_TEXAS_NOT_IN_TABLE":              -20007,
		"ERR_TEXAS_STAND_UP_PARAMETERS":       -20008,
		"ERR_TEXAS_PLAYER_HAS_STAND_UP":       -20009,
		"ERR_TEXAS_DO_BET_PARAMETERS":         -20010,
		"ERR_TEXAS_CHIPS_NOT_ENOUGH":          -20011,
		"ERR_TEXAS_CALL_CHIPS_NOT_ENOUGH":     -20012,
		"ERR_TEXAS_RAISE_CHIPS_NOT_ENOUGH":    -20013,
		"ERR_TEXAS_CONFIG_NOT_FOUND":          -20014,
		"ERR_TEXAS_SEAT_NOT_FOUND":            -20015,
		"ERR_RANK_TYPE_ERROR":                 -90000,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_core_error_code_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_core_error_code_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_core_error_code_proto_rawDescGZIP(), []int{0}
}

var File_core_error_code_proto protoreflect.FileDescriptor

const file_core_error_code_proto_rawDesc = "" +
	"\n" +
	"\x15core/error_code.proto\x12\vg1.protocol*\xd0\x13\n" +
	"\tErrorCode\x12\x0e\n" +
	"\n" +
	"ERR_SUCESS\x10\x00\x12\v\n" +
	"\x06ERR_OK\x10\xc8\x01\x12\x15\n" +
	"\bERR_FAIL\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x18\n" +
	"\vERR_TIMEOUT\x10\xfe\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x18\n" +
	"\vERR_MARSHAL\x10\xfd\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x1a\n" +
	"\rERR_NOT_EXIST\x10\xfc\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x13\n" +
	"\x06ERR_DB\x10\xfb\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x15\n" +
	"\bERR_CONF\x10\xfa\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x15\n" +
	"\bERR_ARGV\x10\xf9\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x15\n" +
	"\bERR_ZONE\x10\xf8\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x1a\n" +
	"\rERR_HAS_EXIST\x10\xf7\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x17\n" +
	"\n" +
	"ERR_GEN_ID\x10\xf6\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x19\n" +
	"\fERR_INTERNAL\x10\xf5\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12$\n" +
	"\x17ERR_NOT_EXIST_GAME_ROOM\x10\xf4\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12!\n" +
	"\x14ERR_NOT_EXIST_PLAYER\x10\xf3\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12#\n" +
	"\x16ERR_NOT_EXIST_GAME_LOG\x10\xf2\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12%\n" +
	"\x18ERR_NOT_ENOUGH_GAME_ROOM\x10\xf1\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12 \n" +
	"\x13ERR_UNAUTHENTICATED\x10\xf0\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x1e\n" +
	"\x11ERR_UNIMPLEMENTED\x10\xef\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12'\n" +
	"\x1aERR_INSTANCE_NOT_AVAILABLE\x10\xef\xb1\xff\xff\xff\xff\xff\xff\xff\x01\x12 \n" +
	"\x13ERR_ITEM_NOT_ENOUGH\x10\xee\xb1\xff\xff\xff\xff\xff\xff\xff\x01\x12\x1f\n" +
	"\x12ERR_ITEM_ADD_ERROR\x10\xed\xb1\xff\xff\xff\xff\xff\xff\xff\x01\x12$\n" +
	"\x17ERR_ITEM_CARD_NOT_EXIST\x10\xec\xb1\xff\xff\xff\xff\xff\xff\xff\x01\x12\"\n" +
	"\x15ERR_INSTANCE_NOT_PASS\x10\xeb\xb1\xff\xff\xff\xff\xff\xff\xff\x01\x12#\n" +
	"\x16ERR_REWARD_ALREADY_GET\x10\xea\xb1\xff\xff\xff\xff\xff\xff\xff\x01\x12!\n" +
	"\x14ERR_SINEW_NOT_ENOUGH\x10\xe9\xb1\xff\xff\xff\xff\xff\xff\xff\x01\x12 \n" +
	"\x13ERR_GOLD_NOT_ENOUGH\x10\xe8\xb1\xff\xff\xff\xff\xff\xff\xff\x01\x12#\n" +
	"\x16ERR_DIAMOND_NOT_ENOUGH\x10\xe7\xb1\xff\xff\xff\xff\xff\xff\xff\x01\x12$\n" +
	"\x17ERR_ACE_COIN_NOT_ENOUGH\x10\xe6\xb1\xff\xff\xff\xff\xff\xff\xff\x01\x12 \n" +
	"\x13ERR_ITEM_OVER_LIMIT\x10\xe5\xb1\xff\xff\xff\xff\xff\xff\xff\x01\x12!\n" +
	"\x14ERR_ITEM_CAN_NOT_USE\x10\xe4\xb1\xff\xff\xff\xff\xff\xff\xff\x01\x12\"\n" +
	"\x15ERR_ITEM_CAN_NOT_SELL\x10\xe3\xb1\xff\xff\xff\xff\xff\xff\xff\x01\x12'\n" +
	"\x1aERR_ITEM_CAN_NOT_DECOMPOSE\x10\xe2\xb1\xff\xff\xff\xff\xff\xff\xff\x01\x12\x1e\n" +
	"\x11ERR_ICON_NOT_HAVE\x10ܱ\xff\xff\xff\xff\xff\xff\xff\x01\x12\x1f\n" +
	"\x12ERR_FRAME_NOT_HAVE\x10۱\xff\xff\xff\xff\xff\xff\xff\x01\x12\x1f\n" +
	"\x12ERR_IMAGE_NOT_HAVE\x10ڱ\xff\xff\xff\xff\xff\xff\xff\x01\x12\x1d\n" +
	"\x10ERR_INVALID_NAME\x10ٱ\xff\xff\xff\xff\xff\xff\xff\x01\x12\x1f\n" +
	"\x12ERR_SENSITIVE_WORD\x10ر\xff\xff\xff\xff\xff\xff\xff\x01\x12\x1f\n" +
	"\x12ERR_DUPLICATE_NAME\x10ױ\xff\xff\xff\xff\xff\xff\xff\x01\x12&\n" +
	"\x19ERR_FRIEND_ALREADY_FRIEND\x10\xbe\xb1\xff\xff\xff\xff\xff\xff\xff\x01\x12!\n" +
	"\x14ERR_FRIEND_NOT_EXIST\x10\xbd\xb1\xff\xff\xff\xff\xff\xff\xff\x01\x12*\n" +
	"\x1dERR_FRIEND_MAX_INVITATION_NUM\x10\xbc\xb1\xff\xff\xff\xff\xff\xff\xff\x01\x120\n" +
	"#ERR_FRIEND_OTHER_MAX_INVITATION_NUM\x10\xbb\xb1\xff\xff\xff\xff\xff\xff\xff\x01\x12,\n" +
	"\x1fERR_FRIEND_INVITATION_NOT_EXIST\x10\xba\xb1\xff\xff\xff\xff\xff\xff\xff\x01\x12&\n" +
	"\x19ERR_FRIEND_MAX_FRIEND_NUM\x10\xb9\xb1\xff\xff\xff\xff\xff\xff\xff\x01\x12,\n" +
	"\x1fERR_FRIEND_OTHER_MAX_FRIEND_NUM\x10\xb8\xb1\xff\xff\xff\xff\xff\xff\xff\x01\x12\x1e\n" +
	"\x11ERR_FRIEND_SHIELD\x10\xb7\xb1\xff\xff\xff\xff\xff\xff\xff\x01\x12\"\n" +
	"\x15ERR_FRIEND_MAX_SHIELD\x10\xb6\xb1\xff\xff\xff\xff\xff\xff\xff\x01\x12!\n" +
	"\x14ERR_MALL_OUT_OF_TIME\x10\xee\xb0\xff\xff\xff\xff\xff\xff\xff\x01\x12!\n" +
	"\x14ERR_MALL_DAILY_LIMIT\x10\xed\xb0\xff\xff\xff\xff\xff\xff\xff\x01\x12\x1f\n" +
	"\x12ERR_MALL_BUY_LIMIT\x10\xec\xb0\xff\xff\xff\xff\xff\xff\xff\x01\x12%\n" +
	"\x18ERR_MAIN_TASK_NOT_FINISH\x10ڰ\xff\xff\xff\xff\xff\xff\xff\x01\x12\x1f\n" +
	"\x12ERR_GUIDE_IS_EXIST\x10\xb5\xb0\xff\xff\xff\xff\xff\xff\xff\x01\x12\"\n" +
	"\x15ERR_FUNCTION_NOT_OPEN\x10\xb4\xb0\xff\xff\xff\xff\xff\xff\xff\x01\x12&\n" +
	"\x19ERR_TEXAS_FOLD_PARAMETERS\x10\xe0\xe3\xfe\xff\xff\xff\xff\xff\xff\x01\x12$\n" +
	"\x17ERR_TEXAS_SEAT_OCCUPIED\x10\xdf\xe3\xfe\xff\xff\xff\xff\xff\xff\x01\x12)\n" +
	"\x1cERR_TEXAS_PLAYER_NOT_IN_GAME\x10\xde\xe3\xfe\xff\xff\xff\xff\xff\xff\x01\x12(\n" +
	"\x1bERR_TEXAS_PLAYER_NOT_ACTIVE\x10\xdd\xe3\xfe\xff\xff\xff\xff\xff\xff\x01\x12.\n" +
	"!ERR_TEXAS_PLAYER_STATUS_INCORRECT\x10\xdc\xe3\xfe\xff\xff\xff\xff\xff\xff\x01\x12%\n" +
	"\x18ERR_TEXAS_PLAYER_IN_GAME\x10\xdb\xe3\xfe\xff\xff\xff\xff\xff\xff\x01\x12!\n" +
	"\x14ERR_TEXAS_TABLE_FULL\x10\xda\xe3\xfe\xff\xff\xff\xff\xff\xff\x01\x12#\n" +
	"\x16ERR_TEXAS_NOT_IN_TABLE\x10\xd9\xe3\xfe\xff\xff\xff\xff\xff\xff\x01\x12*\n" +
	"\x1dERR_TEXAS_STAND_UP_PARAMETERS\x10\xd8\xe3\xfe\xff\xff\xff\xff\xff\xff\x01\x12*\n" +
	"\x1dERR_TEXAS_PLAYER_HAS_STAND_UP\x10\xd7\xe3\xfe\xff\xff\xff\xff\xff\xff\x01\x12(\n" +
	"\x1bERR_TEXAS_DO_BET_PARAMETERS\x10\xd6\xe3\xfe\xff\xff\xff\xff\xff\xff\x01\x12'\n" +
	"\x1aERR_TEXAS_CHIPS_NOT_ENOUGH\x10\xd5\xe3\xfe\xff\xff\xff\xff\xff\xff\x01\x12,\n" +
	"\x1fERR_TEXAS_CALL_CHIPS_NOT_ENOUGH\x10\xd4\xe3\xfe\xff\xff\xff\xff\xff\xff\x01\x12-\n" +
	" ERR_TEXAS_RAISE_CHIPS_NOT_ENOUGH\x10\xd3\xe3\xfe\xff\xff\xff\xff\xff\xff\x01\x12'\n" +
	"\x1aERR_TEXAS_CONFIG_NOT_FOUND\x10\xd2\xe3\xfe\xff\xff\xff\xff\xff\xff\x01\x12%\n" +
	"\x18ERR_TEXAS_SEAT_NOT_FOUND\x10\xd1\xe3\xfe\xff\xff\xff\xff\xff\xff\x01\x12 \n" +
	"\x13ERR_RANK_TYPE_ERROR\x10\xf0\xc0\xfa\xff\xff\xff\xff\xff\xff\x01B9Z7github.com/Iori372552686/g1_common/protocol;g1_protocolb\x06proto3"

var (
	file_core_error_code_proto_rawDescOnce sync.Once
	file_core_error_code_proto_rawDescData []byte
)

func file_core_error_code_proto_rawDescGZIP() []byte {
	file_core_error_code_proto_rawDescOnce.Do(func() {
		file_core_error_code_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_error_code_proto_rawDesc), len(file_core_error_code_proto_rawDesc)))
	})
	return file_core_error_code_proto_rawDescData
}

var file_core_error_code_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_core_error_code_proto_goTypes = []any{
	(ErrorCode)(0), // 0: g1.protocol.ErrorCode
}
var file_core_error_code_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_error_code_proto_init() }
func file_core_error_code_proto_init() {
	if File_core_error_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_error_code_proto_rawDesc), len(file_core_error_code_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_error_code_proto_goTypes,
		DependencyIndexes: file_core_error_code_proto_depIdxs,
		EnumInfos:         file_core_error_code_proto_enumTypes,
	}.Build()
	File_core_error_code_proto = out.File
	file_core_error_code_proto_goTypes = nil
	file_core_error_code_proto_depIdxs = nil
}
