// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: core/game_enum.proto

package g1_protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 花色定义（通用卡牌原语）
type Color int32

const (
	Color_COLOR_NONE    Color = 0 // 无花色
	Color_COLOR_DIAMOND Color = 1 // 1
	Color_COLOR_CLUB    Color = 2 // 2
	Color_COLOR_HEART   Color = 4 // 4
	Color_COLOR_SPADE   Color = 8 // 8
)

// Enum value maps for Color.
var (
	Color_name = map[int32]string{
		0: "COLOR_NONE",
		1: "COLOR_DIAMOND",
		2: "COLOR_CLUB",
		4: "COLOR_HEART",
		8: "COLOR_SPADE",
	}
	Color_value = map[string]int32{
		"COLOR_NONE":    0,
		"COLOR_DIAMOND": 1,
		"COLOR_CLUB":    2,
		"COLOR_HEART":   4,
		"COLOR_SPADE":   8,
	}
)

func (x Color) Enum() *Color {
	p := new(Color)
	*p = x
	return p
}

func (x Color) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Color) Descriptor() protoreflect.EnumDescriptor {
	return file_core_game_enum_proto_enumTypes[0].Descriptor()
}

func (Color) Type() protoreflect.EnumType {
	return &file_core_game_enum_proto_enumTypes[0]
}

func (x Color) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Color.Descriptor instead.
func (Color) EnumDescriptor() ([]byte, []int) {
	return file_core_game_enum_proto_rawDescGZIP(), []int{0}
}

// 点数（通用卡牌原语）
type Rank int32

const (
	Rank_Rank_0  Rank = 0 // 无点数
	Rank_RANK_1  Rank = 1 // A座位1的时候
	Rank_RANK_2  Rank = 2
	Rank_RANK_3  Rank = 3
	Rank_RANK_4  Rank = 4
	Rank_RANK_5  Rank = 5
	Rank_RANK_6  Rank = 6
	Rank_RANK_7  Rank = 7
	Rank_RANK_8  Rank = 8
	Rank_RANK_9  Rank = 9
	Rank_RANK_10 Rank = 10
	Rank_RANK_J  Rank = 11
	Rank_RANK_Q  Rank = 12
	Rank_RANK_K  Rank = 13
	Rank_RANK_A  Rank = 14
)

// Enum value maps for Rank.
var (
	Rank_name = map[int32]string{
		0:  "Rank_0",
		1:  "RANK_1",
		2:  "RANK_2",
		3:  "RANK_3",
		4:  "RANK_4",
		5:  "RANK_5",
		6:  "RANK_6",
		7:  "RANK_7",
		8:  "RANK_8",
		9:  "RANK_9",
		10: "RANK_10",
		11: "RANK_J",
		12: "RANK_Q",
		13: "RANK_K",
		14: "RANK_A",
	}
	Rank_value = map[string]int32{
		"Rank_0":  0,
		"RANK_1":  1,
		"RANK_2":  2,
		"RANK_3":  3,
		"RANK_4":  4,
		"RANK_5":  5,
		"RANK_6":  6,
		"RANK_7":  7,
		"RANK_8":  8,
		"RANK_9":  9,
		"RANK_10": 10,
		"RANK_J":  11,
		"RANK_Q":  12,
		"RANK_K":  13,
		"RANK_A":  14,
	}
)

func (x Rank) Enum() *Rank {
	p := new(Rank)
	*p = x
	return p
}

func (x Rank) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Rank) Descriptor() protoreflect.EnumDescriptor {
	return file_core_game_enum_proto_enumTypes[1].Descriptor()
}

func (Rank) Type() protoreflect.EnumType {
	return &file_core_game_enum_proto_enumTypes[1]
}

func (x Rank) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Rank.Descriptor instead.
func (Rank) EnumDescriptor() ([]byte, []int) {
	return file_core_game_enum_proto_rawDescGZIP(), []int{1}
}

type GameTypeId int32

const (
	GameTypeId_GAME_TYPE_NONE GameTypeId = 0 // 无效玩法
	// rummy
	GameTypeId_RUMMY_MODE_START GameTypeId = 20 // RUMMY玩法开始
	GameTypeId_RUMMY_NORMAL     GameTypeId = 21 // RUMMY常规玩法
)

// Enum value maps for GameTypeId.
var (
	GameTypeId_name = map[int32]string{
		0:  "GAME_TYPE_NONE",
		20: "RUMMY_MODE_START",
		21: "RUMMY_NORMAL",
	}
	GameTypeId_value = map[string]int32{
		"GAME_TYPE_NONE":   0,
		"RUMMY_MODE_START": 20,
		"RUMMY_NORMAL":     21,
	}
)

func (x GameTypeId) Enum() *GameTypeId {
	p := new(GameTypeId)
	*p = x
	return p
}

func (x GameTypeId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameTypeId) Descriptor() protoreflect.EnumDescriptor {
	return file_core_game_enum_proto_enumTypes[2].Descriptor()
}

func (GameTypeId) Type() protoreflect.EnumType {
	return &file_core_game_enum_proto_enumTypes[2]
}

func (x GameTypeId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameTypeId.Descriptor instead.
func (GameTypeId) EnumDescriptor() ([]byte, []int) {
	return file_core_game_enum_proto_rawDescGZIP(), []int{2}
}

type CoinType int32

const (
	CoinType_COIN_NONE  CoinType = 0 // 无效币种
	CoinType_COIN_GOLD  CoinType = 1 // 金币
	CoinType_COIN_ACE   CoinType = 2 // Ace coin
	CoinType_COIN_SCORE CoinType = 3 // 积分
)

// Enum value maps for CoinType.
var (
	CoinType_name = map[int32]string{
		0: "COIN_NONE",
		1: "COIN_GOLD",
		2: "COIN_ACE",
		3: "COIN_SCORE",
	}
	CoinType_value = map[string]int32{
		"COIN_NONE":  0,
		"COIN_GOLD":  1,
		"COIN_ACE":   2,
		"COIN_SCORE": 3,
	}
)

func (x CoinType) Enum() *CoinType {
	p := new(CoinType)
	*p = x
	return p
}

func (x CoinType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CoinType) Descriptor() protoreflect.EnumDescriptor {
	return file_core_game_enum_proto_enumTypes[3].Descriptor()
}

func (CoinType) Type() protoreflect.EnumType {
	return &file_core_game_enum_proto_enumTypes[3]
}

func (x CoinType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CoinType.Descriptor instead.
func (CoinType) EnumDescriptor() ([]byte, []int) {
	return file_core_game_enum_proto_rawDescGZIP(), []int{3}
}

type RoomStage int32

const (
	RoomStage_Free      RoomStage = 0  // 免费模式，体验模式
	RoomStage_LOW       RoomStage = 1  // 初级
	RoomStage_MIDDLE    RoomStage = 2  // 中级
	RoomStage_HIGH      RoomStage = 3  // 高级
	RoomStage_Stage_ALL RoomStage = 99 // 全部类型
)

// Enum value maps for RoomStage.
var (
	RoomStage_name = map[int32]string{
		0:  "Free",
		1:  "LOW",
		2:  "MIDDLE",
		3:  "HIGH",
		99: "Stage_ALL",
	}
	RoomStage_value = map[string]int32{
		"Free":      0,
		"LOW":       1,
		"MIDDLE":    2,
		"HIGH":      3,
		"Stage_ALL": 99,
	}
)

func (x RoomStage) Enum() *RoomStage {
	p := new(RoomStage)
	*p = x
	return p
}

func (x RoomStage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomStage) Descriptor() protoreflect.EnumDescriptor {
	return file_core_game_enum_proto_enumTypes[4].Descriptor()
}

func (RoomStage) Type() protoreflect.EnumType {
	return &file_core_game_enum_proto_enumTypes[4]
}

func (x RoomStage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomStage.Descriptor instead.
func (RoomStage) EnumDescriptor() ([]byte, []int) {
	return file_core_game_enum_proto_rawDescGZIP(), []int{4}
}

type RoomState int32

const (
	RoomState_WAITSTART RoomState = 0 // 等待开始
	RoomState_PLAYING   RoomState = 1 // 比赛中
	RoomState_END       RoomState = 2 // 已结束
	RoomState_PAUSE     RoomState = 3 //房间状态暂停
)

// Enum value maps for RoomState.
var (
	RoomState_name = map[int32]string{
		0: "WAITSTART",
		1: "PLAYING",
		2: "END",
		3: "PAUSE",
	}
	RoomState_value = map[string]int32{
		"WAITSTART": 0,
		"PLAYING":   1,
		"END":       2,
		"PAUSE":     3,
	}
)

func (x RoomState) Enum() *RoomState {
	p := new(RoomState)
	*p = x
	return p
}

func (x RoomState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomState) Descriptor() protoreflect.EnumDescriptor {
	return file_core_game_enum_proto_enumTypes[5].Descriptor()
}

func (RoomState) Type() protoreflect.EnumType {
	return &file_core_game_enum_proto_enumTypes[5]
}

func (x RoomState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomState.Descriptor instead.
func (RoomState) EnumDescriptor() ([]byte, []int) {
	return file_core_game_enum_proto_rawDescGZIP(), []int{5}
}

type RoomSortType int32

const (
	RoomSortType_SORT_TYPE_NONE   RoomSortType = 0 // 默认值
	RoomSortType_SORT_TYPE_ID     RoomSortType = 1 // ID排序
	RoomSortType_SORT_TYPE_PLAYER RoomSortType = 2 // 玩家人数排序
	RoomSortType_SORT_TYPE_TIME   RoomSortType = 3 // 时间排序
)

// Enum value maps for RoomSortType.
var (
	RoomSortType_name = map[int32]string{
		0: "SORT_TYPE_NONE",
		1: "SORT_TYPE_ID",
		2: "SORT_TYPE_PLAYER",
		3: "SORT_TYPE_TIME",
	}
	RoomSortType_value = map[string]int32{
		"SORT_TYPE_NONE":   0,
		"SORT_TYPE_ID":     1,
		"SORT_TYPE_PLAYER": 2,
		"SORT_TYPE_TIME":   3,
	}
)

func (x RoomSortType) Enum() *RoomSortType {
	p := new(RoomSortType)
	*p = x
	return p
}

func (x RoomSortType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomSortType) Descriptor() protoreflect.EnumDescriptor {
	return file_core_game_enum_proto_enumTypes[6].Descriptor()
}

func (RoomSortType) Type() protoreflect.EnumType {
	return &file_core_game_enum_proto_enumTypes[6]
}

func (x RoomSortType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomSortType.Descriptor instead.
func (RoomSortType) EnumDescriptor() ([]byte, []int) {
	return file_core_game_enum_proto_rawDescGZIP(), []int{6}
}

var File_core_game_enum_proto protoreflect.FileDescriptor

const file_core_game_enum_proto_rawDesc = "" +
	"\n" +
	"\x14core/game_enum.proto\x12\vg1.protocol*\\\n" +
	"\x05Color\x12\x0e\n" +
	"\n" +
	"COLOR_NONE\x10\x00\x12\x11\n" +
	"\rCOLOR_DIAMOND\x10\x01\x12\x0e\n" +
	"\n" +
	"COLOR_CLUB\x10\x02\x12\x0f\n" +
	"\vCOLOR_HEART\x10\x04\x12\x0f\n" +
	"\vCOLOR_SPADE\x10\b*\xbb\x01\n" +
	"\x04Rank\x12\n" +
	"\n" +
	"\x06Rank_0\x10\x00\x12\n" +
	"\n" +
	"\x06RANK_1\x10\x01\x12\n" +
	"\n" +
	"\x06RANK_2\x10\x02\x12\n" +
	"\n" +
	"\x06RANK_3\x10\x03\x12\n" +
	"\n" +
	"\x06RANK_4\x10\x04\x12\n" +
	"\n" +
	"\x06RANK_5\x10\x05\x12\n" +
	"\n" +
	"\x06RANK_6\x10\x06\x12\n" +
	"\n" +
	"\x06RANK_7\x10\a\x12\n" +
	"\n" +
	"\x06RANK_8\x10\b\x12\n" +
	"\n" +
	"\x06RANK_9\x10\t\x12\v\n" +
	"\aRANK_10\x10\n" +
	"\x12\n" +
	"\n" +
	"\x06RANK_J\x10\v\x12\n" +
	"\n" +
	"\x06RANK_Q\x10\f\x12\n" +
	"\n" +
	"\x06RANK_K\x10\r\x12\n" +
	"\n" +
	"\x06RANK_A\x10\x0e*H\n" +
	"\n" +
	"GameTypeId\x12\x12\n" +
	"\x0eGAME_TYPE_NONE\x10\x00\x12\x14\n" +
	"\x10RUMMY_MODE_START\x10\x14\x12\x10\n" +
	"\fRUMMY_NORMAL\x10\x15*F\n" +
	"\bCoinType\x12\r\n" +
	"\tCOIN_NONE\x10\x00\x12\r\n" +
	"\tCOIN_GOLD\x10\x01\x12\f\n" +
	"\bCOIN_ACE\x10\x02\x12\x0e\n" +
	"\n" +
	"COIN_SCORE\x10\x03*C\n" +
	"\tRoomStage\x12\b\n" +
	"\x04Free\x10\x00\x12\a\n" +
	"\x03LOW\x10\x01\x12\n" +
	"\n" +
	"\x06MIDDLE\x10\x02\x12\b\n" +
	"\x04HIGH\x10\x03\x12\r\n" +
	"\tStage_ALL\x10c*;\n" +
	"\tRoomState\x12\r\n" +
	"\tWAITSTART\x10\x00\x12\v\n" +
	"\aPLAYING\x10\x01\x12\a\n" +
	"\x03END\x10\x02\x12\t\n" +
	"\x05PAUSE\x10\x03*^\n" +
	"\fRoomSortType\x12\x12\n" +
	"\x0eSORT_TYPE_NONE\x10\x00\x12\x10\n" +
	"\fSORT_TYPE_ID\x10\x01\x12\x14\n" +
	"\x10SORT_TYPE_PLAYER\x10\x02\x12\x12\n" +
	"\x0eSORT_TYPE_TIME\x10\x03B9Z7github.com/Iori372552686/g1_common/protocol;g1_protocolb\x06proto3"

var (
	file_core_game_enum_proto_rawDescOnce sync.Once
	file_core_game_enum_proto_rawDescData []byte
)

func file_core_game_enum_proto_rawDescGZIP() []byte {
	file_core_game_enum_proto_rawDescOnce.Do(func() {
		file_core_game_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_game_enum_proto_rawDesc), len(file_core_game_enum_proto_rawDesc)))
	})
	return file_core_game_enum_proto_rawDescData
}

var file_core_game_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_core_game_enum_proto_goTypes = []any{
	(Color)(0),        // 0: g1.protocol.Color
	(Rank)(0),         // 1: g1.protocol.Rank
	(GameTypeId)(0),   // 2: g1.protocol.GameTypeId
	(CoinType)(0),     // 3: g1.protocol.CoinType
	(RoomStage)(0),    // 4: g1.protocol.RoomStage
	(RoomState)(0),    // 5: g1.protocol.RoomState
	(RoomSortType)(0), // 6: g1.protocol.RoomSortType
}
var file_core_game_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_game_enum_proto_init() }
func file_core_game_enum_proto_init() {
	if File_core_game_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_game_enum_proto_rawDesc), len(file_core_game_enum_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_game_enum_proto_goTypes,
		DependencyIndexes: file_core_game_enum_proto_depIdxs,
		EnumInfos:         file_core_game_enum_proto_enumTypes,
	}.Build()
	File_core_game_enum_proto = out.File
	file_core_game_enum_proto_goTypes = nil
	file_core_game_enum_proto_depIdxs = nil
}
