//
// 本代码由xlsx工具生成，请勿手动修改

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: config/item.proto

package g1_protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=ItemId,proto3" json:"ItemId,omitempty"`               // 物品Id
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`                    // 物品名
	Type          int32                  `protobuf:"varint,3,opt,name=Type,proto3" json:"Type,omitempty"`                   // 大类
	MainType      int32                  `protobuf:"varint,4,opt,name=MainType,proto3" json:"MainType,omitempty"`           // 主类型
	SubType       int32                  `protobuf:"varint,5,opt,name=SubType,proto3" json:"SubType,omitempty"`             // 子类型
	Description   string                 `protobuf:"bytes,6,opt,name=Description,proto3" json:"Description,omitempty"`      // 描述
	Quality       int32                  `protobuf:"varint,7,opt,name=Quality,proto3" json:"Quality,omitempty"`             // 品质
	Icon          string                 `protobuf:"bytes,8,opt,name=Icon,proto3" json:"Icon,omitempty"`                    // 图标
	BagType       int32                  `protobuf:"varint,9,opt,name=BagType,proto3" json:"BagType,omitempty"`             // 背包页签
	NeedLevel     int32                  `protobuf:"varint,10,opt,name=NeedLevel,proto3" json:"NeedLevel,omitempty"`        // 所需等级
	GetWayDes     string                 `protobuf:"bytes,11,opt,name=GetWayDes,proto3" json:"GetWayDes,omitempty"`         // 获取途径_描述
	GetWayJump    string                 `protobuf:"bytes,12,opt,name=GetWayJump,proto3" json:"GetWayJump,omitempty"`       // 获取途径_跳转
	EffectiveTime string                 `protobuf:"bytes,13,opt,name=EffectiveTime,proto3" json:"EffectiveTime,omitempty"` // 生效时间
	InvalidTime   string                 `protobuf:"bytes,14,opt,name=InvalidTime,proto3" json:"InvalidTime,omitempty"`     // 失效时间
	Combine       int32                  `protobuf:"varint,15,opt,name=Combine,proto3" json:"Combine,omitempty"`            // 是否合成
	Sale          int32                  `protobuf:"varint,16,opt,name=Sale,proto3" json:"Sale,omitempty"`                  // 出售
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemConfig) Reset() {
	*x = ItemConfig{}
	mi := &file_config_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemConfig) ProtoMessage() {}

func (x *ItemConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemConfig.ProtoReflect.Descriptor instead.
func (*ItemConfig) Descriptor() ([]byte, []int) {
	return file_config_item_proto_rawDescGZIP(), []int{0}
}

func (x *ItemConfig) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ItemConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemConfig) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ItemConfig) GetMainType() int32 {
	if x != nil {
		return x.MainType
	}
	return 0
}

func (x *ItemConfig) GetSubType() int32 {
	if x != nil {
		return x.SubType
	}
	return 0
}

func (x *ItemConfig) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ItemConfig) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

func (x *ItemConfig) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *ItemConfig) GetBagType() int32 {
	if x != nil {
		return x.BagType
	}
	return 0
}

func (x *ItemConfig) GetNeedLevel() int32 {
	if x != nil {
		return x.NeedLevel
	}
	return 0
}

func (x *ItemConfig) GetGetWayDes() string {
	if x != nil {
		return x.GetWayDes
	}
	return ""
}

func (x *ItemConfig) GetGetWayJump() string {
	if x != nil {
		return x.GetWayJump
	}
	return ""
}

func (x *ItemConfig) GetEffectiveTime() string {
	if x != nil {
		return x.EffectiveTime
	}
	return ""
}

func (x *ItemConfig) GetInvalidTime() string {
	if x != nil {
		return x.InvalidTime
	}
	return ""
}

func (x *ItemConfig) GetCombine() int32 {
	if x != nil {
		return x.Combine
	}
	return 0
}

func (x *ItemConfig) GetSale() int32 {
	if x != nil {
		return x.Sale
	}
	return 0
}

type ItemConfigAry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ary           []*ItemConfig          `protobuf:"bytes,1,rep,name=Ary,proto3" json:"Ary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemConfigAry) Reset() {
	*x = ItemConfigAry{}
	mi := &file_config_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemConfigAry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemConfigAry) ProtoMessage() {}

func (x *ItemConfigAry) ProtoReflect() protoreflect.Message {
	mi := &file_config_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemConfigAry.ProtoReflect.Descriptor instead.
func (*ItemConfigAry) Descriptor() ([]byte, []int) {
	return file_config_item_proto_rawDescGZIP(), []int{1}
}

func (x *ItemConfigAry) GetAry() []*ItemConfig {
	if x != nil {
		return x.Ary
	}
	return nil
}

type ItemDecomposeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`                     // Id
	ItemId        int32                  `protobuf:"varint,2,opt,name=ItemId,proto3" json:"ItemId,omitempty"`             // 被分解道具Id
	OutputItemId  int32                  `protobuf:"varint,3,opt,name=OutputItemId,proto3" json:"OutputItemId,omitempty"` // 产出道具Id
	OutputCount   int32                  `protobuf:"varint,4,opt,name=OutputCount,proto3" json:"OutputCount,omitempty"`   // 产出数量
	IsEnable      int32                  `protobuf:"varint,5,opt,name=IsEnable,proto3" json:"IsEnable,omitempty"`         // 是否启用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemDecomposeConfig) Reset() {
	*x = ItemDecomposeConfig{}
	mi := &file_config_item_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemDecomposeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemDecomposeConfig) ProtoMessage() {}

func (x *ItemDecomposeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_item_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemDecomposeConfig.ProtoReflect.Descriptor instead.
func (*ItemDecomposeConfig) Descriptor() ([]byte, []int) {
	return file_config_item_proto_rawDescGZIP(), []int{2}
}

func (x *ItemDecomposeConfig) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemDecomposeConfig) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ItemDecomposeConfig) GetOutputItemId() int32 {
	if x != nil {
		return x.OutputItemId
	}
	return 0
}

func (x *ItemDecomposeConfig) GetOutputCount() int32 {
	if x != nil {
		return x.OutputCount
	}
	return 0
}

func (x *ItemDecomposeConfig) GetIsEnable() int32 {
	if x != nil {
		return x.IsEnable
	}
	return 0
}

type ItemDecomposeConfigAry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ary           []*ItemDecomposeConfig `protobuf:"bytes,1,rep,name=Ary,proto3" json:"Ary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemDecomposeConfigAry) Reset() {
	*x = ItemDecomposeConfigAry{}
	mi := &file_config_item_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemDecomposeConfigAry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemDecomposeConfigAry) ProtoMessage() {}

func (x *ItemDecomposeConfigAry) ProtoReflect() protoreflect.Message {
	mi := &file_config_item_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemDecomposeConfigAry.ProtoReflect.Descriptor instead.
func (*ItemDecomposeConfigAry) Descriptor() ([]byte, []int) {
	return file_config_item_proto_rawDescGZIP(), []int{3}
}

func (x *ItemDecomposeConfigAry) GetAry() []*ItemDecomposeConfig {
	if x != nil {
		return x.Ary
	}
	return nil
}

type ItemRuleConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`                               // 规则Id
	Name              string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`                            // 规则名
	CanExchange       int32                  `protobuf:"varint,3,opt,name=CanExchange,proto3" json:"CanExchange,omitempty"`             // 可交换
	CanUse            int32                  `protobuf:"varint,4,opt,name=CanUse,proto3" json:"CanUse,omitempty"`                       // 可使用
	MaxOwnCount       int32                  `protobuf:"varint,5,opt,name=MaxOwnCount,proto3" json:"MaxOwnCount,omitempty"`             // 最大拥有数
	MaxOverlay        int32                  `protobuf:"varint,6,opt,name=MaxOverlay,proto3" json:"MaxOverlay,omitempty"`               // 单堆上限
	MaxUseCount       int32                  `protobuf:"varint,7,opt,name=MaxUseCount,proto3" json:"MaxUseCount,omitempty"`             // 最大使用次数
	MaxUseNumber      int32                  `protobuf:"varint,8,opt,name=MaxUseNumber,proto3" json:"MaxUseNumber,omitempty"`           // 单次使用数
	UseNumberInterval int32                  `protobuf:"varint,9,opt,name=UseNumberInterval,proto3" json:"UseNumberInterval,omitempty"` // 使用间隔
	Getuse            int32                  `protobuf:"varint,10,opt,name=Getuse,proto3" json:"Getuse,omitempty"`                      // 获得即使用
	CanDecompose      int32                  `protobuf:"varint,11,opt,name=CanDecompose,proto3" json:"CanDecompose,omitempty"`          // 可分解
	CanRecycle        int32                  `protobuf:"varint,12,opt,name=CanRecycle,proto3" json:"CanRecycle,omitempty"`              // 可回收
	CanDrop           int32                  `protobuf:"varint,13,opt,name=CanDrop,proto3" json:"CanDrop,omitempty"`                    // 可丢弃
	CanMail           int32                  `protobuf:"varint,14,opt,name=CanMail,proto3" json:"CanMail,omitempty"`                    // 可邮寄
	TradeLimitDaily   int32                  `protobuf:"varint,15,opt,name=TradeLimitDaily,proto3" json:"TradeLimitDaily,omitempty"`    // 日交易上限
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ItemRuleConfig) Reset() {
	*x = ItemRuleConfig{}
	mi := &file_config_item_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemRuleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemRuleConfig) ProtoMessage() {}

func (x *ItemRuleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_item_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemRuleConfig.ProtoReflect.Descriptor instead.
func (*ItemRuleConfig) Descriptor() ([]byte, []int) {
	return file_config_item_proto_rawDescGZIP(), []int{4}
}

func (x *ItemRuleConfig) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemRuleConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemRuleConfig) GetCanExchange() int32 {
	if x != nil {
		return x.CanExchange
	}
	return 0
}

func (x *ItemRuleConfig) GetCanUse() int32 {
	if x != nil {
		return x.CanUse
	}
	return 0
}

func (x *ItemRuleConfig) GetMaxOwnCount() int32 {
	if x != nil {
		return x.MaxOwnCount
	}
	return 0
}

func (x *ItemRuleConfig) GetMaxOverlay() int32 {
	if x != nil {
		return x.MaxOverlay
	}
	return 0
}

func (x *ItemRuleConfig) GetMaxUseCount() int32 {
	if x != nil {
		return x.MaxUseCount
	}
	return 0
}

func (x *ItemRuleConfig) GetMaxUseNumber() int32 {
	if x != nil {
		return x.MaxUseNumber
	}
	return 0
}

func (x *ItemRuleConfig) GetUseNumberInterval() int32 {
	if x != nil {
		return x.UseNumberInterval
	}
	return 0
}

func (x *ItemRuleConfig) GetGetuse() int32 {
	if x != nil {
		return x.Getuse
	}
	return 0
}

func (x *ItemRuleConfig) GetCanDecompose() int32 {
	if x != nil {
		return x.CanDecompose
	}
	return 0
}

func (x *ItemRuleConfig) GetCanRecycle() int32 {
	if x != nil {
		return x.CanRecycle
	}
	return 0
}

func (x *ItemRuleConfig) GetCanDrop() int32 {
	if x != nil {
		return x.CanDrop
	}
	return 0
}

func (x *ItemRuleConfig) GetCanMail() int32 {
	if x != nil {
		return x.CanMail
	}
	return 0
}

func (x *ItemRuleConfig) GetTradeLimitDaily() int32 {
	if x != nil {
		return x.TradeLimitDaily
	}
	return 0
}

type ItemRuleConfigAry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ary           []*ItemRuleConfig      `protobuf:"bytes,1,rep,name=Ary,proto3" json:"Ary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemRuleConfigAry) Reset() {
	*x = ItemRuleConfigAry{}
	mi := &file_config_item_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemRuleConfigAry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemRuleConfigAry) ProtoMessage() {}

func (x *ItemRuleConfigAry) ProtoReflect() protoreflect.Message {
	mi := &file_config_item_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemRuleConfigAry.ProtoReflect.Descriptor instead.
func (*ItemRuleConfigAry) Descriptor() ([]byte, []int) {
	return file_config_item_proto_rawDescGZIP(), []int{5}
}

func (x *ItemRuleConfigAry) GetAry() []*ItemRuleConfig {
	if x != nil {
		return x.Ary
	}
	return nil
}

type ItemRuleRefConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=ItemId,proto3" json:"ItemId,omitempty"` // 道具Id
	RuleId        int32                  `protobuf:"varint,2,opt,name=RuleId,proto3" json:"RuleId,omitempty"` // 规则Id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemRuleRefConfig) Reset() {
	*x = ItemRuleRefConfig{}
	mi := &file_config_item_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemRuleRefConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemRuleRefConfig) ProtoMessage() {}

func (x *ItemRuleRefConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_item_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemRuleRefConfig.ProtoReflect.Descriptor instead.
func (*ItemRuleRefConfig) Descriptor() ([]byte, []int) {
	return file_config_item_proto_rawDescGZIP(), []int{6}
}

func (x *ItemRuleRefConfig) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ItemRuleRefConfig) GetRuleId() int32 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

type ItemRuleRefConfigAry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ary           []*ItemRuleRefConfig   `protobuf:"bytes,1,rep,name=Ary,proto3" json:"Ary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemRuleRefConfigAry) Reset() {
	*x = ItemRuleRefConfigAry{}
	mi := &file_config_item_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemRuleRefConfigAry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemRuleRefConfigAry) ProtoMessage() {}

func (x *ItemRuleRefConfigAry) ProtoReflect() protoreflect.Message {
	mi := &file_config_item_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemRuleRefConfigAry.ProtoReflect.Descriptor instead.
func (*ItemRuleRefConfigAry) Descriptor() ([]byte, []int) {
	return file_config_item_proto_rawDescGZIP(), []int{7}
}

func (x *ItemRuleRefConfigAry) GetAry() []*ItemRuleRefConfig {
	if x != nil {
		return x.Ary
	}
	return nil
}

type ItemUseConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`             // 道具Id
	UseType       int32                  `protobuf:"varint,2,opt,name=UseType,proto3" json:"UseType,omitempty"`   // 使用类型
	UseId         int32                  `protobuf:"varint,3,opt,name=UseId,proto3" json:"UseId,omitempty"`       // 使用参数Id
	UseValue      int32                  `protobuf:"varint,4,opt,name=UseValue,proto3" json:"UseValue,omitempty"` // 使用参数值
	UseCD         int32                  `protobuf:"varint,5,opt,name=UseCD,proto3" json:"UseCD,omitempty"`       // 使用CD
	IsEnable      int32                  `protobuf:"varint,6,opt,name=IsEnable,proto3" json:"IsEnable,omitempty"` // 是否启用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemUseConfig) Reset() {
	*x = ItemUseConfig{}
	mi := &file_config_item_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemUseConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemUseConfig) ProtoMessage() {}

func (x *ItemUseConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_item_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemUseConfig.ProtoReflect.Descriptor instead.
func (*ItemUseConfig) Descriptor() ([]byte, []int) {
	return file_config_item_proto_rawDescGZIP(), []int{8}
}

func (x *ItemUseConfig) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemUseConfig) GetUseType() int32 {
	if x != nil {
		return x.UseType
	}
	return 0
}

func (x *ItemUseConfig) GetUseId() int32 {
	if x != nil {
		return x.UseId
	}
	return 0
}

func (x *ItemUseConfig) GetUseValue() int32 {
	if x != nil {
		return x.UseValue
	}
	return 0
}

func (x *ItemUseConfig) GetUseCD() int32 {
	if x != nil {
		return x.UseCD
	}
	return 0
}

func (x *ItemUseConfig) GetIsEnable() int32 {
	if x != nil {
		return x.IsEnable
	}
	return 0
}

type ItemUseConfigAry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ary           []*ItemUseConfig       `protobuf:"bytes,1,rep,name=Ary,proto3" json:"Ary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemUseConfigAry) Reset() {
	*x = ItemUseConfigAry{}
	mi := &file_config_item_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemUseConfigAry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemUseConfigAry) ProtoMessage() {}

func (x *ItemUseConfigAry) ProtoReflect() protoreflect.Message {
	mi := &file_config_item_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemUseConfigAry.ProtoReflect.Descriptor instead.
func (*ItemUseConfigAry) Descriptor() ([]byte, []int) {
	return file_config_item_proto_rawDescGZIP(), []int{9}
}

func (x *ItemUseConfigAry) GetAry() []*ItemUseConfig {
	if x != nil {
		return x.Ary
	}
	return nil
}

var File_config_item_proto protoreflect.FileDescriptor

const file_config_item_proto_rawDesc = "" +
	"\n" +
	"\x11config/item.proto\x12\vg1.protocol\"\xbe\x03\n" +
	"\n" +
	"ItemConfig\x12\x16\n" +
	"\x06ItemId\x18\x01 \x01(\x05R\x06ItemId\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x12\n" +
	"\x04Type\x18\x03 \x01(\x05R\x04Type\x12\x1a\n" +
	"\bMainType\x18\x04 \x01(\x05R\bMainType\x12\x18\n" +
	"\aSubType\x18\x05 \x01(\x05R\aSubType\x12 \n" +
	"\vDescription\x18\x06 \x01(\tR\vDescription\x12\x18\n" +
	"\aQuality\x18\a \x01(\x05R\aQuality\x12\x12\n" +
	"\x04Icon\x18\b \x01(\tR\x04Icon\x12\x18\n" +
	"\aBagType\x18\t \x01(\x05R\aBagType\x12\x1c\n" +
	"\tNeedLevel\x18\n" +
	" \x01(\x05R\tNeedLevel\x12\x1c\n" +
	"\tGetWayDes\x18\v \x01(\tR\tGetWayDes\x12\x1e\n" +
	"\n" +
	"GetWayJump\x18\f \x01(\tR\n" +
	"GetWayJump\x12$\n" +
	"\rEffectiveTime\x18\r \x01(\tR\rEffectiveTime\x12 \n" +
	"\vInvalidTime\x18\x0e \x01(\tR\vInvalidTime\x12\x18\n" +
	"\aCombine\x18\x0f \x01(\x05R\aCombine\x12\x12\n" +
	"\x04Sale\x18\x10 \x01(\x05R\x04Sale\":\n" +
	"\rItemConfigAry\x12)\n" +
	"\x03Ary\x18\x01 \x03(\v2\x17.g1.protocol.ItemConfigR\x03Ary\"\x9f\x01\n" +
	"\x13ItemDecomposeConfig\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x16\n" +
	"\x06ItemId\x18\x02 \x01(\x05R\x06ItemId\x12\"\n" +
	"\fOutputItemId\x18\x03 \x01(\x05R\fOutputItemId\x12 \n" +
	"\vOutputCount\x18\x04 \x01(\x05R\vOutputCount\x12\x1a\n" +
	"\bIsEnable\x18\x05 \x01(\x05R\bIsEnable\"L\n" +
	"\x16ItemDecomposeConfigAry\x122\n" +
	"\x03Ary\x18\x01 \x03(\v2 .g1.protocol.ItemDecomposeConfigR\x03Ary\"\xde\x03\n" +
	"\x0eItemRuleConfig\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12 \n" +
	"\vCanExchange\x18\x03 \x01(\x05R\vCanExchange\x12\x16\n" +
	"\x06CanUse\x18\x04 \x01(\x05R\x06CanUse\x12 \n" +
	"\vMaxOwnCount\x18\x05 \x01(\x05R\vMaxOwnCount\x12\x1e\n" +
	"\n" +
	"MaxOverlay\x18\x06 \x01(\x05R\n" +
	"MaxOverlay\x12 \n" +
	"\vMaxUseCount\x18\a \x01(\x05R\vMaxUseCount\x12\"\n" +
	"\fMaxUseNumber\x18\b \x01(\x05R\fMaxUseNumber\x12,\n" +
	"\x11UseNumberInterval\x18\t \x01(\x05R\x11UseNumberInterval\x12\x16\n" +
	"\x06Getuse\x18\n" +
	" \x01(\x05R\x06Getuse\x12\"\n" +
	"\fCanDecompose\x18\v \x01(\x05R\fCanDecompose\x12\x1e\n" +
	"\n" +
	"CanRecycle\x18\f \x01(\x05R\n" +
	"CanRecycle\x12\x18\n" +
	"\aCanDrop\x18\r \x01(\x05R\aCanDrop\x12\x18\n" +
	"\aCanMail\x18\x0e \x01(\x05R\aCanMail\x12(\n" +
	"\x0fTradeLimitDaily\x18\x0f \x01(\x05R\x0fTradeLimitDaily\"B\n" +
	"\x11ItemRuleConfigAry\x12-\n" +
	"\x03Ary\x18\x01 \x03(\v2\x1b.g1.protocol.ItemRuleConfigR\x03Ary\"C\n" +
	"\x11ItemRuleRefConfig\x12\x16\n" +
	"\x06ItemId\x18\x01 \x01(\x05R\x06ItemId\x12\x16\n" +
	"\x06RuleId\x18\x02 \x01(\x05R\x06RuleId\"H\n" +
	"\x14ItemRuleRefConfigAry\x120\n" +
	"\x03Ary\x18\x01 \x03(\v2\x1e.g1.protocol.ItemRuleRefConfigR\x03Ary\"\x9d\x01\n" +
	"\rItemUseConfig\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x18\n" +
	"\aUseType\x18\x02 \x01(\x05R\aUseType\x12\x14\n" +
	"\x05UseId\x18\x03 \x01(\x05R\x05UseId\x12\x1a\n" +
	"\bUseValue\x18\x04 \x01(\x05R\bUseValue\x12\x14\n" +
	"\x05UseCD\x18\x05 \x01(\x05R\x05UseCD\x12\x1a\n" +
	"\bIsEnable\x18\x06 \x01(\x05R\bIsEnable\"@\n" +
	"\x10ItemUseConfigAry\x12,\n" +
	"\x03Ary\x18\x01 \x03(\v2\x1a.g1.protocol.ItemUseConfigR\x03AryB9Z7github.com/Iori372552686/g1_common/protocol;g1_protocolb\x06proto3"

var (
	file_config_item_proto_rawDescOnce sync.Once
	file_config_item_proto_rawDescData []byte
)

func file_config_item_proto_rawDescGZIP() []byte {
	file_config_item_proto_rawDescOnce.Do(func() {
		file_config_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_item_proto_rawDesc), len(file_config_item_proto_rawDesc)))
	})
	return file_config_item_proto_rawDescData
}

var file_config_item_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_config_item_proto_goTypes = []any{
	(*ItemConfig)(nil),             // 0: g1.protocol.ItemConfig
	(*ItemConfigAry)(nil),          // 1: g1.protocol.ItemConfigAry
	(*ItemDecomposeConfig)(nil),    // 2: g1.protocol.ItemDecomposeConfig
	(*ItemDecomposeConfigAry)(nil), // 3: g1.protocol.ItemDecomposeConfigAry
	(*ItemRuleConfig)(nil),         // 4: g1.protocol.ItemRuleConfig
	(*ItemRuleConfigAry)(nil),      // 5: g1.protocol.ItemRuleConfigAry
	(*ItemRuleRefConfig)(nil),      // 6: g1.protocol.ItemRuleRefConfig
	(*ItemRuleRefConfigAry)(nil),   // 7: g1.protocol.ItemRuleRefConfigAry
	(*ItemUseConfig)(nil),          // 8: g1.protocol.ItemUseConfig
	(*ItemUseConfigAry)(nil),       // 9: g1.protocol.ItemUseConfigAry
}
var file_config_item_proto_depIdxs = []int32{
	0, // 0: g1.protocol.ItemConfigAry.Ary:type_name -> g1.protocol.ItemConfig
	2, // 1: g1.protocol.ItemDecomposeConfigAry.Ary:type_name -> g1.protocol.ItemDecomposeConfig
	4, // 2: g1.protocol.ItemRuleConfigAry.Ary:type_name -> g1.protocol.ItemRuleConfig
	6, // 3: g1.protocol.ItemRuleRefConfigAry.Ary:type_name -> g1.protocol.ItemRuleRefConfig
	8, // 4: g1.protocol.ItemUseConfigAry.Ary:type_name -> g1.protocol.ItemUseConfig
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_config_item_proto_init() }
func file_config_item_proto_init() {
	if File_config_item_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_item_proto_rawDesc), len(file_config_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_item_proto_goTypes,
		DependencyIndexes: file_config_item_proto_depIdxs,
		MessageInfos:      file_config_item_proto_msgTypes,
	}.Build()
	File_config_item_proto = out.File
	file_config_item_proto_goTypes = nil
	file_config_item_proto_depIdxs = nil
}
