//
// 新增配置表 message（item_rule_config / item_use_config / decompose_config）
// 由 protoc 单独编译为 protocol/item_extra.pb.go，不参与 gen_code.sh 全量编译。
// 字段契约与 game_proto/config/xlsx_config.proto 中由 cfgtool 生成的同名 message 对齐。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: config/item_extra.proto

package g1_protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItemRuleConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	CanExchange       int32                  `protobuf:"varint,3,opt,name=CanExchange,proto3" json:"CanExchange,omitempty"`
	CanUse            int32                  `protobuf:"varint,4,opt,name=CanUse,proto3" json:"CanUse,omitempty"`
	MaxOwnCount       int32                  `protobuf:"varint,5,opt,name=MaxOwnCount,proto3" json:"MaxOwnCount,omitempty"`
	MaxOverlay        int32                  `protobuf:"varint,6,opt,name=MaxOverlay,proto3" json:"MaxOverlay,omitempty"`
	MaxUseCount       int32                  `protobuf:"varint,7,opt,name=MaxUseCount,proto3" json:"MaxUseCount,omitempty"`
	MaxUseNumber      int32                  `protobuf:"varint,8,opt,name=MaxUseNumber,proto3" json:"MaxUseNumber,omitempty"`
	UseNumberInterval int32                  `protobuf:"varint,9,opt,name=UseNumberInterval,proto3" json:"UseNumberInterval,omitempty"`
	Getuse            int32                  `protobuf:"varint,10,opt,name=Getuse,proto3" json:"Getuse,omitempty"`
	CanDecompose      int32                  `protobuf:"varint,11,opt,name=CanDecompose,proto3" json:"CanDecompose,omitempty"`
	CanRecycle        int32                  `protobuf:"varint,12,opt,name=CanRecycle,proto3" json:"CanRecycle,omitempty"`
	CanDrop           int32                  `protobuf:"varint,13,opt,name=CanDrop,proto3" json:"CanDrop,omitempty"`
	CanMail           int32                  `protobuf:"varint,14,opt,name=CanMail,proto3" json:"CanMail,omitempty"`
	TradeLimitDaily   int32                  `protobuf:"varint,15,opt,name=TradeLimitDaily,proto3" json:"TradeLimitDaily,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ItemRuleConfig) Reset() {
	*x = ItemRuleConfig{}
	mi := &file_config_item_extra_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemRuleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemRuleConfig) ProtoMessage() {}

func (x *ItemRuleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_item_extra_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemRuleConfig.ProtoReflect.Descriptor instead.
func (*ItemRuleConfig) Descriptor() ([]byte, []int) {
	return file_config_item_extra_proto_rawDescGZIP(), []int{0}
}

func (x *ItemRuleConfig) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemRuleConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ItemRuleConfig) GetCanExchange() int32 {
	if x != nil {
		return x.CanExchange
	}
	return 0
}

func (x *ItemRuleConfig) GetCanUse() int32 {
	if x != nil {
		return x.CanUse
	}
	return 0
}

func (x *ItemRuleConfig) GetMaxOwnCount() int32 {
	if x != nil {
		return x.MaxOwnCount
	}
	return 0
}

func (x *ItemRuleConfig) GetMaxOverlay() int32 {
	if x != nil {
		return x.MaxOverlay
	}
	return 0
}

func (x *ItemRuleConfig) GetMaxUseCount() int32 {
	if x != nil {
		return x.MaxUseCount
	}
	return 0
}

func (x *ItemRuleConfig) GetMaxUseNumber() int32 {
	if x != nil {
		return x.MaxUseNumber
	}
	return 0
}

func (x *ItemRuleConfig) GetUseNumberInterval() int32 {
	if x != nil {
		return x.UseNumberInterval
	}
	return 0
}

func (x *ItemRuleConfig) GetGetuse() int32 {
	if x != nil {
		return x.Getuse
	}
	return 0
}

func (x *ItemRuleConfig) GetCanDecompose() int32 {
	if x != nil {
		return x.CanDecompose
	}
	return 0
}

func (x *ItemRuleConfig) GetCanRecycle() int32 {
	if x != nil {
		return x.CanRecycle
	}
	return 0
}

func (x *ItemRuleConfig) GetCanDrop() int32 {
	if x != nil {
		return x.CanDrop
	}
	return 0
}

func (x *ItemRuleConfig) GetCanMail() int32 {
	if x != nil {
		return x.CanMail
	}
	return 0
}

func (x *ItemRuleConfig) GetTradeLimitDaily() int32 {
	if x != nil {
		return x.TradeLimitDaily
	}
	return 0
}

type ItemRuleConfigAry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ary           []*ItemRuleConfig      `protobuf:"bytes,1,rep,name=Ary,proto3" json:"Ary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemRuleConfigAry) Reset() {
	*x = ItemRuleConfigAry{}
	mi := &file_config_item_extra_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemRuleConfigAry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemRuleConfigAry) ProtoMessage() {}

func (x *ItemRuleConfigAry) ProtoReflect() protoreflect.Message {
	mi := &file_config_item_extra_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemRuleConfigAry.ProtoReflect.Descriptor instead.
func (*ItemRuleConfigAry) Descriptor() ([]byte, []int) {
	return file_config_item_extra_proto_rawDescGZIP(), []int{1}
}

func (x *ItemRuleConfigAry) GetAry() []*ItemRuleConfig {
	if x != nil {
		return x.Ary
	}
	return nil
}

type ItemUseConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	UseType       int32                  `protobuf:"varint,2,opt,name=UseType,proto3" json:"UseType,omitempty"`
	UseId         int32                  `protobuf:"varint,3,opt,name=UseId,proto3" json:"UseId,omitempty"`
	UseValue      int32                  `protobuf:"varint,4,opt,name=UseValue,proto3" json:"UseValue,omitempty"`
	UseCD         int32                  `protobuf:"varint,5,opt,name=UseCD,proto3" json:"UseCD,omitempty"`
	IsEnable      int32                  `protobuf:"varint,6,opt,name=IsEnable,proto3" json:"IsEnable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemUseConfig) Reset() {
	*x = ItemUseConfig{}
	mi := &file_config_item_extra_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemUseConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemUseConfig) ProtoMessage() {}

func (x *ItemUseConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_item_extra_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemUseConfig.ProtoReflect.Descriptor instead.
func (*ItemUseConfig) Descriptor() ([]byte, []int) {
	return file_config_item_extra_proto_rawDescGZIP(), []int{2}
}

func (x *ItemUseConfig) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ItemUseConfig) GetUseType() int32 {
	if x != nil {
		return x.UseType
	}
	return 0
}

func (x *ItemUseConfig) GetUseId() int32 {
	if x != nil {
		return x.UseId
	}
	return 0
}

func (x *ItemUseConfig) GetUseValue() int32 {
	if x != nil {
		return x.UseValue
	}
	return 0
}

func (x *ItemUseConfig) GetUseCD() int32 {
	if x != nil {
		return x.UseCD
	}
	return 0
}

func (x *ItemUseConfig) GetIsEnable() int32 {
	if x != nil {
		return x.IsEnable
	}
	return 0
}

type ItemUseConfigAry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ary           []*ItemUseConfig       `protobuf:"bytes,1,rep,name=Ary,proto3" json:"Ary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemUseConfigAry) Reset() {
	*x = ItemUseConfigAry{}
	mi := &file_config_item_extra_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemUseConfigAry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemUseConfigAry) ProtoMessage() {}

func (x *ItemUseConfigAry) ProtoReflect() protoreflect.Message {
	mi := &file_config_item_extra_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemUseConfigAry.ProtoReflect.Descriptor instead.
func (*ItemUseConfigAry) Descriptor() ([]byte, []int) {
	return file_config_item_extra_proto_rawDescGZIP(), []int{3}
}

func (x *ItemUseConfigAry) GetAry() []*ItemUseConfig {
	if x != nil {
		return x.Ary
	}
	return nil
}

type DecomposeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	ItemId        int32                  `protobuf:"varint,2,opt,name=ItemId,proto3" json:"ItemId,omitempty"`
	OutputItemId  int32                  `protobuf:"varint,3,opt,name=OutputItemId,proto3" json:"OutputItemId,omitempty"`
	OutputCount   int32                  `protobuf:"varint,4,opt,name=OutputCount,proto3" json:"OutputCount,omitempty"`
	IsEnable      int32                  `protobuf:"varint,5,opt,name=IsEnable,proto3" json:"IsEnable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecomposeConfig) Reset() {
	*x = DecomposeConfig{}
	mi := &file_config_item_extra_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecomposeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecomposeConfig) ProtoMessage() {}

func (x *DecomposeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_item_extra_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecomposeConfig.ProtoReflect.Descriptor instead.
func (*DecomposeConfig) Descriptor() ([]byte, []int) {
	return file_config_item_extra_proto_rawDescGZIP(), []int{4}
}

func (x *DecomposeConfig) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DecomposeConfig) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *DecomposeConfig) GetOutputItemId() int32 {
	if x != nil {
		return x.OutputItemId
	}
	return 0
}

func (x *DecomposeConfig) GetOutputCount() int32 {
	if x != nil {
		return x.OutputCount
	}
	return 0
}

func (x *DecomposeConfig) GetIsEnable() int32 {
	if x != nil {
		return x.IsEnable
	}
	return 0
}

type DecomposeConfigAry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ary           []*DecomposeConfig     `protobuf:"bytes,1,rep,name=Ary,proto3" json:"Ary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecomposeConfigAry) Reset() {
	*x = DecomposeConfigAry{}
	mi := &file_config_item_extra_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecomposeConfigAry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecomposeConfigAry) ProtoMessage() {}

func (x *DecomposeConfigAry) ProtoReflect() protoreflect.Message {
	mi := &file_config_item_extra_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecomposeConfigAry.ProtoReflect.Descriptor instead.
func (*DecomposeConfigAry) Descriptor() ([]byte, []int) {
	return file_config_item_extra_proto_rawDescGZIP(), []int{5}
}

func (x *DecomposeConfigAry) GetAry() []*DecomposeConfig {
	if x != nil {
		return x.Ary
	}
	return nil
}

// DropGroupConfig 掉落组配置（双层模型：组→包→物品）
// Type: 0=叶子掉落包(dropRateMap的key直接当DropId产出), 1=组合包(key指向子组,递归解析)
// DropWay: 1=概率独立(万分比), 2=固定全掉, 3=权重选1
// DropType: 0=结果×N(一次选择后整体乘倍数), 1=选N次(独立执行N次)
type DropGroupConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groupid       int32                  `protobuf:"varint,1,opt,name=Groupid,proto3" json:"Groupid,omitempty"`
	Subid         int32                  `protobuf:"varint,2,opt,name=Subid,proto3" json:"Subid,omitempty"`
	DropGroupName string                 `protobuf:"bytes,3,opt,name=DropGroupName,proto3" json:"DropGroupName,omitempty"`
	DropWay       int32                  `protobuf:"varint,4,opt,name=DropWay,proto3" json:"DropWay,omitempty"`
	DropRateMap   map[int32]int32        `protobuf:"bytes,5,rep,name=DropRateMap,proto3" json:"DropRateMap,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	DropType      int32                  `protobuf:"varint,6,opt,name=DropType,proto3" json:"DropType,omitempty"`
	DropCount     int32                  `protobuf:"varint,7,opt,name=DropCount,proto3" json:"DropCount,omitempty"`
	Type          int32                  `protobuf:"varint,8,opt,name=Type,proto3" json:"Type,omitempty"`
	IsBan         int32                  `protobuf:"varint,9,opt,name=IsBan,proto3" json:"IsBan,omitempty"`
	Desc          string                 `protobuf:"bytes,10,opt,name=Desc,proto3" json:"Desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropGroupConfig) Reset() {
	*x = DropGroupConfig{}
	mi := &file_config_item_extra_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropGroupConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropGroupConfig) ProtoMessage() {}

func (x *DropGroupConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_item_extra_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropGroupConfig.ProtoReflect.Descriptor instead.
func (*DropGroupConfig) Descriptor() ([]byte, []int) {
	return file_config_item_extra_proto_rawDescGZIP(), []int{6}
}

func (x *DropGroupConfig) GetGroupid() int32 {
	if x != nil {
		return x.Groupid
	}
	return 0
}

func (x *DropGroupConfig) GetSubid() int32 {
	if x != nil {
		return x.Subid
	}
	return 0
}

func (x *DropGroupConfig) GetDropGroupName() string {
	if x != nil {
		return x.DropGroupName
	}
	return ""
}

func (x *DropGroupConfig) GetDropWay() int32 {
	if x != nil {
		return x.DropWay
	}
	return 0
}

func (x *DropGroupConfig) GetDropRateMap() map[int32]int32 {
	if x != nil {
		return x.DropRateMap
	}
	return nil
}

func (x *DropGroupConfig) GetDropType() int32 {
	if x != nil {
		return x.DropType
	}
	return 0
}

func (x *DropGroupConfig) GetDropCount() int32 {
	if x != nil {
		return x.DropCount
	}
	return 0
}

func (x *DropGroupConfig) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *DropGroupConfig) GetIsBan() int32 {
	if x != nil {
		return x.IsBan
	}
	return 0
}

func (x *DropGroupConfig) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type DropGroupConfigAry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ary           []*DropGroupConfig     `protobuf:"bytes,1,rep,name=Ary,proto3" json:"Ary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropGroupConfigAry) Reset() {
	*x = DropGroupConfigAry{}
	mi := &file_config_item_extra_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropGroupConfigAry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropGroupConfigAry) ProtoMessage() {}

func (x *DropGroupConfigAry) ProtoReflect() protoreflect.Message {
	mi := &file_config_item_extra_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropGroupConfigAry.ProtoReflect.Descriptor instead.
func (*DropGroupConfigAry) Descriptor() ([]byte, []int) {
	return file_config_item_extra_proto_rawDescGZIP(), []int{7}
}

func (x *DropGroupConfigAry) GetAry() []*DropGroupConfig {
	if x != nil {
		return x.Ary
	}
	return nil
}

// ObtainPolicyConfig 恭喜获得展示策略表（主键 Source 字符串）
// DisplayMode: 0=不展示 1=Tips 2=弹窗 3=结算
// MergeMode: 0=不合并 1=按 itemId 合并 2=按品质保留
type ObtainPolicyConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Source           string                 `protobuf:"bytes,1,opt,name=Source,proto3" json:"Source,omitempty"`
	DisplayMode      int32                  `protobuf:"varint,2,opt,name=DisplayMode,proto3" json:"DisplayMode,omitempty"`
	MergeMode        int32                  `protobuf:"varint,3,opt,name=MergeMode,proto3" json:"MergeMode,omitempty"`
	MinQuality       int32                  `protobuf:"varint,4,opt,name=MinQuality,proto3" json:"MinQuality,omitempty"`
	IncludeCurrency  int32                  `protobuf:"varint,5,opt,name=IncludeCurrency,proto3" json:"IncludeCurrency,omitempty"`
	MaxShowCount     int32                  `protobuf:"varint,6,opt,name=MaxShowCount,proto3" json:"MaxShowCount,omitempty"`
	RarePopupQuality int32                  `protobuf:"varint,7,opt,name=RarePopupQuality,proto3" json:"RarePopupQuality,omitempty"`
	CooldownMs       int32                  `protobuf:"varint,8,opt,name=CooldownMs,proto3" json:"CooldownMs,omitempty"`
	IsEnable         int32                  `protobuf:"varint,9,opt,name=IsEnable,proto3" json:"IsEnable,omitempty"`
	Desc             string                 `protobuf:"bytes,10,opt,name=Desc,proto3" json:"Desc,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ObtainPolicyConfig) Reset() {
	*x = ObtainPolicyConfig{}
	mi := &file_config_item_extra_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObtainPolicyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObtainPolicyConfig) ProtoMessage() {}

func (x *ObtainPolicyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_item_extra_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObtainPolicyConfig.ProtoReflect.Descriptor instead.
func (*ObtainPolicyConfig) Descriptor() ([]byte, []int) {
	return file_config_item_extra_proto_rawDescGZIP(), []int{8}
}

func (x *ObtainPolicyConfig) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ObtainPolicyConfig) GetDisplayMode() int32 {
	if x != nil {
		return x.DisplayMode
	}
	return 0
}

func (x *ObtainPolicyConfig) GetMergeMode() int32 {
	if x != nil {
		return x.MergeMode
	}
	return 0
}

func (x *ObtainPolicyConfig) GetMinQuality() int32 {
	if x != nil {
		return x.MinQuality
	}
	return 0
}

func (x *ObtainPolicyConfig) GetIncludeCurrency() int32 {
	if x != nil {
		return x.IncludeCurrency
	}
	return 0
}

func (x *ObtainPolicyConfig) GetMaxShowCount() int32 {
	if x != nil {
		return x.MaxShowCount
	}
	return 0
}

func (x *ObtainPolicyConfig) GetRarePopupQuality() int32 {
	if x != nil {
		return x.RarePopupQuality
	}
	return 0
}

func (x *ObtainPolicyConfig) GetCooldownMs() int32 {
	if x != nil {
		return x.CooldownMs
	}
	return 0
}

func (x *ObtainPolicyConfig) GetIsEnable() int32 {
	if x != nil {
		return x.IsEnable
	}
	return 0
}

func (x *ObtainPolicyConfig) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type ObtainPolicyConfigAry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ary           []*ObtainPolicyConfig  `protobuf:"bytes,1,rep,name=Ary,proto3" json:"Ary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObtainPolicyConfigAry) Reset() {
	*x = ObtainPolicyConfigAry{}
	mi := &file_config_item_extra_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObtainPolicyConfigAry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObtainPolicyConfigAry) ProtoMessage() {}

func (x *ObtainPolicyConfigAry) ProtoReflect() protoreflect.Message {
	mi := &file_config_item_extra_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObtainPolicyConfigAry.ProtoReflect.Descriptor instead.
func (*ObtainPolicyConfigAry) Descriptor() ([]byte, []int) {
	return file_config_item_extra_proto_rawDescGZIP(), []int{9}
}

func (x *ObtainPolicyConfigAry) GetAry() []*ObtainPolicyConfig {
	if x != nil {
		return x.Ary
	}
	return nil
}

// ItemRuleRefConfig 道具→规则引用表
// 独立于 ItemConfig，用于规避 ItemConfig 无法全量重编的限制。
// 业务通过 item_rule_ref_config.GetByItemId(itemId) 查 RuleId，再查 ItemRuleConfig。
type ItemRuleRefConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=ItemId,proto3" json:"ItemId,omitempty"`
	RuleId        int32                  `protobuf:"varint,2,opt,name=RuleId,proto3" json:"RuleId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemRuleRefConfig) Reset() {
	*x = ItemRuleRefConfig{}
	mi := &file_config_item_extra_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemRuleRefConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemRuleRefConfig) ProtoMessage() {}

func (x *ItemRuleRefConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_item_extra_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemRuleRefConfig.ProtoReflect.Descriptor instead.
func (*ItemRuleRefConfig) Descriptor() ([]byte, []int) {
	return file_config_item_extra_proto_rawDescGZIP(), []int{10}
}

func (x *ItemRuleRefConfig) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ItemRuleRefConfig) GetRuleId() int32 {
	if x != nil {
		return x.RuleId
	}
	return 0
}

type ItemRuleRefConfigAry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ary           []*ItemRuleRefConfig   `protobuf:"bytes,1,rep,name=Ary,proto3" json:"Ary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemRuleRefConfigAry) Reset() {
	*x = ItemRuleRefConfigAry{}
	mi := &file_config_item_extra_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemRuleRefConfigAry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemRuleRefConfigAry) ProtoMessage() {}

func (x *ItemRuleRefConfigAry) ProtoReflect() protoreflect.Message {
	mi := &file_config_item_extra_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemRuleRefConfigAry.ProtoReflect.Descriptor instead.
func (*ItemRuleRefConfigAry) Descriptor() ([]byte, []int) {
	return file_config_item_extra_proto_rawDescGZIP(), []int{11}
}

func (x *ItemRuleRefConfigAry) GetAry() []*ItemRuleRefConfig {
	if x != nil {
		return x.Ary
	}
	return nil
}

var File_config_item_extra_proto protoreflect.FileDescriptor

const file_config_item_extra_proto_rawDesc = "" +
	"\n" +
	"\x17config/item_extra.proto\x12\vg1.protocol\"\xde\x03\n" +
	"\x0eItemRuleConfig\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12 \n" +
	"\vCanExchange\x18\x03 \x01(\x05R\vCanExchange\x12\x16\n" +
	"\x06CanUse\x18\x04 \x01(\x05R\x06CanUse\x12 \n" +
	"\vMaxOwnCount\x18\x05 \x01(\x05R\vMaxOwnCount\x12\x1e\n" +
	"\n" +
	"MaxOverlay\x18\x06 \x01(\x05R\n" +
	"MaxOverlay\x12 \n" +
	"\vMaxUseCount\x18\a \x01(\x05R\vMaxUseCount\x12\"\n" +
	"\fMaxUseNumber\x18\b \x01(\x05R\fMaxUseNumber\x12,\n" +
	"\x11UseNumberInterval\x18\t \x01(\x05R\x11UseNumberInterval\x12\x16\n" +
	"\x06Getuse\x18\n" +
	" \x01(\x05R\x06Getuse\x12\"\n" +
	"\fCanDecompose\x18\v \x01(\x05R\fCanDecompose\x12\x1e\n" +
	"\n" +
	"CanRecycle\x18\f \x01(\x05R\n" +
	"CanRecycle\x12\x18\n" +
	"\aCanDrop\x18\r \x01(\x05R\aCanDrop\x12\x18\n" +
	"\aCanMail\x18\x0e \x01(\x05R\aCanMail\x12(\n" +
	"\x0fTradeLimitDaily\x18\x0f \x01(\x05R\x0fTradeLimitDaily\"B\n" +
	"\x11ItemRuleConfigAry\x12-\n" +
	"\x03Ary\x18\x01 \x03(\v2\x1b.g1.protocol.ItemRuleConfigR\x03Ary\"\x9d\x01\n" +
	"\rItemUseConfig\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x18\n" +
	"\aUseType\x18\x02 \x01(\x05R\aUseType\x12\x14\n" +
	"\x05UseId\x18\x03 \x01(\x05R\x05UseId\x12\x1a\n" +
	"\bUseValue\x18\x04 \x01(\x05R\bUseValue\x12\x14\n" +
	"\x05UseCD\x18\x05 \x01(\x05R\x05UseCD\x12\x1a\n" +
	"\bIsEnable\x18\x06 \x01(\x05R\bIsEnable\"@\n" +
	"\x10ItemUseConfigAry\x12,\n" +
	"\x03Ary\x18\x01 \x03(\v2\x1a.g1.protocol.ItemUseConfigR\x03Ary\"\x9b\x01\n" +
	"\x0fDecomposeConfig\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x16\n" +
	"\x06ItemId\x18\x02 \x01(\x05R\x06ItemId\x12\"\n" +
	"\fOutputItemId\x18\x03 \x01(\x05R\fOutputItemId\x12 \n" +
	"\vOutputCount\x18\x04 \x01(\x05R\vOutputCount\x12\x1a\n" +
	"\bIsEnable\x18\x05 \x01(\x05R\bIsEnable\"D\n" +
	"\x12DecomposeConfigAry\x12.\n" +
	"\x03Ary\x18\x01 \x03(\v2\x1c.g1.protocol.DecomposeConfigR\x03Ary\"\x8a\x03\n" +
	"\x0fDropGroupConfig\x12\x18\n" +
	"\aGroupid\x18\x01 \x01(\x05R\aGroupid\x12\x14\n" +
	"\x05Subid\x18\x02 \x01(\x05R\x05Subid\x12$\n" +
	"\rDropGroupName\x18\x03 \x01(\tR\rDropGroupName\x12\x18\n" +
	"\aDropWay\x18\x04 \x01(\x05R\aDropWay\x12O\n" +
	"\vDropRateMap\x18\x05 \x03(\v2-.g1.protocol.DropGroupConfig.DropRateMapEntryR\vDropRateMap\x12\x1a\n" +
	"\bDropType\x18\x06 \x01(\x05R\bDropType\x12\x1c\n" +
	"\tDropCount\x18\a \x01(\x05R\tDropCount\x12\x12\n" +
	"\x04Type\x18\b \x01(\x05R\x04Type\x12\x14\n" +
	"\x05IsBan\x18\t \x01(\x05R\x05IsBan\x12\x12\n" +
	"\x04Desc\x18\n" +
	" \x01(\tR\x04Desc\x1a>\n" +
	"\x10DropRateMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"D\n" +
	"\x12DropGroupConfigAry\x12.\n" +
	"\x03Ary\x18\x01 \x03(\v2\x1c.g1.protocol.DropGroupConfigR\x03Ary\"\xd6\x02\n" +
	"\x12ObtainPolicyConfig\x12\x16\n" +
	"\x06Source\x18\x01 \x01(\tR\x06Source\x12 \n" +
	"\vDisplayMode\x18\x02 \x01(\x05R\vDisplayMode\x12\x1c\n" +
	"\tMergeMode\x18\x03 \x01(\x05R\tMergeMode\x12\x1e\n" +
	"\n" +
	"MinQuality\x18\x04 \x01(\x05R\n" +
	"MinQuality\x12(\n" +
	"\x0fIncludeCurrency\x18\x05 \x01(\x05R\x0fIncludeCurrency\x12\"\n" +
	"\fMaxShowCount\x18\x06 \x01(\x05R\fMaxShowCount\x12*\n" +
	"\x10RarePopupQuality\x18\a \x01(\x05R\x10RarePopupQuality\x12\x1e\n" +
	"\n" +
	"CooldownMs\x18\b \x01(\x05R\n" +
	"CooldownMs\x12\x1a\n" +
	"\bIsEnable\x18\t \x01(\x05R\bIsEnable\x12\x12\n" +
	"\x04Desc\x18\n" +
	" \x01(\tR\x04Desc\"J\n" +
	"\x15ObtainPolicyConfigAry\x121\n" +
	"\x03Ary\x18\x01 \x03(\v2\x1f.g1.protocol.ObtainPolicyConfigR\x03Ary\"C\n" +
	"\x11ItemRuleRefConfig\x12\x16\n" +
	"\x06ItemId\x18\x01 \x01(\x05R\x06ItemId\x12\x16\n" +
	"\x06RuleId\x18\x02 \x01(\x05R\x06RuleId\"H\n" +
	"\x14ItemRuleRefConfigAry\x120\n" +
	"\x03Ary\x18\x01 \x03(\v2\x1e.g1.protocol.ItemRuleRefConfigR\x03AryB\x0fZ\r./g1_protocolb\x06proto3"

var (
	file_config_item_extra_proto_rawDescOnce sync.Once
	file_config_item_extra_proto_rawDescData []byte
)

func file_config_item_extra_proto_rawDescGZIP() []byte {
	file_config_item_extra_proto_rawDescOnce.Do(func() {
		file_config_item_extra_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_item_extra_proto_rawDesc), len(file_config_item_extra_proto_rawDesc)))
	})
	return file_config_item_extra_proto_rawDescData
}

var file_config_item_extra_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_config_item_extra_proto_goTypes = []any{
	(*ItemRuleConfig)(nil),        // 0: g1.protocol.ItemRuleConfig
	(*ItemRuleConfigAry)(nil),     // 1: g1.protocol.ItemRuleConfigAry
	(*ItemUseConfig)(nil),         // 2: g1.protocol.ItemUseConfig
	(*ItemUseConfigAry)(nil),      // 3: g1.protocol.ItemUseConfigAry
	(*DecomposeConfig)(nil),       // 4: g1.protocol.DecomposeConfig
	(*DecomposeConfigAry)(nil),    // 5: g1.protocol.DecomposeConfigAry
	(*DropGroupConfig)(nil),       // 6: g1.protocol.DropGroupConfig
	(*DropGroupConfigAry)(nil),    // 7: g1.protocol.DropGroupConfigAry
	(*ObtainPolicyConfig)(nil),    // 8: g1.protocol.ObtainPolicyConfig
	(*ObtainPolicyConfigAry)(nil), // 9: g1.protocol.ObtainPolicyConfigAry
	(*ItemRuleRefConfig)(nil),     // 10: g1.protocol.ItemRuleRefConfig
	(*ItemRuleRefConfigAry)(nil),  // 11: g1.protocol.ItemRuleRefConfigAry
	nil,                           // 12: g1.protocol.DropGroupConfig.DropRateMapEntry
}
var file_config_item_extra_proto_depIdxs = []int32{
	0,  // 0: g1.protocol.ItemRuleConfigAry.Ary:type_name -> g1.protocol.ItemRuleConfig
	2,  // 1: g1.protocol.ItemUseConfigAry.Ary:type_name -> g1.protocol.ItemUseConfig
	4,  // 2: g1.protocol.DecomposeConfigAry.Ary:type_name -> g1.protocol.DecomposeConfig
	12, // 3: g1.protocol.DropGroupConfig.DropRateMap:type_name -> g1.protocol.DropGroupConfig.DropRateMapEntry
	6,  // 4: g1.protocol.DropGroupConfigAry.Ary:type_name -> g1.protocol.DropGroupConfig
	8,  // 5: g1.protocol.ObtainPolicyConfigAry.Ary:type_name -> g1.protocol.ObtainPolicyConfig
	10, // 6: g1.protocol.ItemRuleRefConfigAry.Ary:type_name -> g1.protocol.ItemRuleRefConfig
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_config_item_extra_proto_init() }
func file_config_item_extra_proto_init() {
	if File_config_item_extra_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_item_extra_proto_rawDesc), len(file_config_item_extra_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_item_extra_proto_goTypes,
		DependencyIndexes: file_config_item_extra_proto_depIdxs,
		MessageInfos:      file_config_item_extra_proto_msgTypes,
	}.Build()
	File_config_item_extra_proto = out.File
	file_config_item_extra_proto_goTypes = nil
	file_config_item_extra_proto_depIdxs = nil
}
