//
// 本代码由xlsx工具生成，请勿手动修改

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: config/mall.proto

package g1_protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MallConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`                        // id
	Type          int32                  `protobuf:"varint,2,opt,name=Type,proto3" json:"Type,omitempty"`                    // 商品类型
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`                     // 礼包名称
	PackageID     int32                  `protobuf:"varint,4,opt,name=PackageID,proto3" json:"PackageID,omitempty"`          // 礼包ID
	CostItemID    int32                  `protobuf:"varint,5,opt,name=CostItemID,proto3" json:"CostItemID,omitempty"`        // 购买货币ID
	CostItemCnt   int32                  `protobuf:"varint,6,opt,name=CostItemCnt,proto3" json:"CostItemCnt,omitempty"`      // 购买货币数量
	BeginTime     string                 `protobuf:"bytes,7,opt,name=BeginTime,proto3" json:"BeginTime,omitempty"`           // 限时开始时间
	EndTime       string                 `protobuf:"bytes,8,opt,name=EndTime,proto3" json:"EndTime,omitempty"`               // 限时结束时间
	BuyLimit      int32                  `protobuf:"varint,9,opt,name=BuyLimit,proto3" json:"BuyLimit,omitempty"`            // 限购次数
	DailyBuyLimit int32                  `protobuf:"varint,10,opt,name=DailyBuyLimit,proto3" json:"DailyBuyLimit,omitempty"` // 每日限购次数
	Lable         int32                  `protobuf:"varint,11,opt,name=Lable,proto3" json:"Lable,omitempty"`                 // 标签
	Rmb           int32                  `protobuf:"varint,12,opt,name=Rmb,proto3" json:"Rmb,omitempty"`                     // 对应充值表ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MallConfig) Reset() {
	*x = MallConfig{}
	mi := &file_config_mall_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MallConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MallConfig) ProtoMessage() {}

func (x *MallConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_mall_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MallConfig.ProtoReflect.Descriptor instead.
func (*MallConfig) Descriptor() ([]byte, []int) {
	return file_config_mall_proto_rawDescGZIP(), []int{0}
}

func (x *MallConfig) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MallConfig) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *MallConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MallConfig) GetPackageID() int32 {
	if x != nil {
		return x.PackageID
	}
	return 0
}

func (x *MallConfig) GetCostItemID() int32 {
	if x != nil {
		return x.CostItemID
	}
	return 0
}

func (x *MallConfig) GetCostItemCnt() int32 {
	if x != nil {
		return x.CostItemCnt
	}
	return 0
}

func (x *MallConfig) GetBeginTime() string {
	if x != nil {
		return x.BeginTime
	}
	return ""
}

func (x *MallConfig) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *MallConfig) GetBuyLimit() int32 {
	if x != nil {
		return x.BuyLimit
	}
	return 0
}

func (x *MallConfig) GetDailyBuyLimit() int32 {
	if x != nil {
		return x.DailyBuyLimit
	}
	return 0
}

func (x *MallConfig) GetLable() int32 {
	if x != nil {
		return x.Lable
	}
	return 0
}

func (x *MallConfig) GetRmb() int32 {
	if x != nil {
		return x.Rmb
	}
	return 0
}

type MallConfigAry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ary           []*MallConfig          `protobuf:"bytes,1,rep,name=Ary,proto3" json:"Ary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MallConfigAry) Reset() {
	*x = MallConfigAry{}
	mi := &file_config_mall_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MallConfigAry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MallConfigAry) ProtoMessage() {}

func (x *MallConfigAry) ProtoReflect() protoreflect.Message {
	mi := &file_config_mall_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MallConfigAry.ProtoReflect.Descriptor instead.
func (*MallConfigAry) Descriptor() ([]byte, []int) {
	return file_config_mall_proto_rawDescGZIP(), []int{1}
}

func (x *MallConfigAry) GetAry() []*MallConfig {
	if x != nil {
		return x.Ary
	}
	return nil
}

var File_config_mall_proto protoreflect.FileDescriptor

const file_config_mall_proto_rawDesc = "" +
	"\n" +
	"\x11config/mall.proto\x12\vg1.protocol\"\xc6\x02\n" +
	"\n" +
	"MallConfig\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x05R\x02Id\x12\x12\n" +
	"\x04Type\x18\x02 \x01(\x05R\x04Type\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12\x1c\n" +
	"\tPackageID\x18\x04 \x01(\x05R\tPackageID\x12\x1e\n" +
	"\n" +
	"CostItemID\x18\x05 \x01(\x05R\n" +
	"CostItemID\x12 \n" +
	"\vCostItemCnt\x18\x06 \x01(\x05R\vCostItemCnt\x12\x1c\n" +
	"\tBeginTime\x18\a \x01(\tR\tBeginTime\x12\x18\n" +
	"\aEndTime\x18\b \x01(\tR\aEndTime\x12\x1a\n" +
	"\bBuyLimit\x18\t \x01(\x05R\bBuyLimit\x12$\n" +
	"\rDailyBuyLimit\x18\n" +
	" \x01(\x05R\rDailyBuyLimit\x12\x14\n" +
	"\x05Lable\x18\v \x01(\x05R\x05Lable\x12\x10\n" +
	"\x03Rmb\x18\f \x01(\x05R\x03Rmb\":\n" +
	"\rMallConfigAry\x12)\n" +
	"\x03Ary\x18\x01 \x03(\v2\x17.g1.protocol.MallConfigR\x03AryB9Z7github.com/Iori372552686/g1_common/protocol;g1_protocolb\x06proto3"

var (
	file_config_mall_proto_rawDescOnce sync.Once
	file_config_mall_proto_rawDescData []byte
)

func file_config_mall_proto_rawDescGZIP() []byte {
	file_config_mall_proto_rawDescOnce.Do(func() {
		file_config_mall_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_mall_proto_rawDesc), len(file_config_mall_proto_rawDesc)))
	})
	return file_config_mall_proto_rawDescData
}

var file_config_mall_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_config_mall_proto_goTypes = []any{
	(*MallConfig)(nil),    // 0: g1.protocol.MallConfig
	(*MallConfigAry)(nil), // 1: g1.protocol.MallConfigAry
}
var file_config_mall_proto_depIdxs = []int32{
	0, // 0: g1.protocol.MallConfigAry.Ary:type_name -> g1.protocol.MallConfig
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_config_mall_proto_init() }
func file_config_mall_proto_init() {
	if File_config_mall_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_mall_proto_rawDesc), len(file_config_mall_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_mall_proto_goTypes,
		DependencyIndexes: file_config_mall_proto_depIdxs,
		MessageInfos:      file_config_mall_proto_msgTypes,
	}.Build()
	File_config_mall_proto = out.File
	file_config_mall_proto_goTypes = nil
	file_config_mall_proto_depIdxs = nil
}
