// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: service/mysqlsvr.proto

package g1_protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EMysqlType int32

const (
	EMysqlType__MYSQL_TYPE_NONE     EMysqlType = 0
	EMysqlType_MYSQL_TYPE_ROLE_INFO EMysqlType = 1 //    MYSQL_TYPE_ROLE_DATA = 116;
)

// Enum value maps for EMysqlType.
var (
	EMysqlType_name = map[int32]string{
		0: "_MYSQL_TYPE_NONE",
		1: "MYSQL_TYPE_ROLE_INFO",
	}
	EMysqlType_value = map[string]int32{
		"_MYSQL_TYPE_NONE":     0,
		"MYSQL_TYPE_ROLE_INFO": 1,
	}
)

func (x EMysqlType) Enum() *EMysqlType {
	p := new(EMysqlType)
	*p = x
	return p
}

func (x EMysqlType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EMysqlType) Descriptor() protoreflect.EnumDescriptor {
	return file_service_mysqlsvr_proto_enumTypes[0].Descriptor()
}

func (EMysqlType) Type() protoreflect.EnumType {
	return &file_service_mysqlsvr_proto_enumTypes[0]
}

func (x EMysqlType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EMysqlType.Descriptor instead.
func (EMysqlType) EnumDescriptor() ([]byte, []int) {
	return file_service_mysqlsvr_proto_rawDescGZIP(), []int{0}
}

// MYSQL_INNER_UPDATE_ROLE_INFO_REQ
type MysqlInnerUpdateRoleInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MysqlInnerUpdateRoleInfoReq) Reset() {
	*x = MysqlInnerUpdateRoleInfoReq{}
	mi := &file_service_mysqlsvr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MysqlInnerUpdateRoleInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MysqlInnerUpdateRoleInfoReq) ProtoMessage() {}

func (x *MysqlInnerUpdateRoleInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_mysqlsvr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MysqlInnerUpdateRoleInfoReq.ProtoReflect.Descriptor instead.
func (*MysqlInnerUpdateRoleInfoReq) Descriptor() ([]byte, []int) {
	return file_service_mysqlsvr_proto_rawDescGZIP(), []int{0}
}

func (x *MysqlInnerUpdateRoleInfoReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MysqlInnerUpdateRoleInfoRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           *Ret                   `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MysqlInnerUpdateRoleInfoRsp) Reset() {
	*x = MysqlInnerUpdateRoleInfoRsp{}
	mi := &file_service_mysqlsvr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MysqlInnerUpdateRoleInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MysqlInnerUpdateRoleInfoRsp) ProtoMessage() {}

func (x *MysqlInnerUpdateRoleInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_mysqlsvr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MysqlInnerUpdateRoleInfoRsp.ProtoReflect.Descriptor instead.
func (*MysqlInnerUpdateRoleInfoRsp) Descriptor() ([]byte, []int) {
	return file_service_mysqlsvr_proto_rawDescGZIP(), []int{1}
}

func (x *MysqlInnerUpdateRoleInfoRsp) GetRet() *Ret {
	if x != nil {
		return x.Ret
	}
	return nil
}

// MYSQL_INNER_SEARCH_ROLE_REQ
type MysqlInnerSearchRoleReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SearchString  string                 `protobuf:"bytes,1,opt,name=search_string,json=searchString,proto3" json:"search_string,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MysqlInnerSearchRoleReq) Reset() {
	*x = MysqlInnerSearchRoleReq{}
	mi := &file_service_mysqlsvr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MysqlInnerSearchRoleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MysqlInnerSearchRoleReq) ProtoMessage() {}

func (x *MysqlInnerSearchRoleReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_mysqlsvr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MysqlInnerSearchRoleReq.ProtoReflect.Descriptor instead.
func (*MysqlInnerSearchRoleReq) Descriptor() ([]byte, []int) {
	return file_service_mysqlsvr_proto_rawDescGZIP(), []int{2}
}

func (x *MysqlInnerSearchRoleReq) GetSearchString() string {
	if x != nil {
		return x.SearchString
	}
	return ""
}

type MysqlInnerSearchRoleRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           *Ret                   `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Uid           uint64                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MysqlInnerSearchRoleRsp) Reset() {
	*x = MysqlInnerSearchRoleRsp{}
	mi := &file_service_mysqlsvr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MysqlInnerSearchRoleRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MysqlInnerSearchRoleRsp) ProtoMessage() {}

func (x *MysqlInnerSearchRoleRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_mysqlsvr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MysqlInnerSearchRoleRsp.ProtoReflect.Descriptor instead.
func (*MysqlInnerSearchRoleRsp) Descriptor() ([]byte, []int) {
	return file_service_mysqlsvr_proto_rawDescGZIP(), []int{3}
}

func (x *MysqlInnerSearchRoleRsp) GetRet() *Ret {
	if x != nil {
		return x.Ret
	}
	return nil
}

func (x *MysqlInnerSearchRoleRsp) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

// MYSQL_INNER_SAVE_ROLE_DATA_REQ — L3 全量快照写回（mainsvr 双写的异步落库路径）
type MysqlInnerSaveRoleDataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                                // RoleInfo 整包序列化（ConnSvrInfo 已清空）
	UpdateTime    int64                  `protobuf:"varint,3,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"` // 服务器时钟 ms，陈旧写守卫用
	IgnoreRsp     bool                   `protobuf:"varint,4,opt,name=ignore_rsp,json=ignoreRsp,proto3" json:"ignore_rsp,omitempty"`    // 运行期异步投递时不等 rsp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MysqlInnerSaveRoleDataReq) Reset() {
	*x = MysqlInnerSaveRoleDataReq{}
	mi := &file_service_mysqlsvr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MysqlInnerSaveRoleDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MysqlInnerSaveRoleDataReq) ProtoMessage() {}

func (x *MysqlInnerSaveRoleDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_mysqlsvr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MysqlInnerSaveRoleDataReq.ProtoReflect.Descriptor instead.
func (*MysqlInnerSaveRoleDataReq) Descriptor() ([]byte, []int) {
	return file_service_mysqlsvr_proto_rawDescGZIP(), []int{4}
}

func (x *MysqlInnerSaveRoleDataReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *MysqlInnerSaveRoleDataReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MysqlInnerSaveRoleDataReq) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *MysqlInnerSaveRoleDataReq) GetIgnoreRsp() bool {
	if x != nil {
		return x.IgnoreRsp
	}
	return false
}

type MysqlInnerSaveRoleDataRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           *Ret                   `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MysqlInnerSaveRoleDataRsp) Reset() {
	*x = MysqlInnerSaveRoleDataRsp{}
	mi := &file_service_mysqlsvr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MysqlInnerSaveRoleDataRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MysqlInnerSaveRoleDataRsp) ProtoMessage() {}

func (x *MysqlInnerSaveRoleDataRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_mysqlsvr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MysqlInnerSaveRoleDataRsp.ProtoReflect.Descriptor instead.
func (*MysqlInnerSaveRoleDataRsp) Descriptor() ([]byte, []int) {
	return file_service_mysqlsvr_proto_rawDescGZIP(), []int{5}
}

func (x *MysqlInnerSaveRoleDataRsp) GetRet() *Ret {
	if x != nil {
		return x.Ret
	}
	return nil
}

// MYSQL_INNER_LOAD_ROLE_DATA_REQ — L2 miss 时的回源读（冷登录路径）
type MysqlInnerLoadRoleDataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MysqlInnerLoadRoleDataReq) Reset() {
	*x = MysqlInnerLoadRoleDataReq{}
	mi := &file_service_mysqlsvr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MysqlInnerLoadRoleDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MysqlInnerLoadRoleDataReq) ProtoMessage() {}

func (x *MysqlInnerLoadRoleDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_mysqlsvr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MysqlInnerLoadRoleDataReq.ProtoReflect.Descriptor instead.
func (*MysqlInnerLoadRoleDataReq) Descriptor() ([]byte, []int) {
	return file_service_mysqlsvr_proto_rawDescGZIP(), []int{6}
}

func (x *MysqlInnerLoadRoleDataReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type MysqlInnerLoadRoleDataRsp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ret           *Ret                   `protobuf:"bytes,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` // 命中时为 RoleInfo 整包序列化，miss 时为空
	UpdateTime    int64                  `protobuf:"varint,3,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MysqlInnerLoadRoleDataRsp) Reset() {
	*x = MysqlInnerLoadRoleDataRsp{}
	mi := &file_service_mysqlsvr_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MysqlInnerLoadRoleDataRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MysqlInnerLoadRoleDataRsp) ProtoMessage() {}

func (x *MysqlInnerLoadRoleDataRsp) ProtoReflect() protoreflect.Message {
	mi := &file_service_mysqlsvr_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MysqlInnerLoadRoleDataRsp.ProtoReflect.Descriptor instead.
func (*MysqlInnerLoadRoleDataRsp) Descriptor() ([]byte, []int) {
	return file_service_mysqlsvr_proto_rawDescGZIP(), []int{7}
}

func (x *MysqlInnerLoadRoleDataRsp) GetRet() *Ret {
	if x != nil {
		return x.Ret
	}
	return nil
}

func (x *MysqlInnerLoadRoleDataRsp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MysqlInnerLoadRoleDataRsp) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

var File_service_mysqlsvr_proto protoreflect.FileDescriptor

const file_service_mysqlsvr_proto_rawDesc = "" +
	"\n" +
	"\x16service/mysqlsvr.proto\x12\vg1.protocol\x1a\x11core/common.proto\"1\n" +
	"\x1bMysqlInnerUpdateRoleInfoReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"A\n" +
	"\x1bMysqlInnerUpdateRoleInfoRsp\x12\"\n" +
	"\x03ret\x18\x01 \x01(\v2\x10.g1.protocol.RetR\x03ret\">\n" +
	"\x17MysqlInnerSearchRoleReq\x12#\n" +
	"\rsearch_string\x18\x01 \x01(\tR\fsearchString\"O\n" +
	"\x17MysqlInnerSearchRoleRsp\x12\"\n" +
	"\x03ret\x18\x01 \x01(\v2\x10.g1.protocol.RetR\x03ret\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uid\"\x81\x01\n" +
	"\x19MysqlInnerSaveRoleDataReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1f\n" +
	"\vupdate_time\x18\x03 \x01(\x03R\n" +
	"updateTime\x12\x1d\n" +
	"\n" +
	"ignore_rsp\x18\x04 \x01(\bR\tignoreRsp\"?\n" +
	"\x19MysqlInnerSaveRoleDataRsp\x12\"\n" +
	"\x03ret\x18\x01 \x01(\v2\x10.g1.protocol.RetR\x03ret\"-\n" +
	"\x19MysqlInnerLoadRoleDataReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\"t\n" +
	"\x19MysqlInnerLoadRoleDataRsp\x12\"\n" +
	"\x03ret\x18\x01 \x01(\v2\x10.g1.protocol.RetR\x03ret\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1f\n" +
	"\vupdate_time\x18\x03 \x01(\x03R\n" +
	"updateTime*<\n" +
	"\n" +
	"EMysqlType\x12\x14\n" +
	"\x10_MYSQL_TYPE_NONE\x10\x00\x12\x18\n" +
	"\x14MYSQL_TYPE_ROLE_INFO\x10\x01B9Z7github.com/Iori372552686/g1_common/protocol;g1_protocolb\x06proto3"

var (
	file_service_mysqlsvr_proto_rawDescOnce sync.Once
	file_service_mysqlsvr_proto_rawDescData []byte
)

func file_service_mysqlsvr_proto_rawDescGZIP() []byte {
	file_service_mysqlsvr_proto_rawDescOnce.Do(func() {
		file_service_mysqlsvr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_mysqlsvr_proto_rawDesc), len(file_service_mysqlsvr_proto_rawDesc)))
	})
	return file_service_mysqlsvr_proto_rawDescData
}

var file_service_mysqlsvr_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_service_mysqlsvr_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_service_mysqlsvr_proto_goTypes = []any{
	(EMysqlType)(0),                     // 0: g1.protocol.EMysqlType
	(*MysqlInnerUpdateRoleInfoReq)(nil), // 1: g1.protocol.MysqlInnerUpdateRoleInfoReq
	(*MysqlInnerUpdateRoleInfoRsp)(nil), // 2: g1.protocol.MysqlInnerUpdateRoleInfoRsp
	(*MysqlInnerSearchRoleReq)(nil),     // 3: g1.protocol.MysqlInnerSearchRoleReq
	(*MysqlInnerSearchRoleRsp)(nil),     // 4: g1.protocol.MysqlInnerSearchRoleRsp
	(*MysqlInnerSaveRoleDataReq)(nil),   // 5: g1.protocol.MysqlInnerSaveRoleDataReq
	(*MysqlInnerSaveRoleDataRsp)(nil),   // 6: g1.protocol.MysqlInnerSaveRoleDataRsp
	(*MysqlInnerLoadRoleDataReq)(nil),   // 7: g1.protocol.MysqlInnerLoadRoleDataReq
	(*MysqlInnerLoadRoleDataRsp)(nil),   // 8: g1.protocol.MysqlInnerLoadRoleDataRsp
	(*Ret)(nil),                         // 9: g1.protocol.Ret
}
var file_service_mysqlsvr_proto_depIdxs = []int32{
	9, // 0: g1.protocol.MysqlInnerUpdateRoleInfoRsp.ret:type_name -> g1.protocol.Ret
	9, // 1: g1.protocol.MysqlInnerSearchRoleRsp.ret:type_name -> g1.protocol.Ret
	9, // 2: g1.protocol.MysqlInnerSaveRoleDataRsp.ret:type_name -> g1.protocol.Ret
	9, // 3: g1.protocol.MysqlInnerLoadRoleDataRsp.ret:type_name -> g1.protocol.Ret
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_service_mysqlsvr_proto_init() }
func file_service_mysqlsvr_proto_init() {
	if File_service_mysqlsvr_proto != nil {
		return
	}
	file_core_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_mysqlsvr_proto_rawDesc), len(file_service_mysqlsvr_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_service_mysqlsvr_proto_goTypes,
		DependencyIndexes: file_service_mysqlsvr_proto_depIdxs,
		EnumInfos:         file_service_mysqlsvr_proto_enumTypes,
		MessageInfos:      file_service_mysqlsvr_proto_msgTypes,
	}.Build()
	File_service_mysqlsvr_proto = out.File
	file_service_mysqlsvr_proto_goTypes = nil
	file_service_mysqlsvr_proto_depIdxs = nil
}
