//
// 本代码由xlsx工具生成，请勿手动修改

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: config/obtain.proto

package g1_protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObtainPolicyConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Source           string                 `protobuf:"bytes,1,opt,name=Source,proto3" json:"Source,omitempty"`                      // 来源标识
	DisplayMode      int32                  `protobuf:"varint,2,opt,name=DisplayMode,proto3" json:"DisplayMode,omitempty"`           // 展示模式
	MergeMode        int32                  `protobuf:"varint,3,opt,name=MergeMode,proto3" json:"MergeMode,omitempty"`               // 合并模式
	MinQuality       int32                  `protobuf:"varint,4,opt,name=MinQuality,proto3" json:"MinQuality,omitempty"`             // 最低品质
	IncludeCurrency  int32                  `protobuf:"varint,5,opt,name=IncludeCurrency,proto3" json:"IncludeCurrency,omitempty"`   // 含货币
	MaxShowCount     int32                  `protobuf:"varint,6,opt,name=MaxShowCount,proto3" json:"MaxShowCount,omitempty"`         // 最大展示数
	RarePopupQuality int32                  `protobuf:"varint,7,opt,name=RarePopupQuality,proto3" json:"RarePopupQuality,omitempty"` // 稀有弹窗品质
	CooldownMs       int32                  `protobuf:"varint,8,opt,name=CooldownMs,proto3" json:"CooldownMs,omitempty"`             // 冷却毫秒
	IsEnable         int32                  `protobuf:"varint,9,opt,name=IsEnable,proto3" json:"IsEnable,omitempty"`                 // 是否启用
	Desc             string                 `protobuf:"bytes,10,opt,name=Desc,proto3" json:"Desc,omitempty"`                         // 描述
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ObtainPolicyConfig) Reset() {
	*x = ObtainPolicyConfig{}
	mi := &file_config_obtain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObtainPolicyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObtainPolicyConfig) ProtoMessage() {}

func (x *ObtainPolicyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_obtain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObtainPolicyConfig.ProtoReflect.Descriptor instead.
func (*ObtainPolicyConfig) Descriptor() ([]byte, []int) {
	return file_config_obtain_proto_rawDescGZIP(), []int{0}
}

func (x *ObtainPolicyConfig) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ObtainPolicyConfig) GetDisplayMode() int32 {
	if x != nil {
		return x.DisplayMode
	}
	return 0
}

func (x *ObtainPolicyConfig) GetMergeMode() int32 {
	if x != nil {
		return x.MergeMode
	}
	return 0
}

func (x *ObtainPolicyConfig) GetMinQuality() int32 {
	if x != nil {
		return x.MinQuality
	}
	return 0
}

func (x *ObtainPolicyConfig) GetIncludeCurrency() int32 {
	if x != nil {
		return x.IncludeCurrency
	}
	return 0
}

func (x *ObtainPolicyConfig) GetMaxShowCount() int32 {
	if x != nil {
		return x.MaxShowCount
	}
	return 0
}

func (x *ObtainPolicyConfig) GetRarePopupQuality() int32 {
	if x != nil {
		return x.RarePopupQuality
	}
	return 0
}

func (x *ObtainPolicyConfig) GetCooldownMs() int32 {
	if x != nil {
		return x.CooldownMs
	}
	return 0
}

func (x *ObtainPolicyConfig) GetIsEnable() int32 {
	if x != nil {
		return x.IsEnable
	}
	return 0
}

func (x *ObtainPolicyConfig) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type ObtainPolicyConfigAry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ary           []*ObtainPolicyConfig  `protobuf:"bytes,1,rep,name=Ary,proto3" json:"Ary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObtainPolicyConfigAry) Reset() {
	*x = ObtainPolicyConfigAry{}
	mi := &file_config_obtain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObtainPolicyConfigAry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObtainPolicyConfigAry) ProtoMessage() {}

func (x *ObtainPolicyConfigAry) ProtoReflect() protoreflect.Message {
	mi := &file_config_obtain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObtainPolicyConfigAry.ProtoReflect.Descriptor instead.
func (*ObtainPolicyConfigAry) Descriptor() ([]byte, []int) {
	return file_config_obtain_proto_rawDescGZIP(), []int{1}
}

func (x *ObtainPolicyConfigAry) GetAry() []*ObtainPolicyConfig {
	if x != nil {
		return x.Ary
	}
	return nil
}

var File_config_obtain_proto protoreflect.FileDescriptor

const file_config_obtain_proto_rawDesc = "" +
	"\n" +
	"\x13config/obtain.proto\x12\vg1.protocol\"\xd6\x02\n" +
	"\x12ObtainPolicyConfig\x12\x16\n" +
	"\x06Source\x18\x01 \x01(\tR\x06Source\x12 \n" +
	"\vDisplayMode\x18\x02 \x01(\x05R\vDisplayMode\x12\x1c\n" +
	"\tMergeMode\x18\x03 \x01(\x05R\tMergeMode\x12\x1e\n" +
	"\n" +
	"MinQuality\x18\x04 \x01(\x05R\n" +
	"MinQuality\x12(\n" +
	"\x0fIncludeCurrency\x18\x05 \x01(\x05R\x0fIncludeCurrency\x12\"\n" +
	"\fMaxShowCount\x18\x06 \x01(\x05R\fMaxShowCount\x12*\n" +
	"\x10RarePopupQuality\x18\a \x01(\x05R\x10RarePopupQuality\x12\x1e\n" +
	"\n" +
	"CooldownMs\x18\b \x01(\x05R\n" +
	"CooldownMs\x12\x1a\n" +
	"\bIsEnable\x18\t \x01(\x05R\bIsEnable\x12\x12\n" +
	"\x04Desc\x18\n" +
	" \x01(\tR\x04Desc\"J\n" +
	"\x15ObtainPolicyConfigAry\x121\n" +
	"\x03Ary\x18\x01 \x03(\v2\x1f.g1.protocol.ObtainPolicyConfigR\x03AryB9Z7github.com/Iori372552686/g1_common/protocol;g1_protocolb\x06proto3"

var (
	file_config_obtain_proto_rawDescOnce sync.Once
	file_config_obtain_proto_rawDescData []byte
)

func file_config_obtain_proto_rawDescGZIP() []byte {
	file_config_obtain_proto_rawDescOnce.Do(func() {
		file_config_obtain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_obtain_proto_rawDesc), len(file_config_obtain_proto_rawDesc)))
	})
	return file_config_obtain_proto_rawDescData
}

var file_config_obtain_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_config_obtain_proto_goTypes = []any{
	(*ObtainPolicyConfig)(nil),    // 0: g1.protocol.ObtainPolicyConfig
	(*ObtainPolicyConfigAry)(nil), // 1: g1.protocol.ObtainPolicyConfigAry
}
var file_config_obtain_proto_depIdxs = []int32{
	0, // 0: g1.protocol.ObtainPolicyConfigAry.Ary:type_name -> g1.protocol.ObtainPolicyConfig
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_config_obtain_proto_init() }
func file_config_obtain_proto_init() {
	if File_config_obtain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_obtain_proto_rawDesc), len(file_config_obtain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_obtain_proto_goTypes,
		DependencyIndexes: file_config_obtain_proto_depIdxs,
		MessageInfos:      file_config_obtain_proto_msgTypes,
	}.Build()
	File_config_obtain_proto = out.File
	file_config_obtain_proto_goTypes = nil
	file_config_obtain_proto_depIdxs = nil
}
