// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: core/role.proto

package g1_protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleRegisterInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Uid              uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	RegisterTime     int32                  `protobuf:"varint,2,opt,name=register_time,json=registerTime,proto3" json:"register_time,omitempty"`
	Zone             int32                  `protobuf:"varint,3,opt,name=zone,proto3" json:"zone,omitempty"`
	TimeOffsetMinute int32                  `protobuf:"varint,4,opt,name=time_offset_minute,json=timeOffsetMinute,proto3" json:"time_offset_minute,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RoleRegisterInfo) Reset() {
	*x = RoleRegisterInfo{}
	mi := &file_core_role_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleRegisterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleRegisterInfo) ProtoMessage() {}

func (x *RoleRegisterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_role_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleRegisterInfo.ProtoReflect.Descriptor instead.
func (*RoleRegisterInfo) Descriptor() ([]byte, []int) {
	return file_core_role_proto_rawDescGZIP(), []int{0}
}

func (x *RoleRegisterInfo) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *RoleRegisterInfo) GetRegisterTime() int32 {
	if x != nil {
		return x.RegisterTime
	}
	return 0
}

func (x *RoleRegisterInfo) GetZone() int32 {
	if x != nil {
		return x.Zone
	}
	return 0
}

func (x *RoleRegisterInfo) GetTimeOffsetMinute() int32 {
	if x != nil {
		return x.TimeOffsetMinute
	}
	return 0
}

type RoleLoginInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LastLoginTime    int32                  `protobuf:"varint,1,opt,name=last_login_time,json=lastLoginTime,proto3" json:"last_login_time,omitempty"`
	LastLogoutTime   int32                  `protobuf:"varint,2,opt,name=last_logout_time,json=lastLogoutTime,proto3" json:"last_logout_time,omitempty"`
	LastHartBeatTime int32                  `protobuf:"varint,3,opt,name=last_hart_beat_time,json=lastHartBeatTime,proto3" json:"last_hart_beat_time,omitempty"`
	NowLoginTime     int32                  `protobuf:"varint,4,opt,name=now_login_time,json=nowLoginTime,proto3" json:"now_login_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RoleLoginInfo) Reset() {
	*x = RoleLoginInfo{}
	mi := &file_core_role_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleLoginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleLoginInfo) ProtoMessage() {}

func (x *RoleLoginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_role_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleLoginInfo.ProtoReflect.Descriptor instead.
func (*RoleLoginInfo) Descriptor() ([]byte, []int) {
	return file_core_role_proto_rawDescGZIP(), []int{1}
}

func (x *RoleLoginInfo) GetLastLoginTime() int32 {
	if x != nil {
		return x.LastLoginTime
	}
	return 0
}

func (x *RoleLoginInfo) GetLastLogoutTime() int32 {
	if x != nil {
		return x.LastLogoutTime
	}
	return 0
}

func (x *RoleLoginInfo) GetLastHartBeatTime() int32 {
	if x != nil {
		return x.LastHartBeatTime
	}
	return 0
}

func (x *RoleLoginInfo) GetNowLoginTime() int32 {
	if x != nil {
		return x.NowLoginTime
	}
	return 0
}

type RoleGameInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayRoomIds   []uint64               `protobuf:"varint,1,rep,packed,name=play_room_ids,json=playRoomIds,proto3" json:"play_room_ids,omitempty"` // 正在游玩的房间IDs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleGameInfo) Reset() {
	*x = RoleGameInfo{}
	mi := &file_core_role_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleGameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleGameInfo) ProtoMessage() {}

func (x *RoleGameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_role_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleGameInfo.ProtoReflect.Descriptor instead.
func (*RoleGameInfo) Descriptor() ([]byte, []int) {
	return file_core_role_proto_rawDescGZIP(), []int{2}
}

func (x *RoleGameInfo) GetPlayRoomIds() []uint64 {
	if x != nil {
		return x.PlayRoomIds
	}
	return nil
}

type RoleBasicInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`    // 角色名称
	Level int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"` // 等级
	// 以下货币/资源字段已废弃（迁移至 RoleCurrencyInfo.currency_map，按 EItemID
	// 货币段 key 存储）。字段号保留占位防止复用；服务端已停写停读。
	Exp           int64  `protobuf:"varint,3,opt,name=exp,proto3" json:"exp,omitempty"`                              // [deprecated] 经验 → currency_map[EItemID.EXP]
	Gold          int64  `protobuf:"varint,4,opt,name=gold,proto3" json:"gold,omitempty"`                            // [deprecated] 金币 → currency_map[EItemID.GOLD]
	Diamond       int64  `protobuf:"varint,5,opt,name=diamond,proto3" json:"diamond,omitempty"`                      // [deprecated] 钻石 → currency_map[EItemID.DIAMOND]
	Credit        int64  `protobuf:"varint,6,opt,name=credit,proto3" json:"credit,omitempty"`                        // [deprecated] 信用 → currency_map[EItemID.CREDIT]
	Liveness      int64  `protobuf:"varint,7,opt,name=liveness,proto3" json:"liveness,omitempty"`                    // [deprecated] 活跃度 → currency_map[EItemID.LIVENESS]
	GuildCoin     int64  `protobuf:"varint,8,opt,name=guild_coin,json=guildCoin,proto3" json:"guild_coin,omitempty"` // [deprecated] 公会币 → currency_map[EItemID.GUILD_COIN]
	FreeCnt       uint32 `protobuf:"varint,9,opt,name=free_cnt,json=freeCnt,proto3" json:"free_cnt,omitempty"`       // 免费改名次数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleBasicInfo) Reset() {
	*x = RoleBasicInfo{}
	mi := &file_core_role_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleBasicInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBasicInfo) ProtoMessage() {}

func (x *RoleBasicInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_role_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleBasicInfo.ProtoReflect.Descriptor instead.
func (*RoleBasicInfo) Descriptor() ([]byte, []int) {
	return file_core_role_proto_rawDescGZIP(), []int{3}
}

func (x *RoleBasicInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleBasicInfo) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *RoleBasicInfo) GetExp() int64 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *RoleBasicInfo) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *RoleBasicInfo) GetDiamond() int64 {
	if x != nil {
		return x.Diamond
	}
	return 0
}

func (x *RoleBasicInfo) GetCredit() int64 {
	if x != nil {
		return x.Credit
	}
	return 0
}

func (x *RoleBasicInfo) GetLiveness() int64 {
	if x != nil {
		return x.Liveness
	}
	return 0
}

func (x *RoleBasicInfo) GetGuildCoin() int64 {
	if x != nil {
		return x.GuildCoin
	}
	return 0
}

func (x *RoleBasicInfo) GetFreeCnt() uint32 {
	if x != nil {
		return x.FreeCnt
	}
	return 0
}

// 道具信息
type PbItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Time          int32                  `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"` // 0表示永久
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbItem) Reset() {
	*x = PbItem{}
	mi := &file_core_role_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbItem) ProtoMessage() {}

func (x *PbItem) ProtoReflect() protoreflect.Message {
	mi := &file_core_role_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbItem.ProtoReflect.Descriptor instead.
func (*PbItem) Descriptor() ([]byte, []int) {
	return file_core_role_proto_rawDescGZIP(), []int{4}
}

func (x *PbItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PbItem) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PbItem) GetTime() int32 {
	if x != nil {
		return x.Time
	}
	return 0
}

type RoleInventoryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemMap       map[int32]*PbItem      `protobuf:"bytes,1,rep,name=item_map,json=itemMap,proto3" json:"item_map,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleInventoryInfo) Reset() {
	*x = RoleInventoryInfo{}
	mi := &file_core_role_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleInventoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInventoryInfo) ProtoMessage() {}

func (x *RoleInventoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_role_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInventoryInfo.ProtoReflect.Descriptor instead.
func (*RoleInventoryInfo) Descriptor() ([]byte, []int) {
	return file_core_role_proto_rawDescGZIP(), []int{5}
}

func (x *RoleInventoryInfo) GetItemMap() map[int32]*PbItem {
	if x != nil {
		return x.ItemMap
	}
	return nil
}

// 头像
type PbIcon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RedPoint      bool                   `protobuf:"varint,2,opt,name=red_point,json=redPoint,proto3" json:"red_point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbIcon) Reset() {
	*x = PbIcon{}
	mi := &file_core_role_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbIcon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbIcon) ProtoMessage() {}

func (x *PbIcon) ProtoReflect() protoreflect.Message {
	mi := &file_core_role_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbIcon.ProtoReflect.Descriptor instead.
func (*PbIcon) Descriptor() ([]byte, []int) {
	return file_core_role_proto_rawDescGZIP(), []int{6}
}

func (x *PbIcon) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PbIcon) GetRedPoint() bool {
	if x != nil {
		return x.RedPoint
	}
	return false
}

// 头像框
type PbFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RedPoint      bool                   `protobuf:"varint,2,opt,name=red_point,json=redPoint,proto3" json:"red_point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbFrame) Reset() {
	*x = PbFrame{}
	mi := &file_core_role_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbFrame) ProtoMessage() {}

func (x *PbFrame) ProtoReflect() protoreflect.Message {
	mi := &file_core_role_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbFrame.ProtoReflect.Descriptor instead.
func (*PbFrame) Descriptor() ([]byte, []int) {
	return file_core_role_proto_rawDescGZIP(), []int{7}
}

func (x *PbFrame) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PbFrame) GetRedPoint() bool {
	if x != nil {
		return x.RedPoint
	}
	return false
}

// 头像
type RoleIconInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IconUrl       string                 `protobuf:"bytes,1,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`                                                                               // 当前头像url
	FrameId       int32                  `protobuf:"varint,2,opt,name=frame_id,json=frameId,proto3" json:"frame_id,omitempty"`                                                                              // 当前相框
	IconMap       map[int32]*PbIcon      `protobuf:"bytes,3,rep,name=icon_map,json=iconMap,proto3" json:"icon_map,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`    // 已解锁的头像列表
	FrameMap      map[int32]*PbFrame     `protobuf:"bytes,4,rep,name=frame_map,json=frameMap,proto3" json:"frame_map,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 已解锁的头像框列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleIconInfo) Reset() {
	*x = RoleIconInfo{}
	mi := &file_core_role_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleIconInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleIconInfo) ProtoMessage() {}

func (x *RoleIconInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_role_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleIconInfo.ProtoReflect.Descriptor instead.
func (*RoleIconInfo) Descriptor() ([]byte, []int) {
	return file_core_role_proto_rawDescGZIP(), []int{8}
}

func (x *RoleIconInfo) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *RoleIconInfo) GetFrameId() int32 {
	if x != nil {
		return x.FrameId
	}
	return 0
}

func (x *RoleIconInfo) GetIconMap() map[int32]*PbIcon {
	if x != nil {
		return x.IconMap
	}
	return nil
}

func (x *RoleIconInfo) GetFrameMap() map[int32]*PbFrame {
	if x != nil {
		return x.FrameMap
	}
	return nil
}

// 商城礼包
type PbMallItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfId        int32                  `protobuf:"varint,1,opt,name=conf_id,json=confId,proto3" json:"conf_id,omitempty"`
	DailyBuyCount int32                  `protobuf:"varint,2,opt,name=daily_buy_count,json=dailyBuyCount,proto3" json:"daily_buy_count,omitempty"`
	TotalBuyCount int32                  `protobuf:"varint,3,opt,name=total_buy_count,json=totalBuyCount,proto3" json:"total_buy_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbMallItem) Reset() {
	*x = PbMallItem{}
	mi := &file_core_role_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbMallItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbMallItem) ProtoMessage() {}

func (x *PbMallItem) ProtoReflect() protoreflect.Message {
	mi := &file_core_role_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbMallItem.ProtoReflect.Descriptor instead.
func (*PbMallItem) Descriptor() ([]byte, []int) {
	return file_core_role_proto_rawDescGZIP(), []int{9}
}

func (x *PbMallItem) GetConfId() int32 {
	if x != nil {
		return x.ConfId
	}
	return 0
}

func (x *PbMallItem) GetDailyBuyCount() int32 {
	if x != nil {
		return x.DailyBuyCount
	}
	return 0
}

func (x *PbMallItem) GetTotalBuyCount() int32 {
	if x != nil {
		return x.TotalBuyCount
	}
	return 0
}

// 商城礼包
type RoleMallInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemMap       map[int32]*PbMallItem  `protobuf:"bytes,1,rep,name=item_map,json=itemMap,proto3" json:"item_map,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleMallInfo) Reset() {
	*x = RoleMallInfo{}
	mi := &file_core_role_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleMallInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleMallInfo) ProtoMessage() {}

func (x *RoleMallInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_role_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleMallInfo.ProtoReflect.Descriptor instead.
func (*RoleMallInfo) Descriptor() ([]byte, []int) {
	return file_core_role_proto_rawDescGZIP(), []int{10}
}

func (x *RoleMallInfo) GetItemMap() map[int32]*PbMallItem {
	if x != nil {
		return x.ItemMap
	}
	return nil
}

type PbTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int32                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Argv1         int32                  `protobuf:"varint,2,opt,name=argv1,proto3" json:"argv1,omitempty"`
	Argv2         int32                  `protobuf:"varint,3,opt,name=argv2,proto3" json:"argv2,omitempty"`
	Argv3         int32                  `protobuf:"varint,4,opt,name=argv3,proto3" json:"argv3,omitempty"`
	Progress      int32                  `protobuf:"varint,5,opt,name=progress,proto3" json:"progress,omitempty"`
	TaskType      int32                  `protobuf:"varint,6,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	HasAward      int32                  `protobuf:"varint,7,opt,name=has_award,json=hasAward,proto3" json:"has_award,omitempty"` //完成奖励   0未领取 1可领取，2自动发放，3手动领取
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbTask) Reset() {
	*x = PbTask{}
	mi := &file_core_role_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbTask) ProtoMessage() {}

func (x *PbTask) ProtoReflect() protoreflect.Message {
	mi := &file_core_role_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbTask.ProtoReflect.Descriptor instead.
func (*PbTask) Descriptor() ([]byte, []int) {
	return file_core_role_proto_rawDescGZIP(), []int{11}
}

func (x *PbTask) GetTaskId() int32 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *PbTask) GetArgv1() int32 {
	if x != nil {
		return x.Argv1
	}
	return 0
}

func (x *PbTask) GetArgv2() int32 {
	if x != nil {
		return x.Argv2
	}
	return 0
}

func (x *PbTask) GetArgv3() int32 {
	if x != nil {
		return x.Argv3
	}
	return 0
}

func (x *PbTask) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *PbTask) GetTaskType() int32 {
	if x != nil {
		return x.TaskType
	}
	return 0
}

func (x *PbTask) GetHasAward() int32 {
	if x != nil {
		return x.HasAward
	}
	return 0
}

type RoleTaskInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskMap       map[int32]*PbTask      `protobuf:"bytes,1,rep,name=task_map,json=taskMap,proto3" json:"task_map,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleTaskInfo) Reset() {
	*x = RoleTaskInfo{}
	mi := &file_core_role_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleTaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleTaskInfo) ProtoMessage() {}

func (x *RoleTaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_role_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleTaskInfo.ProtoReflect.Descriptor instead.
func (*RoleTaskInfo) Descriptor() ([]byte, []int) {
	return file_core_role_proto_rawDescGZIP(), []int{12}
}

func (x *RoleTaskInfo) GetTaskMap() map[int32]*PbTask {
	if x != nil {
		return x.TaskMap
	}
	return nil
}

// 主线任务
type RoleMainTaskInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurTaskId     int32                  `protobuf:"varint,1,opt,name=cur_task_id,json=curTaskId,proto3" json:"cur_task_id,omitempty"`
	Finished      bool                   `protobuf:"varint,2,opt,name=finished,proto3" json:"finished,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleMainTaskInfo) Reset() {
	*x = RoleMainTaskInfo{}
	mi := &file_core_role_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleMainTaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleMainTaskInfo) ProtoMessage() {}

func (x *RoleMainTaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_role_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleMainTaskInfo.ProtoReflect.Descriptor instead.
func (*RoleMainTaskInfo) Descriptor() ([]byte, []int) {
	return file_core_role_proto_rawDescGZIP(), []int{13}
}

func (x *RoleMainTaskInfo) GetCurTaskId() int32 {
	if x != nil {
		return x.CurTaskId
	}
	return 0
}

func (x *RoleMainTaskInfo) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

// 个人公会信息 ,例如公会副本，商场购买记录等
type RoleGuildInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gid           uint64                 `protobuf:"varint,1,opt,name=gid,proto3" json:"gid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Title         int32                  `protobuf:"varint,3,opt,name=title,proto3" json:"title,omitempty"`
	DonateCnt     uint32                 `protobuf:"varint,4,opt,name=donate_cnt,json=donateCnt,proto3" json:"donate_cnt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleGuildInfo) Reset() {
	*x = RoleGuildInfo{}
	mi := &file_core_role_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleGuildInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleGuildInfo) ProtoMessage() {}

func (x *RoleGuildInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_role_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleGuildInfo.ProtoReflect.Descriptor instead.
func (*RoleGuildInfo) Descriptor() ([]byte, []int) {
	return file_core_role_proto_rawDescGZIP(), []int{14}
}

func (x *RoleGuildInfo) GetGid() uint64 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *RoleGuildInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleGuildInfo) GetTitle() int32 {
	if x != nil {
		return x.Title
	}
	return 0
}

func (x *RoleGuildInfo) GetDonateCnt() uint32 {
	if x != nil {
		return x.DonateCnt
	}
	return 0
}

// 玩家引导ID
type RoleGuideInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdLis         []int32                `protobuf:"varint,1,rep,packed,name=id_lis,json=idLis,proto3" json:"id_lis,omitempty"` // 已经完成
	CurId         int32                  `protobuf:"varint,2,opt,name=cur_id,json=curId,proto3" json:"cur_id,omitempty"`        // 正在进行的ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleGuideInfo) Reset() {
	*x = RoleGuideInfo{}
	mi := &file_core_role_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleGuideInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleGuideInfo) ProtoMessage() {}

func (x *RoleGuideInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_role_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleGuideInfo.ProtoReflect.Descriptor instead.
func (*RoleGuideInfo) Descriptor() ([]byte, []int) {
	return file_core_role_proto_rawDescGZIP(), []int{15}
}

func (x *RoleGuideInfo) GetIdLis() []int32 {
	if x != nil {
		return x.IdLis
	}
	return nil
}

func (x *RoleGuideInfo) GetCurId() int32 {
	if x != nil {
		return x.CurId
	}
	return 0
}

// 功能开放列表
type RoleOpenFunction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []int32                `protobuf:"varint,1,rep,packed,name=data,proto3" json:"data,omitempty"`                       // 已经开放的功能ID
	IsAllOpen     bool                   `protobuf:"varint,2,opt,name=is_all_open,json=isAllOpen,proto3" json:"is_all_open,omitempty"` // 测试用,上线后删除该字段
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleOpenFunction) Reset() {
	*x = RoleOpenFunction{}
	mi := &file_core_role_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleOpenFunction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleOpenFunction) ProtoMessage() {}

func (x *RoleOpenFunction) ProtoReflect() protoreflect.Message {
	mi := &file_core_role_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleOpenFunction.ProtoReflect.Descriptor instead.
func (*RoleOpenFunction) Descriptor() ([]byte, []int) {
	return file_core_role_proto_rawDescGZIP(), []int{16}
}

func (x *RoleOpenFunction) GetData() []int32 {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RoleOpenFunction) GetIsAllOpen() bool {
	if x != nil {
		return x.IsAllOpen
	}
	return false
}

// 活动任务,日常，成就等
type RoleActvityTaskInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskMap       map[int32]*PbTask      `protobuf:"bytes,1,rep,name=task_map,json=taskMap,proto3" json:"task_map,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleActvityTaskInfo) Reset() {
	*x = RoleActvityTaskInfo{}
	mi := &file_core_role_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleActvityTaskInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleActvityTaskInfo) ProtoMessage() {}

func (x *RoleActvityTaskInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_role_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleActvityTaskInfo.ProtoReflect.Descriptor instead.
func (*RoleActvityTaskInfo) Descriptor() ([]byte, []int) {
	return file_core_role_proto_rawDescGZIP(), []int{17}
}

func (x *RoleActvityTaskInfo) GetTaskMap() map[int32]*PbTask {
	if x != nil {
		return x.TaskMap
	}
	return nil
}

// 角色的所有数据
type RoleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RegisterInfo  *RoleRegisterInfo      `protobuf:"bytes,1,opt,name=register_info,json=registerInfo,proto3" json:"register_info,omitempty"`
	LoginInfo     *RoleLoginInfo         `protobuf:"bytes,2,opt,name=login_info,json=loginInfo,proto3" json:"login_info,omitempty"`
	GameInfo      *RoleGameInfo          `protobuf:"bytes,3,opt,name=game_info,json=gameInfo,proto3" json:"game_info,omitempty"`                // 游戏信息
	BasicInfo     *RoleBasicInfo         `protobuf:"bytes,4,opt,name=basic_info,json=basicInfo,proto3" json:"basic_info,omitempty"`             // role base
	InventoryInfo *RoleInventoryInfo     `protobuf:"bytes,5,opt,name=inventory_info,json=inventoryInfo,proto3" json:"inventory_info,omitempty"` // 背包数据
	IconInfo      *RoleIconInfo          `protobuf:"bytes,6,opt,name=icon_info,json=iconInfo,proto3" json:"icon_info,omitempty"`                // 头像资源
	MallInfo      *RoleMallInfo          `protobuf:"bytes,7,opt,name=mall_info,json=mallInfo,proto3" json:"mall_info,omitempty"`                // 商城
	MainTaskInfo  *RoleMainTaskInfo      `protobuf:"bytes,8,opt,name=main_task_info,json=mainTaskInfo,proto3" json:"main_task_info,omitempty"`  // 主线任务
	GuildInfo     *RoleGuildInfo         `protobuf:"bytes,9,opt,name=guild_info,json=guildInfo,proto3" json:"guild_info,omitempty"`             // 公会
	GuideInfo     *RoleGuideInfo         `protobuf:"bytes,10,opt,name=guide_info,json=guideInfo,proto3" json:"guide_info,omitempty"`            // 引导数据
	OpenFunInfo   *RoleOpenFunction      `protobuf:"bytes,11,opt,name=open_fun_info,json=openFunInfo,proto3" json:"open_fun_info,omitempty"`    // 功能开放
	Actvity_Info  *RoleActvityTaskInfo   `protobuf:"bytes,13,opt,name=actvity_Info,json=actvityInfo,proto3" json:"actvity_Info,omitempty"`      // 活动任务，日常等
	CurrencyInfo  *RoleCurrencyInfo      `protobuf:"bytes,14,opt,name=currency_info,json=currencyInfo,proto3" json:"currency_info,omitempty"`   // 货币/资源（1-9999 段）
	ConnSvrInfo   *ConnSvrInfo           `protobuf:"bytes,100,opt,name=conn_svr_info,json=connSvrInfo,proto3" json:"conn_svr_info,omitempty"`   // 服务器用，客户端不用管
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleInfo) Reset() {
	*x = RoleInfo{}
	mi := &file_core_role_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInfo) ProtoMessage() {}

func (x *RoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_role_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInfo.ProtoReflect.Descriptor instead.
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return file_core_role_proto_rawDescGZIP(), []int{18}
}

func (x *RoleInfo) GetRegisterInfo() *RoleRegisterInfo {
	if x != nil {
		return x.RegisterInfo
	}
	return nil
}

func (x *RoleInfo) GetLoginInfo() *RoleLoginInfo {
	if x != nil {
		return x.LoginInfo
	}
	return nil
}

func (x *RoleInfo) GetGameInfo() *RoleGameInfo {
	if x != nil {
		return x.GameInfo
	}
	return nil
}

func (x *RoleInfo) GetBasicInfo() *RoleBasicInfo {
	if x != nil {
		return x.BasicInfo
	}
	return nil
}

func (x *RoleInfo) GetInventoryInfo() *RoleInventoryInfo {
	if x != nil {
		return x.InventoryInfo
	}
	return nil
}

func (x *RoleInfo) GetIconInfo() *RoleIconInfo {
	if x != nil {
		return x.IconInfo
	}
	return nil
}

func (x *RoleInfo) GetMallInfo() *RoleMallInfo {
	if x != nil {
		return x.MallInfo
	}
	return nil
}

func (x *RoleInfo) GetMainTaskInfo() *RoleMainTaskInfo {
	if x != nil {
		return x.MainTaskInfo
	}
	return nil
}

func (x *RoleInfo) GetGuildInfo() *RoleGuildInfo {
	if x != nil {
		return x.GuildInfo
	}
	return nil
}

func (x *RoleInfo) GetGuideInfo() *RoleGuideInfo {
	if x != nil {
		return x.GuideInfo
	}
	return nil
}

func (x *RoleInfo) GetOpenFunInfo() *RoleOpenFunction {
	if x != nil {
		return x.OpenFunInfo
	}
	return nil
}

func (x *RoleInfo) GetActvity_Info() *RoleActvityTaskInfo {
	if x != nil {
		return x.Actvity_Info
	}
	return nil
}

func (x *RoleInfo) GetCurrencyInfo() *RoleCurrencyInfo {
	if x != nil {
		return x.CurrencyInfo
	}
	return nil
}

func (x *RoleInfo) GetConnSvrInfo() *ConnSvrInfo {
	if x != nil {
		return x.ConnSvrInfo
	}
	return nil
}

// 货币/资源余额。key 为货币 ID（EItemID 货币段，1-9999）；
// 全部资源（金币/钻石/体力/经验等）集中于此，加新货币零 proto 改动。
type RoleCurrencyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrencyMap   map[int32]int64        `protobuf:"bytes,1,rep,name=currency_map,json=currencyMap,proto3" json:"currency_map,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleCurrencyInfo) Reset() {
	*x = RoleCurrencyInfo{}
	mi := &file_core_role_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleCurrencyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleCurrencyInfo) ProtoMessage() {}

func (x *RoleCurrencyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_role_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleCurrencyInfo.ProtoReflect.Descriptor instead.
func (*RoleCurrencyInfo) Descriptor() ([]byte, []int) {
	return file_core_role_proto_rawDescGZIP(), []int{19}
}

func (x *RoleCurrencyInfo) GetCurrencyMap() map[int32]int64 {
	if x != nil {
		return x.CurrencyMap
	}
	return nil
}

type ConnSvrInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BusId         uint32                 `protobuf:"varint,1,opt,name=bus_id,json=busId,proto3" json:"bus_id,omitempty"`
	ClientPos     string                 `protobuf:"bytes,2,opt,name=client_pos,json=clientPos,proto3" json:"client_pos,omitempty"`
	ClientIp      uint32                 `protobuf:"varint,3,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnSvrInfo) Reset() {
	*x = ConnSvrInfo{}
	mi := &file_core_role_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnSvrInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnSvrInfo) ProtoMessage() {}

func (x *ConnSvrInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_role_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnSvrInfo.ProtoReflect.Descriptor instead.
func (*ConnSvrInfo) Descriptor() ([]byte, []int) {
	return file_core_role_proto_rawDescGZIP(), []int{20}
}

func (x *ConnSvrInfo) GetBusId() uint32 {
	if x != nil {
		return x.BusId
	}
	return 0
}

func (x *ConnSvrInfo) GetClientPos() string {
	if x != nil {
		return x.ClientPos
	}
	return ""
}

func (x *ConnSvrInfo) GetClientIp() uint32 {
	if x != nil {
		return x.ClientIp
	}
	return 0
}

// 玩家头像框需要的信息
type PbIconDesc struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Uid            uint64                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IconUrl        string                 `protobuf:"bytes,3,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
	Frame          int32                  `protobuf:"varint,4,opt,name=frame,proto3" json:"frame,omitempty"`
	Level          int32                  `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	VipLevel       int32                  `protobuf:"varint,6,opt,name=vip_level,json=vipLevel,proto3" json:"vip_level,omitempty"`
	LastOnlineTime int32                  `protobuf:"varint,30,opt,name=last_online_time,json=lastOnlineTime,proto3" json:"last_online_time,omitempty"`
	IsOnline       bool                   `protobuf:"varint,31,opt,name=is_online,json=isOnline,proto3" json:"is_online,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PbIconDesc) Reset() {
	*x = PbIconDesc{}
	mi := &file_core_role_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbIconDesc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbIconDesc) ProtoMessage() {}

func (x *PbIconDesc) ProtoReflect() protoreflect.Message {
	mi := &file_core_role_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbIconDesc.ProtoReflect.Descriptor instead.
func (*PbIconDesc) Descriptor() ([]byte, []int) {
	return file_core_role_proto_rawDescGZIP(), []int{21}
}

func (x *PbIconDesc) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PbIconDesc) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PbIconDesc) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

func (x *PbIconDesc) GetFrame() int32 {
	if x != nil {
		return x.Frame
	}
	return 0
}

func (x *PbIconDesc) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PbIconDesc) GetVipLevel() int32 {
	if x != nil {
		return x.VipLevel
	}
	return 0
}

func (x *PbIconDesc) GetLastOnlineTime() int32 {
	if x != nil {
		return x.LastOnlineTime
	}
	return 0
}

func (x *PbIconDesc) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

var File_core_role_proto protoreflect.FileDescriptor

const file_core_role_proto_rawDesc = "" +
	"\n" +
	"\x0fcore/role.proto\x12\vg1.protocol\"\x8b\x01\n" +
	"\x10RoleRegisterInfo\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12#\n" +
	"\rregister_time\x18\x02 \x01(\x05R\fregisterTime\x12\x12\n" +
	"\x04zone\x18\x03 \x01(\x05R\x04zone\x12,\n" +
	"\x12time_offset_minute\x18\x04 \x01(\x05R\x10timeOffsetMinute\"\xb6\x01\n" +
	"\rRoleLoginInfo\x12&\n" +
	"\x0flast_login_time\x18\x01 \x01(\x05R\rlastLoginTime\x12(\n" +
	"\x10last_logout_time\x18\x02 \x01(\x05R\x0elastLogoutTime\x12-\n" +
	"\x13last_hart_beat_time\x18\x03 \x01(\x05R\x10lastHartBeatTime\x12$\n" +
	"\x0enow_login_time\x18\x04 \x01(\x05R\fnowLoginTime\"2\n" +
	"\fRoleGameInfo\x12\"\n" +
	"\rplay_room_ids\x18\x01 \x03(\x04R\vplayRoomIds\"\xf3\x01\n" +
	"\rRoleBasicInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12\x10\n" +
	"\x03exp\x18\x03 \x01(\x03R\x03exp\x12\x12\n" +
	"\x04gold\x18\x04 \x01(\x03R\x04gold\x12\x18\n" +
	"\adiamond\x18\x05 \x01(\x03R\adiamond\x12\x16\n" +
	"\x06credit\x18\x06 \x01(\x03R\x06credit\x12\x1a\n" +
	"\bliveness\x18\a \x01(\x03R\bliveness\x12\x1d\n" +
	"\n" +
	"guild_coin\x18\b \x01(\x03R\tguildCoin\x12\x19\n" +
	"\bfree_cnt\x18\t \x01(\rR\afreeCntJ\x04\b\n" +
	"\x10\vJ\x04\b\v\x10\f\"B\n" +
	"\x06PbItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12\x12\n" +
	"\x04time\x18\x03 \x01(\x05R\x04time\"\xac\x01\n" +
	"\x11RoleInventoryInfo\x12F\n" +
	"\bitem_map\x18\x01 \x03(\v2+.g1.protocol.RoleInventoryInfo.ItemMapEntryR\aitemMap\x1aO\n" +
	"\fItemMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.g1.protocol.PbItemR\x05value:\x028\x01\"5\n" +
	"\x06PbIcon\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tred_point\x18\x02 \x01(\bR\bredPoint\"6\n" +
	"\aPbFrame\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tred_point\x18\x02 \x01(\bR\bredPoint\"\xf1\x02\n" +
	"\fRoleIconInfo\x12\x19\n" +
	"\bicon_url\x18\x01 \x01(\tR\aiconUrl\x12\x19\n" +
	"\bframe_id\x18\x02 \x01(\x05R\aframeId\x12A\n" +
	"\bicon_map\x18\x03 \x03(\v2&.g1.protocol.RoleIconInfo.IconMapEntryR\aiconMap\x12D\n" +
	"\tframe_map\x18\x04 \x03(\v2'.g1.protocol.RoleIconInfo.FrameMapEntryR\bframeMap\x1aO\n" +
	"\fIconMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.g1.protocol.PbIconR\x05value:\x028\x01\x1aQ\n" +
	"\rFrameMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.g1.protocol.PbFrameR\x05value:\x028\x01\"u\n" +
	"\n" +
	"PbMallItem\x12\x17\n" +
	"\aconf_id\x18\x01 \x01(\x05R\x06confId\x12&\n" +
	"\x0fdaily_buy_count\x18\x02 \x01(\x05R\rdailyBuyCount\x12&\n" +
	"\x0ftotal_buy_count\x18\x03 \x01(\x05R\rtotalBuyCount\"\xa6\x01\n" +
	"\fRoleMallInfo\x12A\n" +
	"\bitem_map\x18\x01 \x03(\v2&.g1.protocol.RoleMallInfo.ItemMapEntryR\aitemMap\x1aS\n" +
	"\fItemMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.g1.protocol.PbMallItemR\x05value:\x028\x01\"\xb9\x01\n" +
	"\x06PbTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x05R\x06taskId\x12\x14\n" +
	"\x05argv1\x18\x02 \x01(\x05R\x05argv1\x12\x14\n" +
	"\x05argv2\x18\x03 \x01(\x05R\x05argv2\x12\x14\n" +
	"\x05argv3\x18\x04 \x01(\x05R\x05argv3\x12\x1a\n" +
	"\bprogress\x18\x05 \x01(\x05R\bprogress\x12\x1b\n" +
	"\ttask_type\x18\x06 \x01(\x05R\btaskType\x12\x1b\n" +
	"\thas_award\x18\a \x01(\x05R\bhasAward\"\xa2\x01\n" +
	"\fRoleTaskInfo\x12A\n" +
	"\btask_map\x18\x01 \x03(\v2&.g1.protocol.RoleTaskInfo.TaskMapEntryR\ataskMap\x1aO\n" +
	"\fTaskMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.g1.protocol.PbTaskR\x05value:\x028\x01\"N\n" +
	"\x10RoleMainTaskInfo\x12\x1e\n" +
	"\vcur_task_id\x18\x01 \x01(\x05R\tcurTaskId\x12\x1a\n" +
	"\bfinished\x18\x02 \x01(\bR\bfinished\"j\n" +
	"\rRoleGuildInfo\x12\x10\n" +
	"\x03gid\x18\x01 \x01(\x04R\x03gid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x03 \x01(\x05R\x05title\x12\x1d\n" +
	"\n" +
	"donate_cnt\x18\x04 \x01(\rR\tdonateCnt\"=\n" +
	"\rRoleGuideInfo\x12\x15\n" +
	"\x06id_lis\x18\x01 \x03(\x05R\x05idLis\x12\x15\n" +
	"\x06cur_id\x18\x02 \x01(\x05R\x05curId\"F\n" +
	"\x10RoleOpenFunction\x12\x12\n" +
	"\x04data\x18\x01 \x03(\x05R\x04data\x12\x1e\n" +
	"\vis_all_open\x18\x02 \x01(\bR\tisAllOpen\"\xb0\x01\n" +
	"\x13RoleActvityTaskInfo\x12H\n" +
	"\btask_map\x18\x01 \x03(\v2-.g1.protocol.RoleActvityTaskInfo.TaskMapEntryR\ataskMap\x1aO\n" +
	"\fTaskMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.g1.protocol.PbTaskR\x05value:\x028\x01\"\xfe\x06\n" +
	"\bRoleInfo\x12B\n" +
	"\rregister_info\x18\x01 \x01(\v2\x1d.g1.protocol.RoleRegisterInfoR\fregisterInfo\x129\n" +
	"\n" +
	"login_info\x18\x02 \x01(\v2\x1a.g1.protocol.RoleLoginInfoR\tloginInfo\x126\n" +
	"\tgame_info\x18\x03 \x01(\v2\x19.g1.protocol.RoleGameInfoR\bgameInfo\x129\n" +
	"\n" +
	"basic_info\x18\x04 \x01(\v2\x1a.g1.protocol.RoleBasicInfoR\tbasicInfo\x12E\n" +
	"\x0einventory_info\x18\x05 \x01(\v2\x1e.g1.protocol.RoleInventoryInfoR\rinventoryInfo\x126\n" +
	"\ticon_info\x18\x06 \x01(\v2\x19.g1.protocol.RoleIconInfoR\biconInfo\x126\n" +
	"\tmall_info\x18\a \x01(\v2\x19.g1.protocol.RoleMallInfoR\bmallInfo\x12C\n" +
	"\x0emain_task_info\x18\b \x01(\v2\x1d.g1.protocol.RoleMainTaskInfoR\fmainTaskInfo\x129\n" +
	"\n" +
	"guild_info\x18\t \x01(\v2\x1a.g1.protocol.RoleGuildInfoR\tguildInfo\x129\n" +
	"\n" +
	"guide_info\x18\n" +
	" \x01(\v2\x1a.g1.protocol.RoleGuideInfoR\tguideInfo\x12A\n" +
	"\ropen_fun_info\x18\v \x01(\v2\x1d.g1.protocol.RoleOpenFunctionR\vopenFunInfo\x12C\n" +
	"\factvity_Info\x18\r \x01(\v2 .g1.protocol.RoleActvityTaskInfoR\vactvityInfo\x12B\n" +
	"\rcurrency_info\x18\x0e \x01(\v2\x1d.g1.protocol.RoleCurrencyInfoR\fcurrencyInfo\x12<\n" +
	"\rconn_svr_info\x18d \x01(\v2\x18.g1.protocol.ConnSvrInfoR\vconnSvrInfoJ\x04\b\f\x10\r\"\xa5\x01\n" +
	"\x10RoleCurrencyInfo\x12Q\n" +
	"\fcurrency_map\x18\x01 \x03(\v2..g1.protocol.RoleCurrencyInfo.CurrencyMapEntryR\vcurrencyMap\x1a>\n" +
	"\x10CurrencyMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"`\n" +
	"\vConnSvrInfo\x12\x15\n" +
	"\x06bus_id\x18\x01 \x01(\rR\x05busId\x12\x1d\n" +
	"\n" +
	"client_pos\x18\x02 \x01(\tR\tclientPos\x12\x1b\n" +
	"\tclient_ip\x18\x03 \x01(\rR\bclientIp\"\xdd\x01\n" +
	"\n" +
	"PbIconDesc\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x04R\x03uid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bicon_url\x18\x03 \x01(\tR\aiconUrl\x12\x14\n" +
	"\x05frame\x18\x04 \x01(\x05R\x05frame\x12\x14\n" +
	"\x05level\x18\x05 \x01(\x05R\x05level\x12\x1b\n" +
	"\tvip_level\x18\x06 \x01(\x05R\bvipLevel\x12(\n" +
	"\x10last_online_time\x18\x1e \x01(\x05R\x0elastOnlineTime\x12\x1b\n" +
	"\tis_online\x18\x1f \x01(\bR\bisOnlineB9Z7github.com/Iori372552686/g1_common/protocol;g1_protocolb\x06proto3"

var (
	file_core_role_proto_rawDescOnce sync.Once
	file_core_role_proto_rawDescData []byte
)

func file_core_role_proto_rawDescGZIP() []byte {
	file_core_role_proto_rawDescOnce.Do(func() {
		file_core_role_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_role_proto_rawDesc), len(file_core_role_proto_rawDesc)))
	})
	return file_core_role_proto_rawDescData
}

var file_core_role_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_core_role_proto_goTypes = []any{
	(*RoleRegisterInfo)(nil),    // 0: g1.protocol.RoleRegisterInfo
	(*RoleLoginInfo)(nil),       // 1: g1.protocol.RoleLoginInfo
	(*RoleGameInfo)(nil),        // 2: g1.protocol.RoleGameInfo
	(*RoleBasicInfo)(nil),       // 3: g1.protocol.RoleBasicInfo
	(*PbItem)(nil),              // 4: g1.protocol.PbItem
	(*RoleInventoryInfo)(nil),   // 5: g1.protocol.RoleInventoryInfo
	(*PbIcon)(nil),              // 6: g1.protocol.PbIcon
	(*PbFrame)(nil),             // 7: g1.protocol.PbFrame
	(*RoleIconInfo)(nil),        // 8: g1.protocol.RoleIconInfo
	(*PbMallItem)(nil),          // 9: g1.protocol.PbMallItem
	(*RoleMallInfo)(nil),        // 10: g1.protocol.RoleMallInfo
	(*PbTask)(nil),              // 11: g1.protocol.PbTask
	(*RoleTaskInfo)(nil),        // 12: g1.protocol.RoleTaskInfo
	(*RoleMainTaskInfo)(nil),    // 13: g1.protocol.RoleMainTaskInfo
	(*RoleGuildInfo)(nil),       // 14: g1.protocol.RoleGuildInfo
	(*RoleGuideInfo)(nil),       // 15: g1.protocol.RoleGuideInfo
	(*RoleOpenFunction)(nil),    // 16: g1.protocol.RoleOpenFunction
	(*RoleActvityTaskInfo)(nil), // 17: g1.protocol.RoleActvityTaskInfo
	(*RoleInfo)(nil),            // 18: g1.protocol.RoleInfo
	(*RoleCurrencyInfo)(nil),    // 19: g1.protocol.RoleCurrencyInfo
	(*ConnSvrInfo)(nil),         // 20: g1.protocol.ConnSvrInfo
	(*PbIconDesc)(nil),          // 21: g1.protocol.PbIconDesc
	nil,                         // 22: g1.protocol.RoleInventoryInfo.ItemMapEntry
	nil,                         // 23: g1.protocol.RoleIconInfo.IconMapEntry
	nil,                         // 24: g1.protocol.RoleIconInfo.FrameMapEntry
	nil,                         // 25: g1.protocol.RoleMallInfo.ItemMapEntry
	nil,                         // 26: g1.protocol.RoleTaskInfo.TaskMapEntry
	nil,                         // 27: g1.protocol.RoleActvityTaskInfo.TaskMapEntry
	nil,                         // 28: g1.protocol.RoleCurrencyInfo.CurrencyMapEntry
}
var file_core_role_proto_depIdxs = []int32{
	22, // 0: g1.protocol.RoleInventoryInfo.item_map:type_name -> g1.protocol.RoleInventoryInfo.ItemMapEntry
	23, // 1: g1.protocol.RoleIconInfo.icon_map:type_name -> g1.protocol.RoleIconInfo.IconMapEntry
	24, // 2: g1.protocol.RoleIconInfo.frame_map:type_name -> g1.protocol.RoleIconInfo.FrameMapEntry
	25, // 3: g1.protocol.RoleMallInfo.item_map:type_name -> g1.protocol.RoleMallInfo.ItemMapEntry
	26, // 4: g1.protocol.RoleTaskInfo.task_map:type_name -> g1.protocol.RoleTaskInfo.TaskMapEntry
	27, // 5: g1.protocol.RoleActvityTaskInfo.task_map:type_name -> g1.protocol.RoleActvityTaskInfo.TaskMapEntry
	0,  // 6: g1.protocol.RoleInfo.register_info:type_name -> g1.protocol.RoleRegisterInfo
	1,  // 7: g1.protocol.RoleInfo.login_info:type_name -> g1.protocol.RoleLoginInfo
	2,  // 8: g1.protocol.RoleInfo.game_info:type_name -> g1.protocol.RoleGameInfo
	3,  // 9: g1.protocol.RoleInfo.basic_info:type_name -> g1.protocol.RoleBasicInfo
	5,  // 10: g1.protocol.RoleInfo.inventory_info:type_name -> g1.protocol.RoleInventoryInfo
	8,  // 11: g1.protocol.RoleInfo.icon_info:type_name -> g1.protocol.RoleIconInfo
	10, // 12: g1.protocol.RoleInfo.mall_info:type_name -> g1.protocol.RoleMallInfo
	13, // 13: g1.protocol.RoleInfo.main_task_info:type_name -> g1.protocol.RoleMainTaskInfo
	14, // 14: g1.protocol.RoleInfo.guild_info:type_name -> g1.protocol.RoleGuildInfo
	15, // 15: g1.protocol.RoleInfo.guide_info:type_name -> g1.protocol.RoleGuideInfo
	16, // 16: g1.protocol.RoleInfo.open_fun_info:type_name -> g1.protocol.RoleOpenFunction
	17, // 17: g1.protocol.RoleInfo.actvity_Info:type_name -> g1.protocol.RoleActvityTaskInfo
	19, // 18: g1.protocol.RoleInfo.currency_info:type_name -> g1.protocol.RoleCurrencyInfo
	20, // 19: g1.protocol.RoleInfo.conn_svr_info:type_name -> g1.protocol.ConnSvrInfo
	28, // 20: g1.protocol.RoleCurrencyInfo.currency_map:type_name -> g1.protocol.RoleCurrencyInfo.CurrencyMapEntry
	4,  // 21: g1.protocol.RoleInventoryInfo.ItemMapEntry.value:type_name -> g1.protocol.PbItem
	6,  // 22: g1.protocol.RoleIconInfo.IconMapEntry.value:type_name -> g1.protocol.PbIcon
	7,  // 23: g1.protocol.RoleIconInfo.FrameMapEntry.value:type_name -> g1.protocol.PbFrame
	9,  // 24: g1.protocol.RoleMallInfo.ItemMapEntry.value:type_name -> g1.protocol.PbMallItem
	11, // 25: g1.protocol.RoleTaskInfo.TaskMapEntry.value:type_name -> g1.protocol.PbTask
	11, // 26: g1.protocol.RoleActvityTaskInfo.TaskMapEntry.value:type_name -> g1.protocol.PbTask
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_core_role_proto_init() }
func file_core_role_proto_init() {
	if File_core_role_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_role_proto_rawDesc), len(file_core_role_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_role_proto_goTypes,
		DependencyIndexes: file_core_role_proto_depIdxs,
		MessageInfos:      file_core_role_proto_msgTypes,
	}.Build()
	File_core_role_proto = out.File
	file_core_role_proto_goTypes = nil
	file_core_role_proto_depIdxs = nil
}
