// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: core/room.proto

package g1_protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TexasRoomInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseInfo      *RoomBaseInfo          `protobuf:"bytes,1,opt,name=base_info,json=baseInfo,proto3" json:"base_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TexasRoomInfo) Reset() {
	*x = TexasRoomInfo{}
	mi := &file_core_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TexasRoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TexasRoomInfo) ProtoMessage() {}

func (x *TexasRoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TexasRoomInfo.ProtoReflect.Descriptor instead.
func (*TexasRoomInfo) Descriptor() ([]byte, []int) {
	return file_core_room_proto_rawDescGZIP(), []int{0}
}

func (x *TexasRoomInfo) GetBaseInfo() *RoomBaseInfo {
	if x != nil {
		return x.BaseInfo
	}
	return nil
}

type RoomOwerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FigureUrl     string                 `protobuf:"bytes,1,opt,name=FigureUrl,proto3" json:"FigureUrl,omitempty"`
	Gender        string                 `protobuf:"bytes,2,opt,name=Gender,proto3" json:"Gender,omitempty"`
	NickName      string                 `protobuf:"bytes,3,opt,name=NickName,proto3" json:"NickName,omitempty"`
	Sign          string                 `protobuf:"bytes,4,opt,name=sign,proto3" json:"sign,omitempty"`               // 签名
	MaxNoble      int32                  `protobuf:"varint,5,opt,name=MaxNoble,proto3" json:"MaxNoble,omitempty"`      // VIP等级
	WeChat        string                 `protobuf:"bytes,6,opt,name=WeChat,proto3" json:"WeChat,omitempty"`           // 微信帐号
	ClubIds       []uint32               `protobuf:"varint,7,rep,packed,name=clubIds,proto3" json:"clubIds,omitempty"` // 加入的俱乐部id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomOwerInfo) Reset() {
	*x = RoomOwerInfo{}
	mi := &file_core_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomOwerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomOwerInfo) ProtoMessage() {}

func (x *RoomOwerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomOwerInfo.ProtoReflect.Descriptor instead.
func (*RoomOwerInfo) Descriptor() ([]byte, []int) {
	return file_core_room_proto_rawDescGZIP(), []int{1}
}

func (x *RoomOwerInfo) GetFigureUrl() string {
	if x != nil {
		return x.FigureUrl
	}
	return ""
}

func (x *RoomOwerInfo) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *RoomOwerInfo) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *RoomOwerInfo) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *RoomOwerInfo) GetMaxNoble() int32 {
	if x != nil {
		return x.MaxNoble
	}
	return 0
}

func (x *RoomOwerInfo) GetWeChat() string {
	if x != nil {
		return x.WeChat
	}
	return ""
}

func (x *RoomOwerInfo) GetClubIds() []uint32 {
	if x != nil {
		return x.ClubIds
	}
	return nil
}

type BuyingPlayerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Playerid      uint32                 `protobuf:"varint,1,opt,name=playerid,proto3" json:"playerid,omitempty"`
	NickName      string                 `protobuf:"bytes,2,opt,name=NickName,proto3" json:"NickName,omitempty"`
	BuyingNum     uint32                 `protobuf:"varint,3,opt,name=buyingNum,proto3" json:"buyingNum,omitempty"` // 买入数
	RoomId        uint32                 `protobuf:"varint,4,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	DwSurplusTime uint32                 `protobuf:"varint,5,opt,name=dwSurplusTime,proto3" json:"dwSurplusTime,omitempty"`        // 买入审批剩余时间(秒)
	DwEndTime     uint32                 `protobuf:"varint,6,opt,name=dwEndTime,proto3" json:"dwEndTime,omitempty"`                // 审批结束时间戳
	ClubId        uint32                 `protobuf:"varint,7,opt,name=club_id,json=clubId,proto3" json:"club_id,omitempty"`        // 俱乐部id
	VerifyId      int32                  `protobuf:"varint,10,opt,name=verify_id,json=verifyId,proto3" json:"verify_id,omitempty"` // 审批者
	FaceUrl       string                 `protobuf:"bytes,11,opt,name=face_url,json=faceUrl,proto3" json:"face_url,omitempty"`     // 头像
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuyingPlayerInfo) Reset() {
	*x = BuyingPlayerInfo{}
	mi := &file_core_room_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuyingPlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyingPlayerInfo) ProtoMessage() {}

func (x *BuyingPlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_room_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyingPlayerInfo.ProtoReflect.Descriptor instead.
func (*BuyingPlayerInfo) Descriptor() ([]byte, []int) {
	return file_core_room_proto_rawDescGZIP(), []int{2}
}

func (x *BuyingPlayerInfo) GetPlayerid() uint32 {
	if x != nil {
		return x.Playerid
	}
	return 0
}

func (x *BuyingPlayerInfo) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *BuyingPlayerInfo) GetBuyingNum() uint32 {
	if x != nil {
		return x.BuyingNum
	}
	return 0
}

func (x *BuyingPlayerInfo) GetRoomId() uint32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *BuyingPlayerInfo) GetDwSurplusTime() uint32 {
	if x != nil {
		return x.DwSurplusTime
	}
	return 0
}

func (x *BuyingPlayerInfo) GetDwEndTime() uint32 {
	if x != nil {
		return x.DwEndTime
	}
	return 0
}

func (x *BuyingPlayerInfo) GetClubId() uint32 {
	if x != nil {
		return x.ClubId
	}
	return 0
}

func (x *BuyingPlayerInfo) GetVerifyId() int32 {
	if x != nil {
		return x.VerifyId
	}
	return 0
}

func (x *BuyingPlayerInfo) GetFaceUrl() string {
	if x != nil {
		return x.FaceUrl
	}
	return ""
}

type RoomBaseInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                                         // 游戏牌局id，落地存储唯一的id，结算绑定参与的所有玩家
	RoomId        uint64                 `protobuf:"varint,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                                   // 房间id
	State         RoomState              `protobuf:"varint,3,opt,name=state,proto3,enum=g1.protocol.RoomState" json:"state,omitempty"`                        // 房间状态 //RoomState
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                                                      // 房间名
	Pwd           string                 `protobuf:"bytes,5,opt,name=pwd,proto3" json:"pwd,omitempty"`                                                        // 邀请码 or 密码
	GameId        GameTypeId             `protobuf:"varint,6,opt,name=game_id,json=gameId,proto3,enum=g1.protocol.GameTypeId" json:"game_id,omitempty"`       // 游戏id
	Stage         RoomStage              `protobuf:"varint,7,opt,name=stage,proto3,enum=g1.protocol.RoomStage" json:"stage,omitempty"`                        // RoomStage
	MaxMember     uint32                 `protobuf:"varint,8,opt,name=max_member,json=maxMember,proto3" json:"max_member,omitempty"`                          // 房间里的人数
	MaxPlayer     uint32                 `protobuf:"varint,9,opt,name=max_player,json=maxPlayer,proto3" json:"max_player,omitempty"`                          // 普通场椅子数 //SNG表示必须坐满开局的人数,MTT最大报名人数
	Zone          uint32                 `protobuf:"varint,10,opt,name=zone,proto3" json:"zone,omitempty"`                                                    // 区服组
	IsPrivate     bool                   `protobuf:"varint,11,opt,name=is_private,json=isPrivate,proto3" json:"is_private,omitempty"`                         // 是否私人局
	Blind         string                 `protobuf:"bytes,12,opt,name=blind,proto3" json:"blind,omitempty"`                                                   // 小/大盲注 例如: 1/2 小盲1 大盲2 SNG表示报名费 1000/100  报名费/服务费
	Ante          uint32                 `protobuf:"varint,13,opt,name=ante,proto3" json:"ante,omitempty"`                                                    // 前注,为0 或没有该字段表示没有前注
	GameTime      int64                  `protobuf:"varint,14,opt,name=game_time,json=gameTime,proto3" json:"game_time,omitempty"`                            // 总时间单位秒, /SNG表示涨盲时间
	IsAuth        bool                   `protobuf:"varint,15,opt,name=is_auth,json=isAuth,proto3" json:"is_auth,omitempty"`                                  // 是否授权带入,sng授权报名
	StartBb       uint32                 `protobuf:"varint,16,opt,name=start_bb,json=startBb,proto3" json:"start_bb,omitempty"`                               // 起始筹码
	StartTime     int64                  `protobuf:"varint,17,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`                         // 开始时间
	OwerId        uint64                 `protobuf:"varint,18,opt,name=ower_id,json=owerId,proto3" json:"ower_id,omitempty"`                                  // 房主uid
	IsRebuy       bool                   `protobuf:"varint,19,opt,name=is_rebuy,json=isRebuy,proto3" json:"is_rebuy,omitempty"`                               // MTT 是否 rebuy
	IsAddon       bool                   `protobuf:"varint,20,opt,name=is_addon,json=isAddon,proto3" json:"is_addon,omitempty"`                               // MTT 是否 Addon
	OwnerInfo     *PbIconDesc            `protobuf:"bytes,21,opt,name=owner_info,json=ownerInfo,proto3" json:"owner_info,omitempty"`                          // 创建者信息
	EndTime       int64                  `protobuf:"varint,22,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`                               // 游戏结束时间
	ClubId        uint32                 `protobuf:"varint,23,opt,name=club_id,json=clubId,proto3" json:"club_id,omitempty"`                                  // 俱乐部id,非俱乐部成员不允许加入
	Competition   GameCompetitionType    `protobuf:"varint,24,opt,name=competition,proto3,enum=g1.protocol.GameCompetitionType" json:"competition,omitempty"` // 比赛类型
	IsInsure      bool                   `protobuf:"varint,25,opt,name=is_insure,json=isInsure,proto3" json:"is_insure,omitempty"`                            // 是否开启保险
	Straddle      int32                  `protobuf:"varint,26,opt,name=straddle,proto3" json:"straddle,omitempty"`                                            // 是否Straddle
	IpLimit       bool                   `protobuf:"varint,27,opt,name=ip_limit,json=ipLimit,proto3" json:"ip_limit,omitempty"`                               // 是否ip限制
	CoinType      CoinType               `protobuf:"varint,28,opt,name=coin_type,json=coinType,proto3,enum=g1.protocol.CoinType" json:"coin_type,omitempty"`  // 币种类型
	Allianceid    uint32                 `protobuf:"varint,29,opt,name=allianceid,proto3" json:"allianceid,omitempty"`                                        // 联盟id
	GpsLimit      bool                   `protobuf:"varint,30,opt,name=gps_limit,json=gpsLimit,proto3" json:"gps_limit,omitempty"`                            // Gps 限制
	CreateTime    int64                  `protobuf:"varint,31,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`                      // 创建时间
	MinBuyIn      int32                  `protobuf:"varint,32,opt,name=MinBuyIn,proto3" json:"MinBuyIn,omitempty"`                                            // 最小买入
	MaxBuyIn      int32                  `protobuf:"varint,33,opt,name=MaxBuyIn,proto3" json:"MaxBuyIn,omitempty"`                                            // 最大买入
	CurPlayerNum  uint32                 `protobuf:"varint,34,opt,name=cur_player_num,json=curPlayerNum,proto3" json:"cur_player_num,omitempty"`              // 当前玩家人数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomBaseInfo) Reset() {
	*x = RoomBaseInfo{}
	mi := &file_core_room_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomBaseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomBaseInfo) ProtoMessage() {}

func (x *RoomBaseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_room_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomBaseInfo.ProtoReflect.Descriptor instead.
func (*RoomBaseInfo) Descriptor() ([]byte, []int) {
	return file_core_room_proto_rawDescGZIP(), []int{3}
}

func (x *RoomBaseInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RoomBaseInfo) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomBaseInfo) GetState() RoomState {
	if x != nil {
		return x.State
	}
	return RoomState_WAITSTART
}

func (x *RoomBaseInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomBaseInfo) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

func (x *RoomBaseInfo) GetGameId() GameTypeId {
	if x != nil {
		return x.GameId
	}
	return GameTypeId_TEXAS_MODE_START
}

func (x *RoomBaseInfo) GetStage() RoomStage {
	if x != nil {
		return x.Stage
	}
	return RoomStage_Free
}

func (x *RoomBaseInfo) GetMaxMember() uint32 {
	if x != nil {
		return x.MaxMember
	}
	return 0
}

func (x *RoomBaseInfo) GetMaxPlayer() uint32 {
	if x != nil {
		return x.MaxPlayer
	}
	return 0
}

func (x *RoomBaseInfo) GetZone() uint32 {
	if x != nil {
		return x.Zone
	}
	return 0
}

func (x *RoomBaseInfo) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *RoomBaseInfo) GetBlind() string {
	if x != nil {
		return x.Blind
	}
	return ""
}

func (x *RoomBaseInfo) GetAnte() uint32 {
	if x != nil {
		return x.Ante
	}
	return 0
}

func (x *RoomBaseInfo) GetGameTime() int64 {
	if x != nil {
		return x.GameTime
	}
	return 0
}

func (x *RoomBaseInfo) GetIsAuth() bool {
	if x != nil {
		return x.IsAuth
	}
	return false
}

func (x *RoomBaseInfo) GetStartBb() uint32 {
	if x != nil {
		return x.StartBb
	}
	return 0
}

func (x *RoomBaseInfo) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *RoomBaseInfo) GetOwerId() uint64 {
	if x != nil {
		return x.OwerId
	}
	return 0
}

func (x *RoomBaseInfo) GetIsRebuy() bool {
	if x != nil {
		return x.IsRebuy
	}
	return false
}

func (x *RoomBaseInfo) GetIsAddon() bool {
	if x != nil {
		return x.IsAddon
	}
	return false
}

func (x *RoomBaseInfo) GetOwnerInfo() *PbIconDesc {
	if x != nil {
		return x.OwnerInfo
	}
	return nil
}

func (x *RoomBaseInfo) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *RoomBaseInfo) GetClubId() uint32 {
	if x != nil {
		return x.ClubId
	}
	return 0
}

func (x *RoomBaseInfo) GetCompetition() GameCompetitionType {
	if x != nil {
		return x.Competition
	}
	return GameCompetitionType_NORMAL
}

func (x *RoomBaseInfo) GetIsInsure() bool {
	if x != nil {
		return x.IsInsure
	}
	return false
}

func (x *RoomBaseInfo) GetStraddle() int32 {
	if x != nil {
		return x.Straddle
	}
	return 0
}

func (x *RoomBaseInfo) GetIpLimit() bool {
	if x != nil {
		return x.IpLimit
	}
	return false
}

func (x *RoomBaseInfo) GetCoinType() CoinType {
	if x != nil {
		return x.CoinType
	}
	return CoinType_COIN_NONE
}

func (x *RoomBaseInfo) GetAllianceid() uint32 {
	if x != nil {
		return x.Allianceid
	}
	return 0
}

func (x *RoomBaseInfo) GetGpsLimit() bool {
	if x != nil {
		return x.GpsLimit
	}
	return false
}

func (x *RoomBaseInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *RoomBaseInfo) GetMinBuyIn() int32 {
	if x != nil {
		return x.MinBuyIn
	}
	return 0
}

func (x *RoomBaseInfo) GetMaxBuyIn() int32 {
	if x != nil {
		return x.MaxBuyIn
	}
	return 0
}

func (x *RoomBaseInfo) GetCurPlayerNum() uint32 {
	if x != nil {
		return x.CurPlayerNum
	}
	return 0
}

// 大厅房间展示信息
// ROOM_CENTER_INNER_UPDATE_ROOM_INFO_REQ
type RoomShowInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        uint64                 `protobuf:"varint,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Base          *RoomBaseInfo          `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomShowInfo) Reset() {
	*x = RoomShowInfo{}
	mi := &file_core_room_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomShowInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomShowInfo) ProtoMessage() {}

func (x *RoomShowInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_room_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomShowInfo.ProtoReflect.Descriptor instead.
func (*RoomShowInfo) Descriptor() ([]byte, []int) {
	return file_core_room_proto_rawDescGZIP(), []int{4}
}

func (x *RoomShowInfo) GetRoomId() uint64 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

func (x *RoomShowInfo) GetBase() *RoomBaseInfo {
	if x != nil {
		return x.Base
	}
	return nil
}

type InnerCreateRoomReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *RoomBaseInfo          `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InnerCreateRoomReq) Reset() {
	*x = InnerCreateRoomReq{}
	mi := &file_core_room_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InnerCreateRoomReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerCreateRoomReq) ProtoMessage() {}

func (x *InnerCreateRoomReq) ProtoReflect() protoreflect.Message {
	mi := &file_core_room_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerCreateRoomReq.ProtoReflect.Descriptor instead.
func (*InnerCreateRoomReq) Descriptor() ([]byte, []int) {
	return file_core_room_proto_rawDescGZIP(), []int{5}
}

func (x *InnerCreateRoomReq) GetBase() *RoomBaseInfo {
	if x != nil {
		return x.Base
	}
	return nil
}

var File_core_room_proto protoreflect.FileDescriptor

const file_core_room_proto_rawDesc = "" +
	"\n" +
	"\x0fcore/room.proto\x12\vg1.protocol\x1a\x14core/game_enum.proto\x1a\x0fcore/role.proto\"G\n" +
	"\rTexasRoomInfo\x126\n" +
	"\tbase_info\x18\x01 \x01(\v2\x19.g1.protocol.RoomBaseInfoR\bbaseInfo\"\xc2\x01\n" +
	"\fRoomOwerInfo\x12\x1c\n" +
	"\tFigureUrl\x18\x01 \x01(\tR\tFigureUrl\x12\x16\n" +
	"\x06Gender\x18\x02 \x01(\tR\x06Gender\x12\x1a\n" +
	"\bNickName\x18\x03 \x01(\tR\bNickName\x12\x12\n" +
	"\x04sign\x18\x04 \x01(\tR\x04sign\x12\x1a\n" +
	"\bMaxNoble\x18\x05 \x01(\x05R\bMaxNoble\x12\x16\n" +
	"\x06WeChat\x18\x06 \x01(\tR\x06WeChat\x12\x18\n" +
	"\aclubIds\x18\a \x03(\rR\aclubIds\"\x96\x02\n" +
	"\x10BuyingPlayerInfo\x12\x1a\n" +
	"\bplayerid\x18\x01 \x01(\rR\bplayerid\x12\x1a\n" +
	"\bNickName\x18\x02 \x01(\tR\bNickName\x12\x1c\n" +
	"\tbuyingNum\x18\x03 \x01(\rR\tbuyingNum\x12\x17\n" +
	"\aroom_id\x18\x04 \x01(\rR\x06roomId\x12$\n" +
	"\rdwSurplusTime\x18\x05 \x01(\rR\rdwSurplusTime\x12\x1c\n" +
	"\tdwEndTime\x18\x06 \x01(\rR\tdwEndTime\x12\x17\n" +
	"\aclub_id\x18\a \x01(\rR\x06clubId\x12\x1b\n" +
	"\tverify_id\x18\n" +
	" \x01(\x05R\bverifyId\x12\x19\n" +
	"\bface_url\x18\v \x01(\tR\afaceUrl\"\xb9\b\n" +
	"\fRoomBaseInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\x04R\x06roomId\x12,\n" +
	"\x05state\x18\x03 \x01(\x0e2\x16.g1.protocol.RoomStateR\x05state\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x10\n" +
	"\x03pwd\x18\x05 \x01(\tR\x03pwd\x120\n" +
	"\agame_id\x18\x06 \x01(\x0e2\x17.g1.protocol.GameTypeIdR\x06gameId\x12,\n" +
	"\x05stage\x18\a \x01(\x0e2\x16.g1.protocol.RoomStageR\x05stage\x12\x1d\n" +
	"\n" +
	"max_member\x18\b \x01(\rR\tmaxMember\x12\x1d\n" +
	"\n" +
	"max_player\x18\t \x01(\rR\tmaxPlayer\x12\x12\n" +
	"\x04zone\x18\n" +
	" \x01(\rR\x04zone\x12\x1d\n" +
	"\n" +
	"is_private\x18\v \x01(\bR\tisPrivate\x12\x14\n" +
	"\x05blind\x18\f \x01(\tR\x05blind\x12\x12\n" +
	"\x04ante\x18\r \x01(\rR\x04ante\x12\x1b\n" +
	"\tgame_time\x18\x0e \x01(\x03R\bgameTime\x12\x17\n" +
	"\ais_auth\x18\x0f \x01(\bR\x06isAuth\x12\x19\n" +
	"\bstart_bb\x18\x10 \x01(\rR\astartBb\x12\x1d\n" +
	"\n" +
	"start_time\x18\x11 \x01(\x03R\tstartTime\x12\x17\n" +
	"\aower_id\x18\x12 \x01(\x04R\x06owerId\x12\x19\n" +
	"\bis_rebuy\x18\x13 \x01(\bR\aisRebuy\x12\x19\n" +
	"\bis_addon\x18\x14 \x01(\bR\aisAddon\x126\n" +
	"\n" +
	"owner_info\x18\x15 \x01(\v2\x17.g1.protocol.PbIconDescR\townerInfo\x12\x19\n" +
	"\bend_time\x18\x16 \x01(\x03R\aendTime\x12\x17\n" +
	"\aclub_id\x18\x17 \x01(\rR\x06clubId\x12B\n" +
	"\vcompetition\x18\x18 \x01(\x0e2 .g1.protocol.GameCompetitionTypeR\vcompetition\x12\x1b\n" +
	"\tis_insure\x18\x19 \x01(\bR\bisInsure\x12\x1a\n" +
	"\bstraddle\x18\x1a \x01(\x05R\bstraddle\x12\x19\n" +
	"\bip_limit\x18\x1b \x01(\bR\aipLimit\x122\n" +
	"\tcoin_type\x18\x1c \x01(\x0e2\x15.g1.protocol.CoinTypeR\bcoinType\x12\x1e\n" +
	"\n" +
	"allianceid\x18\x1d \x01(\rR\n" +
	"allianceid\x12\x1b\n" +
	"\tgps_limit\x18\x1e \x01(\bR\bgpsLimit\x12\x1f\n" +
	"\vcreate_time\x18\x1f \x01(\x03R\n" +
	"createTime\x12\x1a\n" +
	"\bMinBuyIn\x18  \x01(\x05R\bMinBuyIn\x12\x1a\n" +
	"\bMaxBuyIn\x18! \x01(\x05R\bMaxBuyIn\x12$\n" +
	"\x0ecur_player_num\x18\" \x01(\rR\fcurPlayerNum\"V\n" +
	"\fRoomShowInfo\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\x04R\x06roomId\x12-\n" +
	"\x04base\x18\x02 \x01(\v2\x19.g1.protocol.RoomBaseInfoR\x04base\"C\n" +
	"\x12InnerCreateRoomReq\x12-\n" +
	"\x04base\x18\x01 \x01(\v2\x19.g1.protocol.RoomBaseInfoR\x04baseB9Z7github.com/Iori372552686/g1_common/protocol;g1_protocolb\x06proto3"

var (
	file_core_room_proto_rawDescOnce sync.Once
	file_core_room_proto_rawDescData []byte
)

func file_core_room_proto_rawDescGZIP() []byte {
	file_core_room_proto_rawDescOnce.Do(func() {
		file_core_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_room_proto_rawDesc), len(file_core_room_proto_rawDesc)))
	})
	return file_core_room_proto_rawDescData
}

var file_core_room_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_core_room_proto_goTypes = []any{
	(*TexasRoomInfo)(nil),      // 0: g1.protocol.TexasRoomInfo
	(*RoomOwerInfo)(nil),       // 1: g1.protocol.RoomOwerInfo
	(*BuyingPlayerInfo)(nil),   // 2: g1.protocol.BuyingPlayerInfo
	(*RoomBaseInfo)(nil),       // 3: g1.protocol.RoomBaseInfo
	(*RoomShowInfo)(nil),       // 4: g1.protocol.RoomShowInfo
	(*InnerCreateRoomReq)(nil), // 5: g1.protocol.InnerCreateRoomReq
	(RoomState)(0),             // 6: g1.protocol.RoomState
	(GameTypeId)(0),            // 7: g1.protocol.GameTypeId
	(RoomStage)(0),             // 8: g1.protocol.RoomStage
	(*PbIconDesc)(nil),         // 9: g1.protocol.PbIconDesc
	(GameCompetitionType)(0),   // 10: g1.protocol.GameCompetitionType
	(CoinType)(0),              // 11: g1.protocol.CoinType
}
var file_core_room_proto_depIdxs = []int32{
	3,  // 0: g1.protocol.TexasRoomInfo.base_info:type_name -> g1.protocol.RoomBaseInfo
	6,  // 1: g1.protocol.RoomBaseInfo.state:type_name -> g1.protocol.RoomState
	7,  // 2: g1.protocol.RoomBaseInfo.game_id:type_name -> g1.protocol.GameTypeId
	8,  // 3: g1.protocol.RoomBaseInfo.stage:type_name -> g1.protocol.RoomStage
	9,  // 4: g1.protocol.RoomBaseInfo.owner_info:type_name -> g1.protocol.PbIconDesc
	10, // 5: g1.protocol.RoomBaseInfo.competition:type_name -> g1.protocol.GameCompetitionType
	11, // 6: g1.protocol.RoomBaseInfo.coin_type:type_name -> g1.protocol.CoinType
	3,  // 7: g1.protocol.RoomShowInfo.base:type_name -> g1.protocol.RoomBaseInfo
	3,  // 8: g1.protocol.InnerCreateRoomReq.base:type_name -> g1.protocol.RoomBaseInfo
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_core_room_proto_init() }
func file_core_room_proto_init() {
	if File_core_room_proto != nil {
		return
	}
	file_core_game_enum_proto_init()
	file_core_role_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_room_proto_rawDesc), len(file_core_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_room_proto_goTypes,
		DependencyIndexes: file_core_room_proto_depIdxs,
		MessageInfos:      file_core_room_proto_msgTypes,
	}.Build()
	File_core_room_proto = out.File
	file_core_room_proto_goTypes = nil
	file_core_room_proto_depIdxs = nil
}
