//
// 本代码由xlsx工具生成，请勿手动修改

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: config/texas.proto

package g1_protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PBARRTexasFloat_1Eb6F30C5 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=Values,proto3" json:"Values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBARRTexasFloat_1Eb6F30C5) Reset() {
	*x = PBARRTexasFloat_1Eb6F30C5{}
	mi := &file_config_texas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBARRTexasFloat_1Eb6F30C5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBARRTexasFloat_1Eb6F30C5) ProtoMessage() {}

func (x *PBARRTexasFloat_1Eb6F30C5) ProtoReflect() protoreflect.Message {
	mi := &file_config_texas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBARRTexasFloat_1Eb6F30C5.ProtoReflect.Descriptor instead.
func (*PBARRTexasFloat_1Eb6F30C5) Descriptor() ([]byte, []int) {
	return file_config_texas_proto_rawDescGZIP(), []int{0}
}

func (x *PBARRTexasFloat_1Eb6F30C5) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type PBARRTexasString_1F5F72933 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=Values,proto3" json:"Values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBARRTexasString_1F5F72933) Reset() {
	*x = PBARRTexasString_1F5F72933{}
	mi := &file_config_texas_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBARRTexasString_1F5F72933) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBARRTexasString_1F5F72933) ProtoMessage() {}

func (x *PBARRTexasString_1F5F72933) ProtoReflect() protoreflect.Message {
	mi := &file_config_texas_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBARRTexasString_1F5F72933.ProtoReflect.Descriptor instead.
func (*PBARRTexasString_1F5F72933) Descriptor() ([]byte, []int) {
	return file_config_texas_proto_rawDescGZIP(), []int{1}
}

func (x *PBARRTexasString_1F5F72933) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type PBARRTexasFloat_2Eb6F30C5 struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Values        []*PBARRTexasFloat_1Eb6F30C5 `protobuf:"bytes,1,rep,name=Values,proto3" json:"Values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PBARRTexasFloat_2Eb6F30C5) Reset() {
	*x = PBARRTexasFloat_2Eb6F30C5{}
	mi := &file_config_texas_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PBARRTexasFloat_2Eb6F30C5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBARRTexasFloat_2Eb6F30C5) ProtoMessage() {}

func (x *PBARRTexasFloat_2Eb6F30C5) ProtoReflect() protoreflect.Message {
	mi := &file_config_texas_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBARRTexasFloat_2Eb6F30C5.ProtoReflect.Descriptor instead.
func (*PBARRTexasFloat_2Eb6F30C5) Descriptor() ([]byte, []int) {
	return file_config_texas_proto_rawDescGZIP(), []int{2}
}

func (x *PBARRTexasFloat_2Eb6F30C5) GetValues() []*PBARRTexasFloat_1Eb6F30C5 {
	if x != nil {
		return x.Values
	}
	return nil
}

type TexasConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoomStage      int32                  `protobuf:"varint,1,opt,name=RoomStage,proto3" json:"RoomStage,omitempty"`             // 房间类型
	CoinType       int32                  `protobuf:"varint,2,opt,name=CoinType,proto3" json:"CoinType,omitempty"`               // 货币类型
	RoomKeepLive   int64                  `protobuf:"varint,3,opt,name=RoomKeepLive,proto3" json:"RoomKeepLive,omitempty"`       // 房间存在时长(分钟)
	SmallBlind     int64                  `protobuf:"varint,4,opt,name=SmallBlind,proto3" json:"SmallBlind,omitempty"`           // 小盲注
	BigBlind       int64                  `protobuf:"varint,5,opt,name=BigBlind,proto3" json:"BigBlind,omitempty"`               // 大盲注
	MinBuyIn       int32                  `protobuf:"varint,6,opt,name=MinBuyIn,proto3" json:"MinBuyIn,omitempty"`               // 最小买入筹码
	MaxBuyIn       int32                  `protobuf:"varint,7,opt,name=MaxBuyIn,proto3" json:"MaxBuyIn,omitempty"`               // 最大买入筹码
	RakeRate       int64                  `protobuf:"varint,8,opt,name=RakeRate,proto3" json:"RakeRate,omitempty"`               // 每局抽水万分比
	MaxPlayerCount uint32                 `protobuf:"varint,9,opt,name=MaxPlayerCount,proto3" json:"MaxPlayerCount,omitempty"`   // 最大玩家人数
	RakeUpLimit    []int64                `protobuf:"varint,10,rep,packed,name=RakeUpLimit,proto3" json:"RakeUpLimit,omitempty"` // 每局多少人的抽水上限，2人，3人等抽水
	MaxRoomCount   uint32                 `protobuf:"varint,11,opt,name=MaxRoomCount,proto3" json:"MaxRoomCount,omitempty"`      // 最大房间人数
	IsNoFlopNoDrop bool                   `protobuf:"varint,12,opt,name=IsNoFlopNoDrop,proto3" json:"IsNoFlopNoDrop,omitempty"`  // 是否开启
	IsTest         bool                   `protobuf:"varint,13,opt,name=IsTest,proto3" json:"IsTest,omitempty"`                  // 是否为测试
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TexasConfig) Reset() {
	*x = TexasConfig{}
	mi := &file_config_texas_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TexasConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TexasConfig) ProtoMessage() {}

func (x *TexasConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_texas_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TexasConfig.ProtoReflect.Descriptor instead.
func (*TexasConfig) Descriptor() ([]byte, []int) {
	return file_config_texas_proto_rawDescGZIP(), []int{3}
}

func (x *TexasConfig) GetRoomStage() int32 {
	if x != nil {
		return x.RoomStage
	}
	return 0
}

func (x *TexasConfig) GetCoinType() int32 {
	if x != nil {
		return x.CoinType
	}
	return 0
}

func (x *TexasConfig) GetRoomKeepLive() int64 {
	if x != nil {
		return x.RoomKeepLive
	}
	return 0
}

func (x *TexasConfig) GetSmallBlind() int64 {
	if x != nil {
		return x.SmallBlind
	}
	return 0
}

func (x *TexasConfig) GetBigBlind() int64 {
	if x != nil {
		return x.BigBlind
	}
	return 0
}

func (x *TexasConfig) GetMinBuyIn() int32 {
	if x != nil {
		return x.MinBuyIn
	}
	return 0
}

func (x *TexasConfig) GetMaxBuyIn() int32 {
	if x != nil {
		return x.MaxBuyIn
	}
	return 0
}

func (x *TexasConfig) GetRakeRate() int64 {
	if x != nil {
		return x.RakeRate
	}
	return 0
}

func (x *TexasConfig) GetMaxPlayerCount() uint32 {
	if x != nil {
		return x.MaxPlayerCount
	}
	return 0
}

func (x *TexasConfig) GetRakeUpLimit() []int64 {
	if x != nil {
		return x.RakeUpLimit
	}
	return nil
}

func (x *TexasConfig) GetMaxRoomCount() uint32 {
	if x != nil {
		return x.MaxRoomCount
	}
	return 0
}

func (x *TexasConfig) GetIsNoFlopNoDrop() bool {
	if x != nil {
		return x.IsNoFlopNoDrop
	}
	return false
}

func (x *TexasConfig) GetIsTest() bool {
	if x != nil {
		return x.IsTest
	}
	return false
}

type TexasConfigAry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ary           []*TexasConfig         `protobuf:"bytes,1,rep,name=Ary,proto3" json:"Ary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TexasConfigAry) Reset() {
	*x = TexasConfigAry{}
	mi := &file_config_texas_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TexasConfigAry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TexasConfigAry) ProtoMessage() {}

func (x *TexasConfigAry) ProtoReflect() protoreflect.Message {
	mi := &file_config_texas_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TexasConfigAry.ProtoReflect.Descriptor instead.
func (*TexasConfigAry) Descriptor() ([]byte, []int) {
	return file_config_texas_proto_rawDescGZIP(), []int{4}
}

func (x *TexasConfigAry) GetAry() []*TexasConfig {
	if x != nil {
		return x.Ary
	}
	return nil
}

type TexasMachineConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GameId          int32                  `protobuf:"varint,1,opt,name=GameId,proto3" json:"GameId,omitempty"`                   // 游戏id
	StartDuration   int64                  `protobuf:"varint,2,opt,name=StartDuration,proto3" json:"StartDuration,omitempty"`     // 开始时长(秒)
	PreFlopDuration int64                  `protobuf:"varint,3,opt,name=PreFlopDuration,proto3" json:"PreFlopDuration,omitempty"` // 翻牌前时长
	FlopDuration    int64                  `protobuf:"varint,4,opt,name=FlopDuration,proto3" json:"FlopDuration,omitempty"`       // 翻牌下注轮时长
	TurnDuration    int64                  `protobuf:"varint,5,opt,name=TurnDuration,proto3" json:"TurnDuration,omitempty"`       // 转牌下注轮时长
	RiverDuration   int64                  `protobuf:"varint,6,opt,name=RiverDuration,proto3" json:"RiverDuration,omitempty"`     // 河牌下注轮时长
	EndDuration     int64                  `protobuf:"varint,7,opt,name=EndDuration,proto3" json:"EndDuration,omitempty"`         // 结算时长
	DefaultDuration int64                  `protobuf:"varint,8,opt,name=DefaultDuration,proto3" json:"DefaultDuration,omitempty"` // 默认时长
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TexasMachineConfig) Reset() {
	*x = TexasMachineConfig{}
	mi := &file_config_texas_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TexasMachineConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TexasMachineConfig) ProtoMessage() {}

func (x *TexasMachineConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_texas_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TexasMachineConfig.ProtoReflect.Descriptor instead.
func (*TexasMachineConfig) Descriptor() ([]byte, []int) {
	return file_config_texas_proto_rawDescGZIP(), []int{5}
}

func (x *TexasMachineConfig) GetGameId() int32 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *TexasMachineConfig) GetStartDuration() int64 {
	if x != nil {
		return x.StartDuration
	}
	return 0
}

func (x *TexasMachineConfig) GetPreFlopDuration() int64 {
	if x != nil {
		return x.PreFlopDuration
	}
	return 0
}

func (x *TexasMachineConfig) GetFlopDuration() int64 {
	if x != nil {
		return x.FlopDuration
	}
	return 0
}

func (x *TexasMachineConfig) GetTurnDuration() int64 {
	if x != nil {
		return x.TurnDuration
	}
	return 0
}

func (x *TexasMachineConfig) GetRiverDuration() int64 {
	if x != nil {
		return x.RiverDuration
	}
	return 0
}

func (x *TexasMachineConfig) GetEndDuration() int64 {
	if x != nil {
		return x.EndDuration
	}
	return 0
}

func (x *TexasMachineConfig) GetDefaultDuration() int64 {
	if x != nil {
		return x.DefaultDuration
	}
	return 0
}

type TexasMachineConfigAry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ary           []*TexasMachineConfig  `protobuf:"bytes,1,rep,name=Ary,proto3" json:"Ary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TexasMachineConfigAry) Reset() {
	*x = TexasMachineConfigAry{}
	mi := &file_config_texas_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TexasMachineConfigAry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TexasMachineConfigAry) ProtoMessage() {}

func (x *TexasMachineConfigAry) ProtoReflect() protoreflect.Message {
	mi := &file_config_texas_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TexasMachineConfigAry.ProtoReflect.Descriptor instead.
func (*TexasMachineConfigAry) Descriptor() ([]byte, []int) {
	return file_config_texas_proto_rawDescGZIP(), []int{6}
}

func (x *TexasMachineConfigAry) GetAry() []*TexasMachineConfig {
	if x != nil {
		return x.Ary
	}
	return nil
}

type TexasTestConfig struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Round         uint32                        `protobuf:"varint,1,opt,name=Round,proto3" json:"Round,omitempty"`     // 第几轮牌局
	Publics       []*PBARRTexasString_1F5F72933 `protobuf:"bytes,2,rep,name=Publics,proto3" json:"Publics,omitempty"`  // 公共牌
	Chair1        []*PBARRTexasFloat_2Eb6F30C5  `protobuf:"bytes,3,rep,name=Chair1,proto3" json:"Chair1,omitempty"`    // 玩家手牌
	Chair2        string                        `protobuf:"bytes,4,opt,name=Chair2,proto3" json:"Chair2,omitempty"`    // 玩家手牌
	Chair3        string                        `protobuf:"bytes,5,opt,name=Chair3,proto3" json:"Chair3,omitempty"`    // 玩家手牌
	Chair4        string                        `protobuf:"bytes,6,opt,name=Chair4,proto3" json:"Chair4,omitempty"`    // 玩家手牌
	Chair5        string                        `protobuf:"bytes,7,opt,name=Chair5,proto3" json:"Chair5,omitempty"`    // 玩家手牌
	Chair6        string                        `protobuf:"bytes,8,opt,name=Chair6,proto3" json:"Chair6,omitempty"`    // 玩家手牌
	Chair7        string                        `protobuf:"bytes,9,opt,name=Chair7,proto3" json:"Chair7,omitempty"`    // 玩家手牌
	Chair8        string                        `protobuf:"bytes,10,opt,name=Chair8,proto3" json:"Chair8,omitempty"`   // 玩家手牌
	Chair9        string                        `protobuf:"bytes,11,opt,name=Chair9,proto3" json:"Chair9,omitempty"`   // 玩家手牌
	Chair10       string                        `protobuf:"bytes,12,opt,name=Chair10,proto3" json:"Chair10,omitempty"` // 玩家手牌
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TexasTestConfig) Reset() {
	*x = TexasTestConfig{}
	mi := &file_config_texas_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TexasTestConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TexasTestConfig) ProtoMessage() {}

func (x *TexasTestConfig) ProtoReflect() protoreflect.Message {
	mi := &file_config_texas_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TexasTestConfig.ProtoReflect.Descriptor instead.
func (*TexasTestConfig) Descriptor() ([]byte, []int) {
	return file_config_texas_proto_rawDescGZIP(), []int{7}
}

func (x *TexasTestConfig) GetRound() uint32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *TexasTestConfig) GetPublics() []*PBARRTexasString_1F5F72933 {
	if x != nil {
		return x.Publics
	}
	return nil
}

func (x *TexasTestConfig) GetChair1() []*PBARRTexasFloat_2Eb6F30C5 {
	if x != nil {
		return x.Chair1
	}
	return nil
}

func (x *TexasTestConfig) GetChair2() string {
	if x != nil {
		return x.Chair2
	}
	return ""
}

func (x *TexasTestConfig) GetChair3() string {
	if x != nil {
		return x.Chair3
	}
	return ""
}

func (x *TexasTestConfig) GetChair4() string {
	if x != nil {
		return x.Chair4
	}
	return ""
}

func (x *TexasTestConfig) GetChair5() string {
	if x != nil {
		return x.Chair5
	}
	return ""
}

func (x *TexasTestConfig) GetChair6() string {
	if x != nil {
		return x.Chair6
	}
	return ""
}

func (x *TexasTestConfig) GetChair7() string {
	if x != nil {
		return x.Chair7
	}
	return ""
}

func (x *TexasTestConfig) GetChair8() string {
	if x != nil {
		return x.Chair8
	}
	return ""
}

func (x *TexasTestConfig) GetChair9() string {
	if x != nil {
		return x.Chair9
	}
	return ""
}

func (x *TexasTestConfig) GetChair10() string {
	if x != nil {
		return x.Chair10
	}
	return ""
}

type TexasTestConfigAry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ary           []*TexasTestConfig     `protobuf:"bytes,1,rep,name=Ary,proto3" json:"Ary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TexasTestConfigAry) Reset() {
	*x = TexasTestConfigAry{}
	mi := &file_config_texas_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TexasTestConfigAry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TexasTestConfigAry) ProtoMessage() {}

func (x *TexasTestConfigAry) ProtoReflect() protoreflect.Message {
	mi := &file_config_texas_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TexasTestConfigAry.ProtoReflect.Descriptor instead.
func (*TexasTestConfigAry) Descriptor() ([]byte, []int) {
	return file_config_texas_proto_rawDescGZIP(), []int{8}
}

func (x *TexasTestConfigAry) GetAry() []*TexasTestConfig {
	if x != nil {
		return x.Ary
	}
	return nil
}

var File_config_texas_proto protoreflect.FileDescriptor

const file_config_texas_proto_rawDesc = "" +
	"\n" +
	"\x12config/texas.proto\x12\vg1.protocol\"6\n" +
	"\x1cPBARR_texas_float_1_eb6f30c5\x12\x16\n" +
	"\x06Values\x18\x01 \x03(\x02R\x06Values\"7\n" +
	"\x1dPBARR_texas_string_1_f5f72933\x12\x16\n" +
	"\x06Values\x18\x01 \x03(\tR\x06Values\"a\n" +
	"\x1cPBARR_texas_float_2_eb6f30c5\x12A\n" +
	"\x06Values\x18\x01 \x03(\v2).g1.protocol.PBARR_texas_float_1_eb6f30c5R\x06Values\"\xa9\x03\n" +
	"\vTexasConfig\x12\x1c\n" +
	"\tRoomStage\x18\x01 \x01(\x05R\tRoomStage\x12\x1a\n" +
	"\bCoinType\x18\x02 \x01(\x05R\bCoinType\x12\"\n" +
	"\fRoomKeepLive\x18\x03 \x01(\x03R\fRoomKeepLive\x12\x1e\n" +
	"\n" +
	"SmallBlind\x18\x04 \x01(\x03R\n" +
	"SmallBlind\x12\x1a\n" +
	"\bBigBlind\x18\x05 \x01(\x03R\bBigBlind\x12\x1a\n" +
	"\bMinBuyIn\x18\x06 \x01(\x05R\bMinBuyIn\x12\x1a\n" +
	"\bMaxBuyIn\x18\a \x01(\x05R\bMaxBuyIn\x12\x1a\n" +
	"\bRakeRate\x18\b \x01(\x03R\bRakeRate\x12&\n" +
	"\x0eMaxPlayerCount\x18\t \x01(\rR\x0eMaxPlayerCount\x12 \n" +
	"\vRakeUpLimit\x18\n" +
	" \x03(\x03R\vRakeUpLimit\x12\"\n" +
	"\fMaxRoomCount\x18\v \x01(\rR\fMaxRoomCount\x12&\n" +
	"\x0eIsNoFlopNoDrop\x18\f \x01(\bR\x0eIsNoFlopNoDrop\x12\x16\n" +
	"\x06IsTest\x18\r \x01(\bR\x06IsTest\"<\n" +
	"\x0eTexasConfigAry\x12*\n" +
	"\x03Ary\x18\x01 \x03(\v2\x18.g1.protocol.TexasConfigR\x03Ary\"\xb6\x02\n" +
	"\x12TexasMachineConfig\x12\x16\n" +
	"\x06GameId\x18\x01 \x01(\x05R\x06GameId\x12$\n" +
	"\rStartDuration\x18\x02 \x01(\x03R\rStartDuration\x12(\n" +
	"\x0fPreFlopDuration\x18\x03 \x01(\x03R\x0fPreFlopDuration\x12\"\n" +
	"\fFlopDuration\x18\x04 \x01(\x03R\fFlopDuration\x12\"\n" +
	"\fTurnDuration\x18\x05 \x01(\x03R\fTurnDuration\x12$\n" +
	"\rRiverDuration\x18\x06 \x01(\x03R\rRiverDuration\x12 \n" +
	"\vEndDuration\x18\a \x01(\x03R\vEndDuration\x12(\n" +
	"\x0fDefaultDuration\x18\b \x01(\x03R\x0fDefaultDuration\"J\n" +
	"\x15TexasMachineConfigAry\x121\n" +
	"\x03Ary\x18\x01 \x03(\v2\x1f.g1.protocol.TexasMachineConfigR\x03Ary\"\x8a\x03\n" +
	"\x0fTexasTestConfig\x12\x14\n" +
	"\x05Round\x18\x01 \x01(\rR\x05Round\x12D\n" +
	"\aPublics\x18\x02 \x03(\v2*.g1.protocol.PBARR_texas_string_1_f5f72933R\aPublics\x12A\n" +
	"\x06Chair1\x18\x03 \x03(\v2).g1.protocol.PBARR_texas_float_2_eb6f30c5R\x06Chair1\x12\x16\n" +
	"\x06Chair2\x18\x04 \x01(\tR\x06Chair2\x12\x16\n" +
	"\x06Chair3\x18\x05 \x01(\tR\x06Chair3\x12\x16\n" +
	"\x06Chair4\x18\x06 \x01(\tR\x06Chair4\x12\x16\n" +
	"\x06Chair5\x18\a \x01(\tR\x06Chair5\x12\x16\n" +
	"\x06Chair6\x18\b \x01(\tR\x06Chair6\x12\x16\n" +
	"\x06Chair7\x18\t \x01(\tR\x06Chair7\x12\x16\n" +
	"\x06Chair8\x18\n" +
	" \x01(\tR\x06Chair8\x12\x16\n" +
	"\x06Chair9\x18\v \x01(\tR\x06Chair9\x12\x18\n" +
	"\aChair10\x18\f \x01(\tR\aChair10\"D\n" +
	"\x12TexasTestConfigAry\x12.\n" +
	"\x03Ary\x18\x01 \x03(\v2\x1c.g1.protocol.TexasTestConfigR\x03AryB9Z7github.com/Iori372552686/g1_common/protocol;g1_protocolb\x06proto3"

var (
	file_config_texas_proto_rawDescOnce sync.Once
	file_config_texas_proto_rawDescData []byte
)

func file_config_texas_proto_rawDescGZIP() []byte {
	file_config_texas_proto_rawDescOnce.Do(func() {
		file_config_texas_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_texas_proto_rawDesc), len(file_config_texas_proto_rawDesc)))
	})
	return file_config_texas_proto_rawDescData
}

var file_config_texas_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_config_texas_proto_goTypes = []any{
	(*PBARRTexasFloat_1Eb6F30C5)(nil),  // 0: g1.protocol.PBARR_texas_float_1_eb6f30c5
	(*PBARRTexasString_1F5F72933)(nil), // 1: g1.protocol.PBARR_texas_string_1_f5f72933
	(*PBARRTexasFloat_2Eb6F30C5)(nil),  // 2: g1.protocol.PBARR_texas_float_2_eb6f30c5
	(*TexasConfig)(nil),                // 3: g1.protocol.TexasConfig
	(*TexasConfigAry)(nil),             // 4: g1.protocol.TexasConfigAry
	(*TexasMachineConfig)(nil),         // 5: g1.protocol.TexasMachineConfig
	(*TexasMachineConfigAry)(nil),      // 6: g1.protocol.TexasMachineConfigAry
	(*TexasTestConfig)(nil),            // 7: g1.protocol.TexasTestConfig
	(*TexasTestConfigAry)(nil),         // 8: g1.protocol.TexasTestConfigAry
}
var file_config_texas_proto_depIdxs = []int32{
	0, // 0: g1.protocol.PBARR_texas_float_2_eb6f30c5.Values:type_name -> g1.protocol.PBARR_texas_float_1_eb6f30c5
	3, // 1: g1.protocol.TexasConfigAry.Ary:type_name -> g1.protocol.TexasConfig
	5, // 2: g1.protocol.TexasMachineConfigAry.Ary:type_name -> g1.protocol.TexasMachineConfig
	1, // 3: g1.protocol.TexasTestConfig.Publics:type_name -> g1.protocol.PBARR_texas_string_1_f5f72933
	2, // 4: g1.protocol.TexasTestConfig.Chair1:type_name -> g1.protocol.PBARR_texas_float_2_eb6f30c5
	7, // 5: g1.protocol.TexasTestConfigAry.Ary:type_name -> g1.protocol.TexasTestConfig
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_config_texas_proto_init() }
func file_config_texas_proto_init() {
	if File_config_texas_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_texas_proto_rawDesc), len(file_config_texas_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_texas_proto_goTypes,
		DependencyIndexes: file_config_texas_proto_depIdxs,
		MessageInfos:      file_config_texas_proto_msgTypes,
	}.Build()
	File_config_texas_proto = out.File
	file_config_texas_proto_goTypes = nil
	file_config_texas_proto_depIdxs = nil
}
