#!/bin/bash
#
# 生成 g1_common/protocol/*.pb.go
#
# 此脚本位于 common/game_proto/ 下，但需要从主仓根目录调用（因为依赖主仓的
# lib/contrib/protoc 二进制和 Go 工具链）。调用方式见主仓 scripts/gen_common_proto.sh。
#
# 用法（从主仓根）：
#   cd common/game_proto && ./gen_code.sh
# 或经主仓脚本：
#   ./scripts/gen_common_proto.sh
#
# 环境变量（可选，由调用方传入）：
#   PROTOC_BIN_DIR  — protoc 二进制所在目录（含 bin/protoc 和 include/）
#                     若未设置，默认用主仓 ../../lib/contrib/protoc/<os>/

set -euo pipefail

SYSTEM=$(go env GOOS)
MODULE=github.com/Iori372552686/g1_common
BIN_DIR=.bin
PROTOC_GEN_GO=${BIN_DIR}/protoc-gen-go
PROTOC_GO_INJECT_TAG=${BIN_DIR}/protoc-go-inject-tag

# 定位 protoc：优先环境变量，回退到主仓 lib/contrib/protoc（相对 common/game_proto）
if [ -z "${PROTOC_BIN_DIR:-}" ]; then
    case "${SYSTEM}" in
        linux)   PROTOC_BIN_DIR=../../lib/contrib/protoc/protoc-33.2-linux-x86_64 ;;
        darwin)  PROTOC_BIN_DIR=../../lib/contrib/protoc/protoc-33.2-osx-aarch_64 ;;
        windows) PROTOC_BIN_DIR=../../lib/contrib/protoc/protoc-33.2-win64 ;;
        *) echo "unsupported GOOS: ${SYSTEM}" >&2; exit 1 ;;
    esac
fi

PROTOC="${PROTOC_BIN_DIR}/bin/protoc"
PROTOC_INCLUDE="${PROTOC_BIN_DIR}/include"

if [ "${SYSTEM}" = "windows" ]; then
    PROTOC_GEN_GO=${BIN_DIR}/protoc-gen-go.exe
    PROTOC_GO_INJECT_TAG=${BIN_DIR}/protoc-go-inject-tag.exe
    PROTOC="${PROTOC_BIN_DIR}/bin/protoc.exe"
fi

mkdir -p "${BIN_DIR}"
go build -o "${PROTOC_GEN_GO}" google.golang.org/protobuf/cmd/protoc-gen-go
go build -o "${PROTOC_GO_INJECT_TAG}" github.com/favadi/protoc-go-inject-tag

# Protocol-owned protos live under g1_common/game_proto/{core,config,storage,service}/.
# Generated Go stays in g1_common/protocol (即 ../protocol，与 game_proto 同级).
# Service protos with go_package pointing at GoOne/api/gen are generated by
# the main repo's `go run ./tools/cmd/genproto` and must be excluded here.
PROTO_FILES=()
while IFS= read -r f; do
  [[ -f "${f}" ]] || continue
  if grep -q 'github.com/Iori372552686/GoOne/api/gen/' "${f}"; then
    continue
  fi
  PROTO_FILES+=("${f}")
done < <(find core config storage service -name '*.proto' -type f | sort)

if [ "${#PROTO_FILES[@]}" -eq 0 ]; then
    echo "no protocol-owned proto files found"
    exit 0
fi

# 输出到 ../protocol（g1_common/protocol，与 game_proto 同级）
rm -rf ../protocol
"${PROTOC}" -I. -I"${PROTOC_INCLUDE}" \
    --plugin=protoc-gen-go="${PROTOC_GEN_GO}" \
    --go_out=.. \
    --go_opt=module="${MODULE}" \
    --go_opt=paths=import \
    "${PROTO_FILES[@]}"

if [ -f "../protocol/database.pb.go" ]; then
    "${PROTOC_GO_INJECT_TAG}" -input=../protocol/database.pb.go
    gofmt -w ../protocol/database.pb.go
fi

echo "✓ g1_common/protocol generated (../protocol/)"
