
/*
* 本代码由xlsx工具生成，请勿手动修改
*/

syntax = "proto3";

package g1.protocol;

option go_package = "./g1_protocol";


message DropItemConfing {
}

message DropItemConfingAry { 
	repeated DropItemConfing Ary = 1;
}

message ItemConfig {
}

message ItemConfigAry { 
	repeated ItemConfig Ary = 1;
}

message MachineConfig {
}

message MachineConfigAry { 
	repeated MachineConfig Ary = 1;
}

message MallConfig {
}

message MallConfigAry { 
	repeated MallConfig Ary = 1;
}

message RechargeConfig {
}

message RechargeConfigAry { 
	repeated RechargeConfig Ary = 1;
}

message TaskConfig {
}

message TaskConfigAry { 
	repeated TaskConfig Ary = 1;
}

message TexasConfig {
}

message TexasConfigAry { 
	repeated TexasConfig Ary = 1;
}

message TexasTestConfig {
}

message TexasTestConfigAry { 
	repeated TexasTestConfig Ary = 1;
}

